### PR TITLE
DOC-7456: Remove Deprecated UI option- All direct messages

### LINKED ISSUE #7456: Help Wanted: Remove Deprecated UI option
# Context

The **All direct messages** option for the direct messages list has been removed from the product and should be removed from the product documentation to avoid user confusion.

# Documentation Asks

Source file: preferences/customize-your-channel-sidebar.rst

Within the **How many direct messages to display** section:

1. Remove references to the **All direct messages** option.
2. Capture a new animated GIF without that option present, reuse the existing image file name, and model the new GIF animation based on the existing one.

# QA Validation Criteria

In a generated docs preview:
- Visiting the docs page directly results in the direct message option being removed from the text-based documentation as well as the associated animated GIF.

### PR DESCRIPTION
**Pull request by Rutam21**
### Summary

This PR removes the `All Direct Messages` option reference from the Customize your Channel Sidebar page. It also adds a new GIF to show the updated UI options available in the App.

### Ticket Link

Fixes #7456 

- [x] This PR follows the Mattermost Contributing Guidelines.

### CODE REVIEW

**Comment by Rutam21** [comment]
@cwarnermm Please review and suggest changes, if any. Thanks.

**Review by cwarnermm — APPROVED** [review]
Thank you, @Rutam21!!

**Comment by Rutam21** [comment]
@lindy65 You can assign this PR to me for QA Testing. Thanks.

**Comment by lindy65** [comment]
Assigned to you @Rutam21 :)

**Comment by Rutam21** [comment]
### The changes in this PR have been tested in the preview environment and all the required changes are available in the mentioned pages.

- `All Direct Messages` option reference has been removed from the Customize your Channel Sidebar page.
- The GIF in the `Manage direct messages` section on this page is updated and doesn't show the availability of this `All Direct Messages` option.

I've attached a video as a confirmation.

https://github.com/user-attachments/assets/825e8342-7b3c-44e3-b037-787a8662f220

cc: @lindy65

**Comment by lindy65** [comment]
Thanks for testing @Rutam21 - counted towards Hacktoberfest!

**Pull request merged**
