### PR TITLE
Manually updating channel handle/URL when renaming a channel

### PR DESCRIPTION
**Pull request by jasonblais**

### CODE REVIEW

**Comment by it33** [comment]
>You may also change the channel URL (also known as the channel handle) when renaming a channel. **The URL is not automatically updated to prevent unintentionally breaking existing links and integrations.**

Seems a little expert mode, it might be more important to be clear that changing a channel URL it will break existing links (will it break webhooks and permalinks too?)

I don't think anyone expects the channel URL to change when the UI name changes. It would be like updating the site name and expecting the entire server URL to change.

**Comment by jasonblais** [comment]
Thanks, updated

**Comment by esethna** [comment]
+1

**Comment by lfbrock** [comment]
+1

**Pull request merged**
