### PR TITLE
WIP: Onboarding Guide

### PR DESCRIPTION
**Pull request by it33**
Working on documentation to help enterprise on-boarding processes

### CODE REVIEW

**Comment by amyblais** [comment]
Closing this as this has been open with no activity for a while - it can always be re-opened if needed.

**Comment by it33** [comment]
Re-opening this. I think it's important to document on-boarding. Need an owner.

**Comment by wiersgallak** [comment]
@it33 I can own this guide.  I can see the benefit of having a document such as this and there are some things I'd like to add.

**Comment by it33** [comment]
Thanks @wiersgallak!

**Comment by it33** [comment]
@wiersgallak are you okay if we close this PR and move to GitLab feature proposal repo to discuss? https://gitlab.com/mattermost/proposals/issues/44

I was talking to Stu about this as well, and he's working on something here too.

**Pull request closed without merging**
