### PR TITLE
Adding Customer Thermometer to docs

### PR DESCRIPTION
**Pull request by justinegeffen**
Adding a rating functionality to the documentation.

### CODE REVIEW

**Comment by justinegeffen** [comment]
Putting together the content from: https://github.com/mattermost/docs/blob/pr-customer-thermometer/source/templates/customer_thermometer.html and although it's showing in the source code, it's not displaying in the output. 

@icelander, do you have any idea why this might be? I am able to display it on the index page though. See below: 
Screen Shot 2020-01-23 at 15 42 47

Screenshot from local build source code for reference: Screen Shot 2020-01-23 at 15 40 07

**Comment by jasonblais** [comment]
cc @asaadmahmood on above as well in case you have thoughts.

Thanks @justinegeffen for this! One additional question I have is what are your thoughts on using emojis instead of coloured dots to represent the rating? The emojis might more clearly convey emotion from the visitor. 0/5

**Comment by justinegeffen** [comment]
I'm 5/5 for using emojis - currently setting that up and getting new URLs for the feedback responses.

**Comment by justinegeffen** [comment]
Closing this PR as we're going with a custom UI as per: MM-23098

**Pull request closed without merging**
