### PR TITLE
Fixing broken links

### PR DESCRIPTION
**Pull request by amyblais**
One question for reviewer:
What is the link to GitLab Omnibus test build? [This link](http://ci-linux-gitlab-omnibus.mattermost.com/users/password/new?user_email=) in [this doc](https://docs.mattermost.com/process/gitlab-process.html) doesn't work.

### CODE REVIEW

**Comment by esethna** [comment]
^ Not sure, probably best to ask @jasonblais as he deals with GitLab

**Comment by jasonblais** [comment]
@amyblais Do you mean this link? http://ci-linux-gitlab-omnibus.mattermost.com/

It's kind of working, Derrick and Harrison are working on finishing that build: https://mattermost.atlassian.net/browse/MM-9717

**Comment by amyblais** [comment]
Yes, that link.
Ok, since it's already in our docs I guess ok to keep as is.

**Comment by jasonblais** [comment]
Yeah, we can keep it, should get fixed soon

**Pull request merged**
