### PR TITLE
Update system console doc formatting

### PR DESCRIPTION
**Pull request by esethna**
Tested locally to verify sphinx rendering. Changes include:

- Prioritizing UI labels over config.json labels
- Move config.json labels and options into a table cell

### CODE REVIEW

**Comment by jasonblais** [comment]
Are there any places where we might need to update links in other pages that reference cofig-settings.rst?

**Comment by esethna** [comment]
+1 from LI with one minor tweak

**Comment by esethna** [comment]
@jasonblais the links to section headings haven't changed with this PR. And in the case where we've posted a link directly to a setting, the link doesn't break, it just redirects to the top of the page.

**Comment by it33** [comment]
Just curious, is this feature in, or was it removed May 16? 

image

**Comment by it33** [comment]
Propose new text "Settings configurable only in config.json" to replace below text

image

**Comment by it33** [comment]
Other than the items above +1, really great work @esethna!!

**Pull request merged**
