### PR TITLE
Add instructions for Chinese fulltext search on PostgreSQL

### PR DESCRIPTION
**Pull request by schemacs**
Inspired by this [issue](/mattermost/platform/issues/2159), and also after failed to migrate the database to MySQL. Thanks for making mattermost!

### CODE REVIEW

**Comment by it33** [comment]
Thanks @schemacs! Highly appreciated, 

One suggestion: Propose including a link to `https://forum.mattermost.org/c/international/chinese`, which is a new forum area we've added to support discussion for the Chinese language community.

**Comment by schemacs** [comment]
@it33 the linked added.

**Comment by it33** [comment]
+1

**Comment by esethna** [comment]
Looks good, thanks @schemacs!

**Comment by esethna** [comment]
@schemacs sorry, maybe one more suggestion: Do you mind submitting a quick pull request to include a link to the MySQL requirements from: http://docs.mattermost.com/install/requirements.html#database-software

**Comment by schemacs** [comment]
@esethna OK, but I could not verify whether this works for Japanese, or Korean, so I just add another link just for Chinese?

**Comment by esethna** [comment]
@schemacs, yes, just for Chinese, that would be great! Thanks!

**Comment by schemacs** [comment]
@esethna Will this quick editing #100 be right?

**Pull request merged**
