### PR TITLE
MM-30048 Implement new websocket events for collapsed threads

### PR DESCRIPTION
**Pull request by cwarnermm**
Documentation for: https://mattermost.atlassian.net/browse/MM-30048

Updated:
-  Self-Managed Admin Guide > Configure Mattermost > Configuration Settings > Experimental Settings only in config.json > Service Settings
   - Added new Collapsed Threads configuration setting

### CODE REVIEW

**Comment by amyblais** [comment]
May also need to be documented in the Telemetry doc.

**Comment by cwarnermm** [comment]
@reflog - In the Telemetry documentation, CollapsedThreads is currently documented as a bool, rather than a string. Please let me know if that's technically correct or if changes are needed. Thanks!

**Comment by reflog** [comment]
@cwarnermm - it was a boolean initially, but not it's a tri-state: "off/default_on/default_off".
off - turned off completely
default_off - each user has to opt-in
default_on - each user has to opt-out

**Review by reflog — APPROVED** [review]

**Comment by cwarnermm** [comment]
Thanks, @reflog -- are tri-states also documented as bools in the Telemetry documentation? (they appear to be - just want to confirm).

**Comment by reflog** [comment]
Yup, it's the same in telemetry

**Comment by esethna** [comment]
@cwarnermm let's hold off on any docs for PRs for collapsed reply threads for now. In fact we should probably figure out our approach to documenting the entire feature once we are closer to implementation rather than piecemeal

**Comment by amyblais** [comment]
I'll close this for now so that it doesn't get introduced to the v5.31-documentation branch.

**Pull request closed without merging**
