### PR TITLE
Update nav components for 9.0 announce

### PR DESCRIPTION
**Pull request by emdecr**
#### Summary
This PR adds the 9.0 announce blog to the notification banner (set for 2 weeks), and updates the global nav to align with mm.com.

@cwarnermm – Feel free to adjust the footer links and I'll mirror the changes on mm.com. 

Also, I am going to put a DNM tag on until I can chat with Aaron about the fallback link once two weeks is up. Should be taken off early this morning.

Thank you!

### CODE REVIEW

**Comment by emdecr** [comment]
AT approved the copy and timeframe, so we're all good with all that~

**Comment by cwarnermm** [comment]
There's a few links we may want to revisit and a few we may want to realign with our messaging house. There's a few cases, noted below, where I'm not sure whether we want to adjust the website or leave as-is. All input is welcome.

In the header:
- Let's update the **Academy** link to point to: ``https://academy.mattermost.com/``
- [INPUT NEEDED] For the **Release Notes** link, we can keep it pointing to the self-hosted changelog OR we could update it to point to the changelog landing page instead: ``https://docs.mattermost.com/guides/changelogs.html``. I'm open to either.

In the footer:
- The **All Docs** link looks like it's missing the ``https://docs.mattermost.com/`` link, but that might be something auto-generated.
- [INPUT NEEDED] The **Admin** link redirects as expected. Do we want to keep it as **Admin** or update it to **Manage** or similar?
- [INPUT NEEDED] The **Playbooks** link redirects as expected. In the docs, we're de-emphasizing the vertical name **Mattermost Playbooks** in favour of the outcome **building repeatable processes**. Not sure if we want to make a similar update to our terminology here.
- [INPUT NEEDED] The **Channels** link redirects as expected. In the docs, we're de-emphasizing the vertical name in favour of the outcome **connect and collaborate**. This is another case where I'm not sure whether we want to do the same to the website.

Oh, and the Twitter logo is outdated.

**Comment by emdecr** [comment]
Thanks @cwarnermm! Comments sub-bulleted.

In the header:
- Let's update the Academy link to point to: https://academy.mattermost.com/
  - ✅ 
- [INPUT NEEDED] For the Release Notes link, we can keep it pointing to the self-hosted changelog OR we could update it to point to the changelog landing page instead: https://docs.mattermost.com/guides/changelogs.html. I'm open to either.
  - I think the move to https://docs.mattermost.com/guides/changelogs.html is a good call ✅ 
 
In the footer:
- The All Docs link looks like it's missing the https://docs.mattermost.com/ link, but that might be something auto-generated.
  - Yep, I've got the paths set to the root, so it'll pick up on whatever the domain is.
- [INPUT NEEDED] The Admin link redirects as expected. Do we want to keep it as Admin or update it to Manage or similar?
- [INPUT NEEDED] The Playbooks link redirects as expected. In the docs, we're de-emphasizing the vertical name Mattermost Playbooks in favour of the outcome building repeatable processes. Not sure if we want to make a similar update to our terminology here.
- [INPUT NEEDED] The Channels link redirects as expected. In the docs, we're de-emphasizing the vertical name in favour of the outcome connect and collaborate. This is another case where I'm not sure whether we want to do the same to the website.
  - Those three points are good flags. **Can I ask the team and circle back in another PR with their changes, if any?** We're still deciding on how we want to work in the de-emphasis of the vertical in favour of the outcomes, and a bunch of other messaging house changes (and how they affect structure and terminology).

Oh, and the Twitter logo is outdated.
- I believe this one is still on hold because other orgs have not made the change yet either (ex. Atlassian, GitLab, etc.). Asked the team again and waiting on their feedback.

I can push up the checkmarks shortly.

**Comment by cwarnermm** [comment]
@emdecr - Yes. A separate PR makes sense, given that there's discussion and alignment needed. Thanks!!

**Comment by emdecr** [comment]
@cwarnermm Just a heads up for this PR and the one for [dev docs](https://github.com/mattermost/mattermost-developer-documentation/pull/1292). I'm going to be OOO until next Monday starting tomorrow, but feel free to tag the marketing folks (AZ/Kevin/Aaron) if you need another pair of eyes for anything related.

Also update: We've decided to start updating the Twitter logo, but that will come in another PR once I sort a few thing.

TY!

**Review by cwarnermm — APPROVED** [review]
Thank you, @emdecr!!

**Pull request merged**
