### PR TITLE
Updated Doc / source / index.rst and merged some documents in Doc / source directory

### PR DESCRIPTION
**Pull request by yangshuaimeng**
There are two main contributions this time：
1. The guides in the doc / source directory contain the contents of about and overview. Therefore, about and overview are deleted and only guides are retained.
2. The index.rst in doc / source directory is modified and some contents are added.

### CODE REVIEW

**Comment by justinegeffen** [comment]
Thank you for your contribution, @yangshuaimeng! I noted that this PR contains a lot of deleted files - would you be open to talking us through this change? We'd like to understand it better before we proceed with reviewing it. Thank you!

**Comment by yangshuaimeng** [comment]
Thank you for your reply.I'd like to discuss this change with you.Thank you!



| |
杨帅盟
|
|
***@***.***
|
签名由网易邮箱大师定制
On 8/8/2021 16:57，Justine ***@***.***> wrote：

Thank you for your contribution, @yangshuaimeng! I noted that this PR contains a lot of deleted files - would you be open to talking us through this change? We'd like to understand it better before we proceed with reviewing it. Thank you!

**Comment by yangshuaimeng** [comment]
> 感谢您的贡献，@yangshuaimeng！我注意到此 PR 包含大量已删除的文件 - 您愿意与我们讨论此更改吗？我们希望在继续审查之前更好地理解它。谢谢！

Thank you for your reply.I'd like to discuss this change with you.Thank you!

**Comment by yangshuaimeng** [comment]
Thank you for your reply.I'd like to discuss this change with you.Thank you!

**Comment by yangshuaimeng** [comment]
> Thank you for your contribution, @yangshuaimeng! I noted that this PR contains a lot of deleted files - would you be open to talking us through this change? We'd like to understand it better before we proceed with reviewing it. Thank you!

Thank you for your reply.I'd like to discuss this change with you.Thank you!

**Comment by justinegeffen** [comment]
Hi @yangshuaimeng. I see you closed your PR. You're welcome to contact us via the Docathon channel if you'd like to chat about your PR. Otherwise, thank you for the time taken to submit it! :)

**Pull request closed without merging**
