### PR TITLE
upgrade to sphinx 4.4

### PR DESCRIPTION
**Pull request by svelle**
This upgrades sphinx to the latest version (4.4)

This includes some new features and re-enables parallel building on macos.

I tested this locally and everything seems to be fin but this might possible break a lot of stuff that I'm unaware of that's why I'm marking this as work in progress for now, but I need people from the docs team to review this because I don't know what's looking right or wrong.

### CODE REVIEW

**Comment by cwarnermm** [comment]
Hi @svelle! What's the motivation to upgrade Sphinx from v3.7 to v4.4? We've been using v3.7 intentionally for parallel build support since later versions didn't fully support it yet.

**Comment by svelle** [comment]
Screenshot 2022-01-18 at 15 28 24

Hey @cwarnermm I've upped this to reenable parallel building on macos and python 3.8+ versions. But as per our conversation yesterday we can hold off on the upgrade for now. Should we keep the PR open? It's really just a one line change so bringing this up to date once we merge it should be easy to do.

**Comment by cwarnermm** [comment]
@svelle - Let's keep this PR open. @neflyte is familiar with the parallel build code, and he's going to review how multi-core processing was implemented. The results of his investigation will help identify next steps towards updating our Sphinx instance.

**Comment by neflyte** [comment]
@svelle @cwarnermm I took a look at this on both macOS and Linux; both work perfectly! On macOS I used Python 3.9 with no issues. Python 3.8 on Linux also had no issues. :smile: This is a great fix from the Sphinx team! Good catch, @svelle :100:

**Review by cwarnermm — APPROVED** [review]

**Pull request merged**
