### PR TITLE
Add Style related documentation on interactive message buttons

### PR DESCRIPTION
**Pull request by larkox**
#### Summary
Add Style related documentation on interactive message buttons

#### Ticket Link
Fix https://github.com/mattermost/docs/issues/3725

### CODE REVIEW

**Comment by justinegeffen** [comment]
Thank you for this, @larkox! These docs have actually moved to https://developers.mattermost.com/integrate/admin-guide/admin-interactive-messages/ but haven't yet been archived in the repo (there is a PR open for it). Would you be open to making these changes in the dev-docs repo (it also counts as a docathon entry.)? :)

**Comment by larkox** [comment]
@justinegeffen Sure, no problem. I will do it :smile:

**Comment by justinegeffen** [comment]
Thanks, @larkox! Feel free to reference this one in that PR so we can close this and add the new PR to review. :)

**Comment by larkox** [comment]
@justinegeffen Done ;)

**Pull request closed without merging**
