### PR TITLE
Add an FAQ section for incoming webhooks

### PR DESCRIPTION
**Pull request by jasonblais**

### CODE REVIEW

**Comment by jasonblais** [comment]
Whoops. I just read further in the customer channel and saw @icelander you were gonna work on this. Feel free to edit, or resubmit a separate PR if you had something else in mind

**Comment by lfbrock** [comment]
Just to add - this is good, but we may want to specifically note how to send as a DM to yourself. 

For our one customer's use case, it sounds like they have the webhooks created by the Admin, and as a result it's being sent to the DM channel between the admin and the user instead of the user's personal DM channel. I'm not sure how common that is, but it might be an issue for teams where creating integrations is restricted to admins.

**Comment by jasonblais** [comment]
Maybe @icelander you can help with Lindsay's feedback?

**Comment by icelander** [comment]
I created a new pull request with this information that includes how to send to a specific DM channel: #1907

**Comment by lindy65** [comment]
Thanks @icelander - is it ok to close off this PR from JB then?

**Comment by jasonblais** [comment]
https://github.com/mattermost/docs/pull/1907 covers this

**Pull request closed without merging**
