### PR TITLE
V6.2 Docs

### PR DESCRIPTION
**Pull request by amyblais**

### CODE REVIEW

**Comment by amyblais** [comment]
cc @cwarnermm

**Comment by amyblais** [comment]
@justinegeffen @cwarnermm Ideally I would like to merge this in by today (end of day is fine).

**Review by justinegeffen — APPROVED** [review]
LGTM! Thanks all!

**Review by cwarnermm — APPROVED** [review]
Reviewed & corrected build issues and broken links. Ready to merge.

**Comment by amyblais** [comment]
I'll merge this tomorrow. There may be a fix needed for a v6.2 dot release, or it may be added to Known Issues.

**Comment by amyblais** [comment]
@cwarnermm A suggested edit for the changelog file https://github.com/mattermost/docs/pull/5287/files#diff-eba248b2c1a66750343693c8d84e6909fc3c26f299880afcc7261837a0465323:

Replace ``Release Day: 2021-12-16`` with:

 - **v6.1.1, release day TBD**
   - Investigating a SIGSEGV error after upgrade to v6.2.0 when plugins are disabled in config. It is recommended to enable plugins when upgrading to v6.2.0.

 - **v6.1.0, released 2021-12-16**
   - Original 6.1.0 release

**Pull request merged**
