### PR TITLE
Update product.rst

### PR DESCRIPTION
**Pull request by lindy65**
Removed superfluous comma from line 43

### CODE REVIEW

**Comment by lindy65** [comment]
I couldn't merge this directly - sorry...

**Comment by justinegeffen** [comment]
Thanks @lindy65! We use the Oxford comma in our documentation so there's always a comma before the "and" in a list. :) Thanks for the PR - it's good to know that some eagle eyes are reading the docs! :)

**Comment by lindy65** [comment]
Thanks @justinegeffen - I never use a comma before `and` because:

```
The AP Stylebook considers the Oxford Comma unimportant, and many journalists agree that they shouldn't be required to use it. Why don't they use it? Many opponents of the Oxford comma claim that it makes a piece of writing sound more pretentious and stuffy, and that it can make things seem cluttered and redundant.
```

Good to know though that MM prefers its use ;)

**Comment by justinegeffen** [comment]
Haha, yeah it's a contentious issue! We follow the Chicago Manual of Style for the most part and in technical writing we ideally want precision and clarity so it works well for our kind of writing. Journalism is a whole other ballgame and understandably has very different conventions. :)

**Comment by lindy65** [comment]
Cool... no worries...  It just looks and "feels" very weird to me ;)

**Comment by justinegeffen** [comment]
Totally get that! Took me a long while to get used to it too. :D

**Pull request closed without merging**
