### PR TITLE
DOC-7524: Rename channels page needs animated GIFs for mobile app workflows

### LINKED ISSUE #7524: Rename channels page needs animated GIFs for mobile app workflows
## Context

To help visual learners learn how to perform tasks using the Mattermost mobile app, add visuals and short animated GIFs on the [Rename channels](https://docs.mattermost.com/collaborate/rename-channels.html) page.

## Docs Request

- Add appropriate visuals/GIFs for all the steps in the `Rename channels` section under the mobile app tab.

## Additional Notes

- Use the latest Mattermost mobile app and the standard Mattermost Denim theme to capture all workflows.
- Avoid drawing lines, arrows, boxes, or callouts on images.
- Don't forget to include ALT Text descriptions for all new image assets.
- Use existing docs pages with images as a starting point for code guidance. The Docs team can help provide RST syntax support for publication.
- Save static image files in PNG format within the docs repository's `/images` directory.

# QA Validation Criteria

In a generated docs preview:
- Visiting the docs page results in 4 new mobile-specific screenshots in each subsection from the **Mobile** tab.

### PR DESCRIPTION
**Pull request by Rutam21**
### Summary

This PR adds visual workflows for the Mattermost mobile app tab on the [Rename channels](https://docs.mattermost.com/collaborate/rename-channels.html) page

### Ticket Link

Fixes #7524 

- [x] This PR follows Mattermost Contributing Guidelines.

### CODE REVIEW

**Comment by Rutam21** [comment]
@cwarnermm Please review and suggest changes, if any. Thanks.

@lindy65 Please add this to my queue for QA Testing once the reviews are complete. Thank you.

**Review by cwarnermm — APPROVED** [review]
Thank you, @Rutam21!

**Comment by varghesejose2020** [comment]
@lindy65  please assign me

**Comment by Rutam21** [comment]
## The changes are tested in the preview environment and they reflect properly.

- The `Rename channels` page has now 5 workflow images for visual learners.

Please refer to the screenshots below as a confirmation.

### Current Docs Page [[Rename Channels](https://docs.mattermost.com/collaborate/rename-channels.html)]

Screenshot 2024-10-31 185923

### Preview Environment Page

**Step 1**

Screenshot 2024-10-31 185953


**Step 2**

Screenshot 2024-10-31 190059

**Step 3**

Screenshot 2024-10-31 190114

**Step 4**

Screenshot 2024-10-31 190129

**Step 5**
Screenshot 2024-10-31 190144


cc: @lindy65

**Pull request merged**
