### PR TITLE
updated User management configuration settings

### PR DESCRIPTION
**Pull request by ayrotideysarkar**

### CODE REVIEW

**Comment by cwarnermm** [comment]
This is a very good start, @ayrotideysarkar! Thank you.

Please remember to write in full, complete sentences including proper capitalization and punctuation. Also, remember to use existing documentation content as a guide when drafting new content. Many existing docs pages contain similar language that you should apply in your own drafts to ensure consistency.

Once you have this content fully drafted with the above guidelines in mind, I'll review the PR in full. Thanks!

**Comment by ayrotideysarkar** [comment]
@cwarnermm  can you check and give feedback  for the changes I made?

**Comment by cwarnermm** [comment]
Hi @ayrotideysarkar! Is this PR draft complete or are you planning on making additional updates?

**Comment by ayrotideysarkar** [comment]
> Hi @ayrotideysarkar! Is this PR draft complete or are you planning on making additional updates?

it's not completed I will add some more details I just need your feedback before adding more details

**Comment by cwarnermm** [comment]
Our team's process is to provide feedback when this PR is draft complete. Thanks!

**Pull request closed without merging**
