### PR TITLE
Update docs regarding the Slack Attachment format

### PR DESCRIPTION
**Pull request by ZJvandeWeg**

### CODE REVIEW

**Comment by it33** [comment]
Thanks for the contribution!

Link formatting needs to be RST, update proposed: https://github.com/ZJvandeWeg/docs/pull/1

Also proposing tweaks to intro text.

**Comment by ZJvandeWeg** [comment]
@it33 I merged that, now this should be good :)

**Comment by it33** [comment]
Thanks @ZJvandeWeg 

You're the first contributor to our [Holiday Hackfest](https://about.mattermost.com/hackfest-leaderboard/), congrats! 

image

**Comment by ZJvandeWeg** [comment]
@it33 Cool. Ill add docs on your API soon too. So maybe you can bring an extra T-Shirt to Mexico!

**Pull request merged**
