### PR TITLE
Added Spellchecker Action [Docathon 2021]

### PR DESCRIPTION
**Pull request by AdvaitDhingra**
#### Summary

I added a spellchecker action for rust files.
#### Ticket Link

n/A

### CODE REVIEW

**Comment by justinegeffen** [comment]
Thanks for this PR it looks really well done.

Could you give us a run-down of how it will work? I see it's a .yml file which has been added to our workflows. Is this something we'd need to add to the Sphinx config and build files as well? And is there a CircleCI impact if the check fails? We have a number of checks and balances for our PRs, such as a preview server being spun up, a number of checks for the build, etc. Having an idea of pass/fail behavior means we can ascertain whether this would be a mandatory check or not.

It would be awesome to find out how this interacts with Sphinx in general, and whether we need to install an extension or whether it just slots into the config.

Lastly, if you could take us through the list of words and how they're matched to content and whether it's suggested or find and replace that'd be awesome. 

I really look forward to learning more about this!

**Comment by AdvaitDhingra** [comment]
> Thanks for this PR it looks really well done.
> 
> Could you give us a run-down of how it will work? I see it's a .yml file which has been added to our workflows. Is this something we'd need to add to the Sphinx config and build files as well? And is there a CircleCI impact if the check fails? We have a number of checks and balances for our PRs, such as a preview server being spun up, a number of checks for the build, etc. Having an idea of pass/fail behavior means we can ascertain whether this would be a mandatory check or not.
> 
> It would be awesome to find out how this interacts with Sphinx in general, and whether we need to install an extension or whether it just slots into the config.
> 
> Lastly, if you could take us through the list of words and how they're matched to content and whether it's suggested or find and replace that'd be awesome. 
> 
> I really look forward to learning more about this!
> 
> 

Thanks for your feedback 

The workflow goes through everything and checks it for spelling. If the word is unknown and isn't on the word list, it gets marked as wrong. This word list is in word list.txt and I just added the words it was marking as wrong but weren't. 

I think I can configure it so that even if the test fails you can still merge. Or maybe if a new contribution adds a word that gets marked as wrong, it is that contributors responsibility to add it to wordlist.txt. Then we could make it mandatory. 

We can do it however you want.
Not sure on how this would affect CircleCI but I'll get back to you on that.

**Comment by justinegeffen** [comment]
Thanks @AdvaitDhingra! So is the word list a list of correct words, or words that would be flagged as incorrect? 

As I understand it, I'd open a PR, and this process would be part of the checks that are run. Words that are similar to or exact matches for the words on the list would get flagged for investigation. Then I'd review the files and correct if needed?

If so, I have a few more questions. :)

- Would those identified words be highlighted in the files or have their position in the file listed? For a PR with a single file reviewing wouldn't be hard. But a PR with multiple files or large files would be arduous to re-review and an indication of what line the issue is on would help.
- What would the criteria of a "wrong" word be? Say a word like "*mattermost*" is listed , would the formatting mean it's flagged as incorrect or does formatting not matter?
- You mentioned the words added were words marked as "wrong" but aren't. Is that in your browser or in your editor? For example, in my browser "mattermost" and "Mattermost" are marked as incorrect so just want to confirm where the original issue is.

I think this is a really intriguing PR with potential, hence all the questions. :) We always do a lot of investigation and testing for any addition to our processes to ensure that if it's implemented we know how it works and its limitations. :)

**Comment by AdvaitDhingra** [comment]
> Thanks @AdvaitDhingra! So is the word list a list of correct words, or words that would be flagged as incorrect?
> 
> As I understand it, I'd open a PR, and this process would be part of the checks that are run. Words that are similar to or exact matches for the words on the list would get flagged for investigation. Then I'd review the files and correct if needed?
Yes.
> 
> If so, I have a few more questions. :)
> 
> * Would those identified words be highlighted in the files or have their position in the file listed? For a PR with a single file reviewing wouldn't be hard. But a PR with multiple files or large files would be arduous to re-review and an indication of what line the issue is on would help.
Yes, you get the location of the file. You don't however have the location of the word, but finding individual words is a no-brainer with modern IDE's.
> * What would the criteria of a "wrong" word be? Say a word like "_mattermost_" is listed , would the formatting mean it's flagged as incorrect or does formatting not matter?
PySpelling uses Apsell, so a word that is not in it's dictionary. I'm just realizing that names will be marked as wrong. They would have to be added to wordlist.txt . Maybe under a section for names.
> * You mentioned the words added were words marked as "wrong" but aren't. Is that in your browser or in your editor? For example, in my browser "mattermost" and "Mattermost" are marked as incorrect so just want to confirm where the original issue is.
I ran PySpelling locally and it gave me the words that it thought were wrong, There are still a few more to add to the list, though.
> 
> I think this is a really intriguing PR with potential, hence all the questions. :) We always do a lot of investigation and testing for any addition to our processes to ensure that if it's implemented we know how it works and its limitations. :)

:D

**Comment by AdvaitDhingra** [comment]
The workflow runs on all PR's and all pushes to master

**Comment by justinegeffen** [comment]
Thanks, @AdvaitDhingra! We will need to look into this a bit more, possibly in a test environment. We'd also like to compare it to the Sphinx extension to understand the similarities/differences. :)

**Comment by cwarnermm** [comment]
Hi @AdvaitDhingra! Thanks for your contribution! Incorporating a spell checker into our workflows is an excellent idea. However, after a thorough review of your PR, we've identified that this spell checker implementation isn't aligned closely enough with our current technology stack and tools. We won't be moving forward with this PR. We appreciate your Docathon 2021 contribution and look forward to working with you on other PRs.

**Pull request closed without merging**
