### PR TITLE
Update prod-docker.rst

### PR DESCRIPTION
**Pull request by Mario-Hofstaetter**
Correct docs on how to setup Team Edition.
There is no `dockerfile: Dockerfile-enterprise` in the current `docker-compose.yml` file

Edit: the compose file in question is: [mattermost-docker/blob/master/docker-compose.yml](https://github.com/mattermost/mattermost-docker/blob/master/docker-compose.yml)

### CODE REVIEW

**Comment by amyblais** [comment]
@pichouk Would you be interested in taking a look at the changes made here in this doc PR?

**Comment by Mario-Hofstaetter** [comment]
@amyblais I've already signed the CLA, and my Username is listed in the google spreadsheet.
Is it normal the check is still marked as not ok?

**Comment by cpanato** [comment]
@Mario-Hofstaetter all good thanks 😄

**Comment by pichouk** [comment]
LGTM

**Pull request merged**
