### PR TITLE
6.3.6 ESR dot release docs

### PR DESCRIPTION
**Pull request by amyblais**
Note: I'll add the release date once ready.

### CODE REVIEW

**Review by justinegeffen — APPROVED** [review]

**Comment by amyblais** [comment]
@cwarnermm @angeloskyratzakos Do you have any ideas why this says "merge/blocked"? Have you seen this before?

**Comment by cwarnermm** [comment]
I suspect we're continuing to face the CircleCI issue that was causing a similar blockage for me yesterday. See https://community-daily.mattermost.com/private-core/pl/ge5aqp3i77yr7k4bbe3z7obmdr for context. 

We have 2 ways forward for this PR: restart CircleCI or commit something new to the PR to restart the Circle CI processes. I'm not currently seeing a way to restart CircleCI for the docs repo.

**Comment by pfltdv** [comment]
@cwarnermm Currently github has issues and all actions are delayed. I've restarted the job, it will update the checks. Unfortunately it will take time to update. https://www.githubstatus.com/

**Comment by cwarnermm** [comment]
Thanks, @pfltdv, for the confirmation that GitHub issues are ongoing, and for pushing this PR forward manually!

**Pull request closed without merging**
