### PR TITLE
DOC-7453: Document New Server Configuration Setting- Mobile External Browser

### LINKED ISSUE #7453: Help Wanted: Document New Client Configuration Property
# Context

https://github.com/mattermost/mattermost-mobile/pull/8220 introduces a new client configuration property that determines whether the mobile app should use the default external browser to perform SSO Authentication instead of the internal one.

# Documentation Ask

Source file: configure/site-configuration-settings.rst

Within the **Customization** section, add the new configuration setting (and its associated search metadata located directly above a section title) as a new section on this page.

Position the new configuration setting immediately following the **App custom URL schemes** section, and format the details of the section modelled after the [report a problem](https://docs.mattermost.com/configure/site-configuration-settings.html#report-a-problem-link) configuration setting.

Include the following configuration setting details:
- Section title: Mobile external browser
- Available only for self-hosted deployments
- Description: Configures the mobile app to perform SSO Authentication using the external default browser.
- String input. 
- System Config path: N/A
- config.json = NativeAppSettings -> MobileExternalBrowser
- Environment variable = MM_NATIVEAPPSETTINGS_MOBILEEXTERNALBROWSER

# QA Validation Criteria

In a generated docs preview:
- Searching for the new configuration setting returns the correct details.
- Visiting the docs page directly returns details about the new configuration setting.

### PR DESCRIPTION
**Pull request by Rutam21**
### Summary

This PR adds a Mobile External Browser section in the Site Configuration Settings page with the necessary configuration setting options available to the users.

### Ticket Link
Fixes #7453 

- [x] This PR follows the Mattermost Contributing Guidelines.

### CODE REVIEW

**Comment by Rutam21** [comment]
@cwarnermm Please review and suggest changes, if any. Thanks.

**Review by cwarnermm — APPROVED** [review]
Thanks, @Rutam21!

**Comment by Rutam21** [comment]
@lindy65 Please assign this PR to me for QA Testing. Thanks.

**Comment by lindy65** [comment]
Assigned @Rutam21 👍

**Comment by Rutam21** [comment]
### The changes in this PR have been tested in the preview environment and all the required changes are available in the mentioned pages.

- A new `Mobile external browser` section has been added under the `Customization` section which is available on the `Site Configuration Settings` page.
- This section has proper formatting and a link to this section is also available in the list of contents on the right side of the page.

I've attached a video as a confirmation.

https://github.com/user-attachments/assets/5333e125-820e-4326-9420-b5077daad3cf

cc: @lindy65

**Comment by lindy65** [comment]
Thank you @Rutam21 - counted towards Hacktoberfest!

cc @cwarnermm

**Pull request merged**
