### PR TITLE
Updated mmctl channel delete requirements

### PR DESCRIPTION
**Pull request by glennschler**
Updated mmctl channel delete documentation to clarify that Enable API Channel Deletion config setting must be enabled. Removed note in configuration setting documentation about local mode ignoring this setting.

Update for issue #5466

### CODE REVIEW

**Comment by glennschler** [comment]
@cwarnermm Should I submit this PR again to the v6.6documentaion branch instead of this branch?

**Comment by cwarnermm** [comment]
If you're able to submit this PR against the `v.6.6-documentation` branch, that would be great!

**Comment by glennschler** [comment]
@cwarnermm I submitted a new PR to mattermost:v6.6-documentation from my fork. I hope that helps. Let me know if I should do something to merge into master

**Comment by cwarnermm** [comment]
Closing.

**Pull request closed without merging**
