### PR TITLE
DOPS-380 Add 404.html that redirects to index.html

### PR DESCRIPTION
**Pull request by jwilander**
#### Summary
This will allow us to serve 404s to this page and then redirect to the root. This should fix the weird relative route for static assets on non-existent pages.

#### Ticket Link
https://mattermost.atlassian.net/browse/DOPS-380

### CODE REVIEW

**Review by cpanato — APPROVED** [review]

**Review by cwarnermm — APPROVED** [review]
Thanks!

**Comment by justinegeffen** [comment]
@lawrencejohnson, this is the PR for the issue you reported. If you're able to review it, that'd be great!

**Review by harryfromwork — APPROVED** [review]

**Comment by justinegeffen** [comment]
@jwilander, is the 404 page meant to be deleted? Just wondering where a reader gets directed if they hit a 404?
@lawrencejohnson, that makes sense. We'll test this in prod once it's merged. I think there's another PR for that S3 change though.

**Comment by jwilander** [comment]
Made the change in S3/cloudfront @lawrencejohnson

**Comment by lawrencejohnson** [comment]
> Made the change in S3/cloudfront @lawrencejohnson

Looks good, I'm seeing this returned:

```
<!DOCTYPE html>
<html>
<head>
  <title>404 Page Not Found</title>
  <meta http-equiv="refresh" content="0;url=https://docs.mattermost.com"/>
</body>
</html>
```

Is there any chance we can change the status code returned from 200 to 404?

**Comment by jwilander** [comment]
@lawrencejohnson set it to return 404

**Comment by lawrencejohnson** [comment]
Awesome, confirmed.

**Pull request merged**
