### PR TITLE
Add 'mark messages read or unread' section

### PR DESCRIPTION
**Pull request by jasonblais**

### CODE REVIEW

**Comment by esethna** [comment]
@jasonblais I know this isn't related to composing messaged but it seems like this could go in the messages table rather than its own section?

**Comment by jasonblais** [comment]
2/5 too, but that makes sense.

Had a PR ready to submit for `/shortcuts`, will submit now with the latest change

**Comment by lindy65** [comment]
+1

**Comment by esethna** [comment]
+1, thanks!

**Pull request merged**
