### PR TITLE
Update upgrade.md

### PR DESCRIPTION
**Pull request by lfbrock**

### CODE REVIEW

**Comment by it33** [comment]
Thanks @lfbrock, propose adding sub-bullets and links to guides directly? 

image

**Comment by lfbrock** [comment]
Updated, but there is an issue where clicking on a link on the same page takes you to slightly below the actual heading, so we may want to break them out into separate pages later. 

screenshot 2016-07-19 11 52 09

**Comment by it33** [comment]
@lfbrock super minor, instead of "and above, and earlier" propose "and later, and earlier"? 

image

Otherwise +1, thanks!

**Comment by lfbrock** [comment]
Fixed, and also updated the section about what versions can upgrade - can you review it to make sure it's clear enough?

screenshot 2016-07-19 12 29 02

**Comment by jasonblais** [comment]
+1, reviewed earlier and latest changes look good

**Comment by it33** [comment]
@lfbrock, propose simplifying to get everyone one to 3.2, since there's security updates there that aren't in 3.1

image

**Pull request merged**
