### PR TITLE
Academy links added contextually

### PR DESCRIPTION
**Pull request by cwarnermm**
Mattermost Academy links added conceptually to applicable documentation topics based on this [spec](https://docs.google.com/document/d/1vH0Qc3EYpIZalIZdo8zrv_VV7w-O58BCRG7RIBTc6VI/edit#heading=h.gxme6upk1yq3)

Repurposed the existing badge design code for these Academy links. Additional branding/styling can be applied to a specific ``academy-badge`` class if needed.

@matthewbirtch - I welcome your input on this docs PR. Is UX open to advising on look and feel for these Academy call outs?

### CODE REVIEW

**Comment by emdecr** [comment]
Hey @cwarnermm  – just queuing this up - some Qs:

1. Where can I find the image used in[ the callout](https://app.asana.com/0/1201867728201087/1205806463438845)? The one with the laptop and clicky/cursor accent?
2. Is there a Figma for the callout? Just wanna make sure I got colours right. 

TY!

**Comment by cwarnermm** [comment]
@matthewbirtch - Can you help provide the image assets needed, please?

**Comment by matthewbirtch** [comment]
@emdecr @cwarnermm you can find the callout in [this figma file](https://www.figma.com/file/5JeZlsoA9aAhPk9ZXEXbj6/Visuals-used-in-docs?type=design&node-id=13-2&mode=design&t=b5qGjj2i0JwFpW6G-4)

Or you can use this image directly:
academy-thumbnail-end-user-onboarding

**Comment by cwarnermm** [comment]
@emdecr - Yes to all 4. And thank you!

**Comment by emdecr** [comment]
@cwarnermm This should be good for a first round of reviews. I did a bulk update, so def flag if some badge instances look wonky on certain pages. Thanks!

**Comment by emdecr** [comment]
Oh and one note: @matthewbirtch I added a placeholder hover style on the badges (just a bg colour change for now) – lemme know if you had specs in mind. TY!
Ex pg: http://mattermost-docs-preview-pulls.s3-website-us-east-1.amazonaws.com/6733/collaborate/collaborate-using-mattermost-for-microsoft-teams.html

**Comment by cwarnermm** [comment]
These additions look FANTASTIC, @emdecr and @matthewbirtch!! Thank you both so much!

@emdecr - One Academy link is missing from this PR on the [Search for messages](https://docs.mattermost.com/collaborate/search-for-messages.html) page. 

Also, I noticed that the perma links don't resolve yet to Academy; I imagine that's expected. :)

**Comment by matthewbirtch** [comment]
> Oh and one note: @matthewbirtch I added a placeholder hover style on the badges (just a bg colour change for now) – lemme know if you had specs in mind. TY! Ex pg: http://mattermost-docs-preview-pulls.s3-website-us-east-1.amazonaws.com/6733/collaborate/collaborate-using-mattermost-for-microsoft-teams.html

Looks great @emdecr. I'm good with this hover state @emdecr. If we could also add a `border-color: #DDDFE4` on hover, that would be good too. 

I also just noticed that the layout of the callout breaks a bit between 768-960.
image

Looks great other than that!

**Comment by emdecr** [comment]
@cwarnermm Thanks Carrie!

- I don't see an `.. include::` on that search page template. Where did we want it placed and which badge? `academy-search.rst`?
- And yes, re: links – just added a [task](https://app.asana.com/0/1204612713651629/1205864479767498/f). Using [this doc](https://docs.google.com/document/d/1vH0Qc3EYpIZalIZdo8zrv_VV7w-O58BCRG7RIBTc6VI/edit?usp=sharing) as reference – should be able to get to them all today.

@matthewbirtch Appreciate the flag + feedback! Should be fixed and added the border colour change 👍

**Comment by cwarnermm** [comment]
@emdecr - Sounds like I missed adding that link, not you! :) Whoops! Yes, it would be the ``academy-search`` badge; the pl would be ``/pl/mattermost-academy-search-training``. Placement would be directly following the intro text and before the first heading on that page. Really appreciate your help with this! Sorry for the miss!

And thanks for creating the pl links too! :)

**Comment by matthewbirtch** [comment]
> @matthewbirtch Appreciate the flag + feedback! Should be fixed and added the border colour change 👍

Nailed it! Thanks

**Comment by matthewbirtch** [comment]
Sorry, one more _really_ minor detail @emdecr: the border radius on the left side of the callout seems a little off. I think because there is the same border radius applied to both the outer container and the top-left and bottom-left corner of the image. We probably need to adjust the radius on the inner image to 5px instead of 6px to fix that.

**Comment by emdecr** [comment]
@matthewbirtch No detail is too minor 😁  – def keep flagging anything; appreciate it 👍

**Review by matthewbirtch — APPROVED** [review]
Looks great to me!

**Comment by emdecr** [comment]
@cwarnermm Circling-back to say the `/pl/` links should be live, but just holler if one's missing. TY!

**Pull request merged**
