### PR TITLE
Doc changes for platform repo split.

### PR DESCRIPTION
**Pull request by jasonblais**
WIP. Updates left:
1) ~~Update platform meeting names after we've settled on the new name~~ Will be submitted separately
2) ~~Update localization process (https://github.com/mattermost/docs/blob/jasonblais-platform-repo-split/source/developer/localization.rst) once new process implemented.~~
3) ~~Update developer machine setup once build processes set up:~~ Covered by https://github.com/mattermost/docs/pull/1480
4) ~~Update code contribution guidelines once build processes set up~~ Covered by https://github.com/mattermost/docs/pull/1483
5) ~~Update core developer flow once build processes set up~~
 - ~~https://github.com/mattermost/docs/edit/jasonblais-platform-repo-split/source/developer/core-developer-handbook.md~~ Covered by https://github.com/mattermost/docs/pull/1484
 - ~~https://github.com/mattermost/docs/blob/e36f91afa1a80cc2dbc194f84b6740b129742e65/source/developer/developer-flow.md~~

### CODE REVIEW

**Comment by jespino** [comment]
Hi, I created a PR to this branch with the changes in the dev-setup-{system}.rst files. I hope it helps :)

**Comment by jasonblais** [comment]
@jespino It helps a lot!! Thank you :)

**Comment by jespino** [comment]
I have some extra changes in my PR for the developer-flow already reviewed. Take a look to it if you want to include the changes.

**Comment by lindy65** [comment]
Will do @esethna

**Comment by lindy65** [comment]
Checked all master docs and could not find anything that looked broken.

**Pull request merged**
