### PR TITLE
Add important note to zoom integration

### PR DESCRIPTION
**Pull request by saturninoabril**
Add important note to zoom integration. This PR is made in reference to community response at [Mattermost forum](https://forum.mattermost.org/t/solved-error-message-when-trying-to-launch-a-zoom-videoconference/4372/7?u=saturnino)

screen shot 2018-01-22 at 9 11 29 pm

### CODE REVIEW

**Comment by saturninoabril** [comment]
I fixed merge conflicts but then I realize that the recent merge added note similar to this PR. 
@lindy65 Please help check how to better state the notes. Thanks!

screen shot 2018-01-24 at 2 01 22 am

**Comment by lindy65** [comment]
@saturninoabril - I have combined the "Note" and "Important" into one...  Thoughts?

**Comment by saturninoabril** [comment]
Looks good to me, thanks @lindy65!

**Comment by lindy65** [comment]
Thanks @saturninoabril :)

**Pull request merged**
