### PR TITLE
DOC-7455: Remove 4 experimental configuration settings that are no lo…

### LINKED ISSUE #7455: Help Wanted: Remove configuration settings from documentation
# Context

4 experimental configuration settings are no longer active in the product code base and can be safely removed from product documentation.

# Documentation Ask

Remove the following 4 configuration settings (including their associated search meta data located directly above each section title):
* [Latest Android version](https://docs.mattermost.com/configure/experimental-configuration-settings.html#latest-android-version)
* [Minimum Android version](https://docs.mattermost.com/configure/experimental-configuration-settings.html#minimum-android-version)
* [Latest iOS version](https://docs.mattermost.com/configure/experimental-configuration-settings.html#latest-ios-version)
* [Minimum iOS version](https://docs.mattermost.com/configure/experimental-configuration-settings.html#minimum-ios-version)

### PR DESCRIPTION
**Pull request by Rutam21**
### Summary

This PR removes the following 4 configuration options from the `Experimental configuration settings` page.

- Latest Android version
- Minimum Android version
- Latest iOS version
- Minimum iOS version

The Metadata for these sections are also removed from the page.

### Ticket Link

Fixes #7455 

- [x] This PR follows the Mattermost Contributing Guidelines.

### CODE REVIEW

**Comment by Rutam21** [comment]
@cwarnermm Please review and suggest changes, if any.

**Review by cwarnermm — APPROVED** [review]
Thanks, @Rutam21!

**Comment by Rutam21** [comment]
@lindy65 Please assign this PR to me for QA Testing. Thanks.

**Comment by Rutam21** [comment]
### The changes in this PR have been tested in the preview environment and all required changes are observed.

The requested 4 sections have been removed.

- Latest Android version
- Minimum Android version
- Latest iOS version
- Minimum iOS version

Please find the snapshots attached comparing the current Docs with the preview environment Docs.

#### Current Docs

CurrentDocs

#### Preview Environment Docs

PRTestDocs

cc: @lindy65

**Comment by lindy65** [comment]
Thanks for testing @Rutam21 - counted towards Hacktoberfest

cc @cwarnermm

**Pull request merged**
