### PR TITLE
Prioritize PostgreSQL in deploy docs

### PR DESCRIPTION
**Pull request by azigler**
Hi @cwarnermm and @nab-77!

Based on our conversation in the training outline, I went through our various deploy docs and made sure PostgreSQL is mentioned before MySQL everywhere I could find them. Let me know if I missed anything!

### CODE REVIEW

**Review by cwarnermm — APPROVED** [review]
Thanks, @azigler!

**Review by cwarnermm — APPROVED** [review]
Thank you, @azigler!

**Comment by azigler** [comment]
@cwarnermm Hey Carrie, it looks like the MySQL instructions on [this page](https://docs.mattermost.com/install/install-rhel-8.html) are spilled into the PostgreSQL tab, so the tabbed box is broken after my changes. Do you mind taking a look and taming the Sphinx to help me out? 😄

**Comment by cwarnermm** [comment]
@azigler - Fixed via https://github.com/mattermost/docs/pull/6407

**Pull request merged**
