### PR TITLE
docs: update mattermost version in k8s examples

### PR DESCRIPTION
**Pull request by fmartingr**
#### Summary

This pull requests updates the version used in operator examples to prevent people from copying and pasting the example and accidentally deploy an older version, with a comment so we try to make sure people deploy the version they want to deploy.

Direct link to changes in preview environment: http://mattermost-docs-preview-pulls.s3-website-us-east-1.amazonaws.com/6839/install/install-kubernetes.html

### CODE REVIEW

**Comment by cwarnermm** [comment]
Thank you, @fmartingr! Great update! Do you recommend that this version increment as we release new versions of Mattermost? If so, this is something we can add to the monthly release playbook. CC @amyblais

**Comment by fmartingr** [comment]
> Thank you, @fmartingr! Great update! Do you recommend that this version increment as we release new versions of Mattermost? If so, this is something we can add to the monthly release playbook. CC @amyblais

I don't think that's necessary, at least for the time being. I just wanted to put an obvious comment there about users checking the latest version. Maybe we should strip the version parameter so readers are forced to do so? Do we have an automated way of inserting the latest stable version there automatically?

**Comment by cwarnermm** [comment]
@fmartingr - Updating the version numbers is currently a manual task that Release Management manages.

Are you open to helping resolve the merge conflict on this PR?

**Comment by fmartingr** [comment]
> Are you open to helping resolve the merge conflict on this PR?

Done!

**Pull request merged**
