### PR TITLE
Revisiting ubuntu key update instructions

### PR DESCRIPTION
**Pull request by phoinixgrr**
#### Summary

Building on https://github.com/mattermost/docs/pull/7050 
- We are revisiting key update instructions for ubuntu focal and jammy
- We are removing support for EOL bionic 18.04 LTS Ubuntu distribution.

### CODE REVIEW

**Review by saturninoabril — APPROVED** [review]
Thanks @phoinixgrr!

**Review by toninis — APPROVED** [review]

**Comment by phoinixgrr** [comment]
Before: 
Screenshot 2024-04-18 at 13 47 01
After: 
Screenshot 2024-04-18 at 13 56 29

**Comment by cwarnermm** [comment]
Thanks, @phoinixgrr! Given that we're removing support for EOL bionic 18.04 LTS Ubuntu distribution, I'd like to commit additional, related updates to this documentation PR, if you don't mind, archiving the 18.04 docs officially.

**Comment by phoinixgrr** [comment]
Awesome @cwarnermm ❤️ 
Thank you

**Pull request merged**
