### PR TITLE
PLT-8007 - Fixing mobile app links

### PR DESCRIPTION
**Pull request by asaadmahmood**
Hey guys have a look, a minor fix for the links.
Ticket: https://mattermost.atlassian.net/browse/PLT-8007

### CODE REVIEW

**Comment by lfbrock** [comment]
@lindy65 - we can't merge this, I think it gets rid of the links to the pages? Please add the links somewhere else, we can't just remove them....

**Comment by lindy65** [comment]
@lfbrock, I think this was a PR that you originally worked on where the links don't display properly.  Perhaps @asaadmahmood can take another look to see if he can fix them to look like the links in the screenshot of the ticket linked above?

**Comment by asaadmahmood** [comment]
@lfbrock Since those links are within that page, and clicking on these links takes you to the sections, wouldn't that be enough? Similar to other links that link to the respected section? Or do these also need the link specific for some reason?

**Comment by lfbrock** [comment]
They are separate documents, not within the page. See https://docs.mattermost.com/mobile/mobile-overview.html. 

To clarify: 
1. The links currently work, they are links to separate documents 
2. They look strange in the menu

We should either: 
1. Fix the way they look in the menu 
or 
2. Remove the links from the title and put them within the text instead

@asaadmahmood if 1 isn't possible / not worth the work, @lindy65 can you make a pull request for option 2.

**Comment by lindy65** [comment]
@asaadmahmood - I think you've fixed the way these types of links look in the docs before?  Let me know whether you can fix - if not, I'll make a PR for option 2. above.  Thanks!

**Comment by asaadmahmood** [comment]
@lindy65 I think lets just go with the second option.

**Pull request closed without merging**
