### PR TITLE
[MM-55587] Add documentation for call transcriptions settings

### PR DESCRIPTION
**Pull request by streamer45**
#### Summary

PR updates the documentation for the new plugin settings that control the upcoming call transcriptions functionality.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-55587

### CODE REVIEW

**Review by cpoile — APPROVED** [review]
Thank you!

**Comment by cwarnermm** [comment]
@amyblais - Can you confirm that calls transcriptions is a v9.4 feature?

**Comment by amyblais** [comment]
> @amyblais - Can you confirm that calls transcriptions is a v9.4 feature?

I'm not sure, @streamer45 @cpoile do you know?

**Comment by amyblais** [comment]
> @amyblais - Can you confirm that calls transcriptions is a v9.4 feature?

Actually yes, it is a v9.4 feature https://github.com/mattermost/mattermost-plugin-calls/pull/549.

**Comment by streamer45** [comment]
Yes, it's experimental behind a config flag (default off) but it will be there in 9.4 / Calls v0.22

**Pull request merged**
