### PR TITLE
Documentation site redux

### PR DESCRIPTION
**Pull request by neflyte**
#### Summary
This PR migrates the product docs site to a new Sphinx theme, [furo](https://pradyunsg.me/furo/), and upgrades Sphinx and its extensions to the latest releases.

Before building this branch for the first time, please make sure you have run `pipenv sync --dev` to update Sphinx and its dependencies.

**Development Note**: Currently building using Python 3.11; however, Mattermost pipelines use Python 3.9. Test all changes against Python 3.9 and Python 3.11 ahead of go-live. When go-live ready, bump pipelines to Python 3.11 to take advantage of incremental improvements.

### CODE REVIEW

**Comment by cwarnermm** [comment]
@asaadmahmood - I've reviewed the merge conflicts and would have resolved them all as "Accept Incoming Change" but I can't directly speak to the changes via ``mytheme.css`` and ``conf.py`` Can you take a look please?

**Comment by neflyte** [comment]
I've made a few modifications:  :smile: 

- Removed the `base.html` template in favour of `furo`'s built-in base template
- Use Sphinx's `html_baseurl` config option to specify the path of the doc set instead of specifying a PR ID as a custom parameter in the `reredirects` extension
- GitHub workflows were updated to use the correct `html_baseurl` value for preview environments
- Rewrote rST links into `doc` and `ref` inline directives to allow `html_baseurl` to work in more places
  - One-time migration script is included (`convert-links.py`)
  - Where possible, redirected pages were resolved into their final target links
  - Cleanup:
    - Some rST tables need spacing fixes
    - `ref` directives may have the incorrect section name and need to be updated
- Modified the `search.html` template to inherit from `page.html`; this brings the latest UI updates to the search page

FYI: The modifications to GitHub workflows won't take effect until this PR is merged. Previews created for this PR won't have redirects fixed.

**Comment by neflyte** [comment]
Note: I've observed that mid-page links (links with URL fragments) don't take the user to the correct part of the page if the announcement banner is showing. Dismissing the banner seems to allow mid-page links to work again.

**Comment by neflyte** [comment]
I've got the Edit in GitHub link working; it took a small change in `conf.py.`
I've also managed to extract the customizations from `page.html` into a small set of overrides to furo's `page.html` template. :smile: 

With regards to Markdown, we can use the `doc` and `ref` roles in a similar way to rST:
```markdown
{ref}`Extended Support Release <upgrade/release-definitions:Extended Support Release (ESR)>`
{doc}`Upgrading </upgrade/upgrading-mattermost-server>`
```

And we can use top-of-page directives like `:nosearch:` and `:orphan:` in a similar way to Hugo's document frontmatter:
```
---
nosearch: true
---
(markdown document starts here)
```

**Comment by neflyte** [comment]
I added Google Tag Manager support to `page.html` and left some test feedback; hopefully it's reflected in Looker. :) There were a couple nice places to insert the GTM scripts that align with furo!

**Pull request merged**
