### PR TITLE
[MM-33009] Set correct HTTP version for websocket upgrade on NGINX

### PR DESCRIPTION
**Pull request by streamer45**
#### Summary

We were failing to set the HTTP version to 1.1 for NGINX deployments. This started failing after the recent websocket revamp in https://github.com/mattermost/mattermost-server/pull/16620.

#### Ticket

https://mattermost.atlassian.net/browse/MM-33009

@amyblais We might also want to add an upgrade note for the release that will include the linked PR changes since some users/customers might be using the stock config as suggested and upgrading would most probably break websocket connections.

### CODE REVIEW

**Review by agnivade — APPROVED** [review]
Great catch!

**Review by amyblais — APPROVED** [review]

**Comment by amyblais** [comment]
Adding an upgrade note via https://github.com/mattermost/docs/pull/4355.

**Comment by agnivade** [comment]
I don't think there is any harm in merging this. The directive can stay for prior versions and there shouldn't be any issue.

**Comment by streamer45** [comment]
> I don't think there is any harm in merging this. The directive can stay for prior versions and there shouldn't be any issue.

Yes, it was wrong before as well just that the previous implementation was a bit more lenient.

**Pull request merged**
