### PR TITLE
DOC-7531: Join and leave channels page needs animated GIFs for mobile app workflows

### LINKED ISSUE #7531: Join and leave channels page needs animated GIFs for mobile app workflows
## Context

To help visual learners learn how to perform tasks using the Mattermost mobile app, add visuals and short animated GIFs on the [Join and leave channels](https://docs.mattermost.com/collaborate/join-leave-channels.html) page.

## Docs Request

- Add appropriate visuals/GIFs for all the steps in the `Join a channel` section under the mobile app tab.
- Add appropriate visuals/GIFs for all the steps in the `Leave a channel` section under the mobile app tab.

## Additional Notes

- Use the latest Mattermost mobile app and the standard Mattermost Denim theme to capture all workflows.
- Avoid drawing lines, arrows, boxes, or callouts on images.
- Don't forget to include ALT Text descriptions for all new image assets.
- Use existing docs pages with images as a starting point for code guidance. The Docs team can help provide RST syntax support for publication.
- Save static image files in PNG format within the docs repository's `/images` directory.

# QA Validation Criteria

In a generated docs preview:
- Visiting the docs page results in appropriate new mobile-specific screenshots in each subsection from the **Mobile** tab.

### PR DESCRIPTION
**Pull request by Rutam21**
### Summary

This PR adds visual workflows for the Mattermost mobile app tab on the [Join and leave channels](https://docs.mattermost.com/collaborate/join-leave-channels.html) page

### Ticket Link

Fixes #7531 

- [x] This PR follows Mattermost Contributing Guidelines.

### CODE REVIEW

**Comment by Rutam21** [comment]
@cwarnermm Please review and suggest changes, if any. Thanks.

@lindy65 Please add this to my queue for QA Testing once the reviews are complete. Thank you.

**Comment by lindy65** [comment]
Assigned to you for testing @Rutam21 - will still count towards Hacktoberfest as it was before end of day on 31 Oct

**Comment by Rutam21** [comment]
# The changes are tested in the preview environment and they reflect properly.

- The `Join and leave channels` page has now 6 new workflow images under the mobile tab for visual learners.

Please refer to the screenshots below as a confirmation.

## Current Docs Page [[Rename Channels](https://docs.mattermost.com/collaborate/rename-channels.html)]

### Join a channel Section

Screenshot 2024-11-01 141844

### Leave a channel section

Screenshot 2024-11-01 141859

## Preview Environment Page

### Join a channel Section

**Step 1**

Screenshot 2024-11-01 142048

**Step 2**

Screenshot 2024-11-01 142104

**Step 3**

Screenshot 2024-11-01 142120

### Leave a channel section

**Step 1**

Screenshot 2024-11-01 142321

**Step 2**

Screenshot 2024-11-01 142336

**Step 3**

Screenshot 2024-11-01 142350

**Step 4**

Screenshot 2024-11-01 142405

**[ Awaiting final review from @cwarnermm ]**

cc: @lindy65

**Comment by lindy65** [comment]
Thanks for testing @Rutam21 - counted towards Hacktoberfest

**Review by cwarnermm — APPROVED** [review]
Thank you, @Rutam21!

**Pull request merged**
