### PR TITLE
Update desktop.rst

### PR DESCRIPTION
**Pull request by Dartui**
#### Summary

Add escaped backslash to local storage path on Windows

### CODE REVIEW

**Comment by svelle** [comment]
Thanks for you contribution @Dartui !!

If you find the time could you sign the contributor CLA? Otherwise we can't merge this PR :)

**Comment by justinegeffen** [comment]
LGTM, thanks @Dartui! Once you've signed the CLA, we can merge this PR. :)

**Comment by justinegeffen** [comment]
Thanks, @Dartui, I re-checked the CLA and realized you've signed it. :)

**Pull request merged**
