### PR TITLE
Correct a unit conversion for the FileSettings.MaxFileSize config setting, make clear that IEC units are used

### PR DESCRIPTION
**Pull request by zsrv**
#### Summary

This PR corrects a unit conversion for the *FileSettings.MaxFileSize* configuration setting (104857600 bytes is 100 mebibytes), and uses IEC prefix names instead of SI prefix names to make clear how values entered in the System Console will be interpreted.

A code comment [here](https://github.com/mattermost/mattermost/blob/a40550136f45ebd1bde2be3b75ab6acf7eaa8a92/server/public/model/config.go#L1613) indicates that IEC units should be used.

#### Ticket Link

None

### CODE REVIEW

**Comment by harshilsharma63** [comment]
@zsrv are you open to fixing the remaining instances of SI units as well?

**Comment by zsrv** [comment]
@harshilsharma63 sure, I'll work on it this weekend.

**Comment by zsrv** [comment]
@harshilsharma63 I've added an additional commit that makes the clarification for the MS Teams plugin, but there are two parts that I think I'll need someone with access to the Mattermost Enterprise code to verify:

https://github.com/mattermost/docs/blob/8c24d2e2e0c5ee6f192dd1b5e2f5335849466a54/source/configure/experimental-configuration-settings.rst?plain=1#L855
https://github.com/mattermost/docs/blob/8c24d2e2e0c5ee6f192dd1b5e2f5335849466a54/source/manage/logging.rst?plain=1#L395

I couldn't find usages of these config options in the open source code base, so as these are related to enterprise-only features I assume they are only used in the enterprise code base.

**Review by harshilsharma63 — APPROVED** [review]
LGTM!

**Review by cwarnermm — APPROVED** [review]
Thank you so much for this docs PR, @zsrv! Much appreciated!

**Pull request merged**
