### PR TITLE
Use $host instead of $http_host

### PR DESCRIPTION
**Pull request by Glandos**
See https://trac.nginx.org/nginx/ticket/2468#comment:1

#### Summary

Fix example configuration.

### CODE REVIEW

**Review by agnivade — APPROVED** [review]
Thanks!

**Review by cwarnermm — APPROVED** [review]
Thank you, @Glandos!!

**Comment by cwarnermm** [comment]
@Glandos - Are you open to signing the Mattermost CLA? This step is necessary to merge your PR changes into the documentation code base. Thanks!

**Comment by Glandos** [comment]
> @Glandos - Are you open to signing the Mattermost CLA? This step is necessary to merge your PR changes into the documentation code base. Thanks!

Yes, but it seems to be a bit excessive to me to sign a CLA for a changed variable name in an example configuration file :)

**Pull request merged**
