### PR TITLE
Fix slack-advanced-exporter order of operations

### PR DESCRIPTION
**Pull request by Mercbot7**
We found that the repo: https://github.com/grundleborg/slack-advanced-exporter has the proper order of operations for exporting slack resources. When we ran with the current order we received an error about a bad zip file for the last step for the slack-advanced-exporter.

### CODE REVIEW

**Comment by icelander** [comment]
LGTM! 👍

**Review by icelander — APPROVED** [review]

**Review by cwarnermm — APPROVED** [review]
Thank you!

**Comment by cwarnermm** [comment]
@Mercbot7 - Are you open to signing the Mattermost CLA?

**Comment by Mercbot7** [comment]
Sorry, I was out for the Christmas break. CLA is good and submitted.

**Pull request merged**
