### PR TITLE
Fix broken links to legacy changelogs

### PR DESCRIPTION
**Pull request by cwarnermm**
Fixes https://github.com/mattermost/docs/issues/5958

### CODE REVIEW

**Comment by cwarnermm** [comment]
Links to legacy changelogs need to be updated from 
- ``self-managed-changelog.html#release-vx-y-feature-release`` OR 
- ``/administration/changelog.html#release-vx-y`` 

to ``legacy-self-hosted-changelog.html#release-vx-y``

**Comment by amyblais** [comment]
Thank you for getting this started, I took a stab at fixing the remaining links but the preview environment shows a blank screen if I try click on the updated links.

**Comment by cwarnermm** [comment]
Yes, I'm seeing the same, @amyblais. That's what motivated me to try merging a single link fix into production to confirm that the fix would work. 

Based on what I saw, I suspect that our preview environment doesn't resolve relative docs links correctly. However, in production, relative links resolve as expected.

**Comment by cwarnermm** [comment]
@amyblais - Please let me know if you'd like me to finish updating legacy changelog links that aren't currently working. Happy to do so!

**Review by amyblais — APPROVED** [review]
I believe I was able to fix all the broken links, though currently they can't be verified in preview.

**Comment by cwarnermm** [comment]
@amyblais When you're ready to merge, I'm happy to review the links in production to ensure they resolve correctly.

**Comment by cwarnermm** [comment]
@amyblais All link fixes now work as expected with the following exceptions:
- v5.31
- v5.30
- v4.9.4
- v5.0.3
- all v4.x links

I can help with these investigations & fixes.

**Comment by amyblais** [comment]
Thank you for reviewing, I'd say it's low priority to fix these.

**Pull request merged**
