### PR TITLE
Update search metadata

### PR DESCRIPTION
**Pull request by matthew-src**
#### Summary

This PR updates the search metadata for Integrations and Compliance settings to include the `config.json` file keys and Environment variables. I would like to flag the settings on the Compliance page for review, as those settings are located in several different objects in the `config.json` file, and especially the settings related to `BatchSize`, as there are multiple settings with that name.

### CODE REVIEW

**Comment by cwarnermm** [comment]
@wiggin77 - Can we get your help to review the Compliance config setting updates proposed in this PR, please?

**Review by wiggin77 — APPROVED** [review]
LGTM :+1:

**Review by cwarnermm — APPROVED** [review]

**Comment by cwarnermm** [comment]
Thanks, @matthew-src! So great to have these gaps filled in! Would the next step beyond this PR include migrating from the current format to the table-based format?

**Comment by matthew-src** [comment]
Hi @cwarnermm, yes that is a logic next step for these pages.

**Pull request merged**
