### PR TITLE
Update devops-command-center.rst

### PR DESCRIPTION
**Pull request by amyblais**
Editor review

### CODE REVIEW

**Comment by amyblais** [comment]
Question: Should https://github.com/mattermost/docs/blob/19d45d0826d3026b3e37961822e9469f91cba2bc/source/administration/devops-command-center.rst#telemetry be added to https://docs.mattermost.com/administration/telemetry.html?

**Comment by itao** [comment]
No, the beta telemetry should not be added to the main docs. It is temporarily given to select customers, and will likely be completely rethought as we prepare for Cloud first.

**Comment by itao** [comment]
Thanks for the improvements, @amyblais. No, the beta telemetry should not be added to the main docs. It is temporarily given to select customers, and will likely be completely rethought as we prepare for Cloud first.

**Comment by justinegeffen** [comment]
Thanks so much, @amyblais, much appreciated! :)

**Pull request merged**
