### PR TITLE
Rename source/process/help-wanted.rst to source/archive/help-wanted.rst

### PR DESCRIPTION
**Pull request by justinegeffen**
Testing moving articles to archive and how it affects the redirects.

### CODE REVIEW

**Comment by justinegeffen** [comment]
@cwarnermm, the remaining content in the Process directory will be migrated to the handbook asap.

**Review by cwarnermm — APPROVED** [review]
This is great! Thank you!

**Comment by justinegeffen** [comment]
@cwarnermm, I'll get back to this PR today or tomorrow once I've gone through all the changes that have caused conflicts. It looks like the same renaming issue as we've had previously.

**Comment by cwarnermm** [comment]
This is cleanup work that can happen later if needed. I can also help with the conflicts.

**Comment by justinegeffen** [comment]
Closing in favor of redoing this due to huge merge conflict issues.

**Pull request closed without merging**
