### PR TITLE
IS-7067: Keyboard Accessibility Screenshot doesn't represent user's product experience

### LINKED ISSUE #7067: Help Wanted: Screenshot doesn't represent user's product experience
# Issue
The first screenshot in [Keyboard accessibility - Mattermost documentation](https://docs.mattermost.com/collaborate/keyboard-accessibility.html) is missing the blue focus outline indicating that the area is selected/active). The screenshot is also outdated and missing a number of product enhancements.

## Current
image

## Expected

image

# How to Contribute
- Re-capture the UI, with accessibility shortcuts enabled and blue outline visible.
- Any public channel on the [Mattermost Community Server](https://community.mattermost.com) can be captured with an empty text box (no message draft).
- Capture using a browser or the desktop app displaying the **Mattermost Denim Theme**.

### PR DESCRIPTION
**Pull request by Rutam21**
## Summary

The current screenshot that is available at the top of the https://docs.mattermost.com/collaborate/keyboard-accessibility.html page is outdated and doesn't represent the user's current product experience. This PR replaces the outdated image with the current product experience image.

## Ticket Link

This PR fixes #7067 

## Checklist

- [x] This PR follows the Mattermost Contributing Guidelines.
- [x] The screenshot has been taken on the Mattermost Desktop App that uses the Denim theme.

### CODE REVIEW

**Comment by Rutam21** [comment]
@cwarnermm Please review and suggest changes, if any. Thanks.

**Comment by cwarnermm** [comment]
Thanks, @Rutam21. Can the image background be white, rather than grey, using the Denim Theme, to improve image contrast, please?

**Comment by Rutam21** [comment]
@cwarnermm Please check and confirm if the current image is okay.

**Review by cwarnermm — APPROVED** [review]
Thanks, @Rutam21!

**Pull request merged**
