### PR TITLE
Update important upgrade notes

### PR DESCRIPTION
**Pull request by amyblais**
Add note about MS Teams Calls plugin update. I'll also add it to the v7.0 changelog PR draft.

To merge when https://github.com/mattermost/mattermost-plugin-msteams-meetings/pull/63 is released.

### CODE REVIEW

**Review by srkgupta — APPROVED** [review]
Thanks @amyblais. LGTM

**Comment by amyblais** [comment]
@DHaussermann Do you know if this is good to be merged? (Has https://github.com/mattermost/mattermost-plugin-msteams-meetings/pull/63 been released?)

**Comment by amyblais** [comment]
@DHaussermann I've updated it to v2.0.0 now!

**Review by DHaussermann — APPROVED** [review]
Perfect Thanks @amyblais!

Sorry for the confusion. 
And yes, in answer to the second part of the question, the PR has been merged. The release was cut and was pushed to the marketplace just about an hour ago so the version is now available :)

**Pull request merged**
