### PR TITLE
Fix formatting issue

### PR DESCRIPTION
**Pull request by amyblais**
This PR attempts to fix the formatting issue reported at https://community.mattermost.com/core/pl/17hoqoz543fhmbrdx1ewiu9hic. I'm unsure if there was any better way to fix the formatting.

### CODE REVIEW

**Comment by cwarnermm** [comment]
@amyblais - I'd like to apply a bit more formatting & simplification to the text to make it easier to scan. Any concerns with me committing updates to your branch?

**Comment by amyblais** [comment]
> @amyblais - I'd like to apply a bit more formatting & simplification to the text to make it easier to scan. Any concerns with me committing updates to your branch?

@cwarnermm Feel free 👍

**Comment by cwarnermm** [comment]
@amyblais - I've applied additional formatting to the v7.2 schema information, and streamlined the content by:
- removing [bigdb]
- removing hash symbols
- removing extraneous CLI output that doesn't add value

How does the new preview read to you?

**Comment by amyblais** [comment]
@cwarnermm Thank you, it looks great!

**Review by agnivade — APPROVED** [review]

**Pull request merged**
