### PR TITLE
Disable "View page source".

### PR DESCRIPTION
**Pull request by ajerezr**

### CODE REVIEW

**Comment by it33** [comment]
Thanks @ajerezr! Much appreciated, 

Could you help take a look at how we might be able to replace the View Source link with an Edit link, connected to the underlying GitHub pages for each file?

**Comment by ajerezr** [comment]
Ok @it33, I will take a look, but I don't promise anything :)

**Comment by it33** [comment]
Thanks! A few people tried this before and couldn't solve the puzzle, but we know many other Sphinx sites do this, so solutions do exist. If you're able to figure it out it would help a lot.

**Comment by it33** [comment]
Hi @ajerezr, our goal was switching the "View page source" link to an "Edit Page" link to the GitHub page where users could edit the source. 

While removing "View page source" is an intermediate step we couldn't take this without the "Edit Page" part. 

Please let me know if you'd still like to try to add that part?

**Comment by ajerezr** [comment]
Hi @it33 , now im in other projects so i cant view how change "edit page" part.
Anyway, i take a look around to if i view something, i write you.

Sorry for the inconvenience,

**Comment by esethna** [comment]
Thanks again for the PR, closing it for now. Feel free to resubmit if you are able to look into adding the "Edit Page" functionality.

**Pull request closed without merging**
