### PR TITLE
WIP: Update to company goals and recruiting process 

### PR DESCRIPTION
**Pull request by lindy65**
Recreating recruitment doc in RST

### CODE REVIEW

**Comment by lfbrock** [comment]
Made a few small edits, I think it looks good. 

My one question is if we should do an rst include for values, since it's in both this doc and this one: https://docs.mattermost.com/process/handbook.html

And I think our mission is different in both places, not sure if we want it to be consistent?

**Comment by lfbrock** [comment]
@lindy65 - I think this needs: 

1. Add recruitment.rst to Table of Contents
2. Samiksha and Seiji to address Ian's comment 

Then I think it's ready to go

**Comment by it33** [comment]
I need to take a deeper pass at this, the engineer vs. non-engineer needs work.

**Comment by amyblais** [comment]
@lindy65 What is the status of this PR and do you need any help here to finish this?

**Comment by lindy65** [comment]
@amyblais - thanks for following up :)  

We're waiting for IJT's thumbs up as he wanted to review more thoroughly and processes were changing rapidly at the time the PR was created...

**Comment by it33** [comment]
Hi, sorry, propose we close this as its out-of-date, also we're planning to move handbook out of docs

**Pull request closed without merging**
