### PR TITLE
Light Performance Adjustments for Page Speed Opportunities

### PR DESCRIPTION
**Pull request by lawrencejohnson**
#### Summary
Performance adjustments were made to improve Page Speed scores. See below for specifics:

- Localized Mattermost Logo
- Moved script references below header markup
- Preloaded fonts
- Combined Pgyment css into theme CSS to reduce HTTP requests
- Made some light indentation adjustments to scripts section for readability

#### Ticket Link
https://mattermost.atlassian.net/browse/MAR-259

### CODE REVIEW

**Comment by justinegeffen** [comment]
Thanks, @lawrencejohnson! I see some changes have been made to the themes/templates so Carrie and I would like to take some time to build and test this locally, as I don't think the preview server spins up for forked PRs. What sort of changes should we be looking for?

**Comment by lawrencejohnson** [comment]
Hi Justine - no visual changes; from a functionality standpoint the only thing that I could think might be affected would be the Search, but I tested it locally and seemed to be working fine.

**Review by cwarnermm — APPROVED** [review]
Approving. Not able to contribute a technical review of this update.

**Comment by justinegeffen** [comment]
@asaadmahmood, would you be open to reviewing this and letting us know whether it all looks good? I'm not sure I know enough about CSS/themes to know what to look for. Thank you!

**Review by asaadmahmood — APPROVED** [review]
LGTM

**Review by justinegeffen — APPROVED** [review]

**Pull request merged**
