### PR TITLE
updated User management configuration settings

### PR DESCRIPTION
**Pull request by ayrotideysarkar**
I have added the instructions about how to manage users action as an admin

### CODE REVIEW

**Comment by justinegeffen** [comment]
Thank you for this PR, @ayrotideysarkar! Would you be open to providing some context for the change?

**Comment by cwarnermm** [comment]
@justinegeffen - @ayrotideysarkar is developing user management documentation for system admins.

**Comment by cwarnermm** [comment]
Thanks, @ayrotideysarkar. This draft is a good start. From here, you'll detail the specific steps an admin needs to take in the System Console to perform specific user administrative actions outlined in the framework you can use below:

```
Introductory text 
-----------------

- what's this section in the docs about?

Find users
~~~~~~~~~~

- admins also can narrow down search results by filtering by team or user status

1.
2.
3.

Active or deactivate users
~~~~~~~~~~~~~~~~~~~~~~~~~~

1. 
2.
3.

Manage user roles
~~~~~~~~~~~~~~~~~~

1.
2.
3.

Update team membership
~~~~~~~~~~~~~~~~~~~~~~

1.
2.
3.

Reset user's password
~~~~~~~~~~~~~~~~~~~~~

1.
2.
3.

Update user's email
~~~~~~~~~~~~~~~~~~~~

1.
2.
3.

Revoke user sessions
~~~~~~~~~~~~~~~~~~~~~

1.
2.
3.
```

**Comment by ayrotideysarkar** [comment]
@cwarnermm  okay I will follow this format from now on 🙂

**Pull request closed without merging**
