### PR TITLE
Cursor pointer added

### PR DESCRIPTION
**Pull request by Mustafa-Azad025**
#5913 I Have Added Cursor pointer in all buttons and link and also copy button 
please merge in your repo.

### CODE REVIEW

**Comment by justinegeffen** [comment]
Thanks, @Mustafa-Azad025! This is great work. Once you've signed the CLA we can move forward with the review. :)

**Comment by neflyte** [comment]
The only issue I see is there is a pointer that appears over the text in the feedback widget; the pointer should not be there since it's not a link. Only the emoji icons and the text under them should show the pointer.

**Comment by cwarnermm** [comment]
@neflyte - Are you open to technically reviewing this PR?

**Comment by cwarnermm** [comment]
@Mustafa-Azad025 - Please see @neflyte's feedback.

**Pull request closed without merging**
