### PR TITLE
feature/7053-fix-search-special-chars 

### LINKED ISSUE #7053: Help Wanted: Entering special characters as search criteria returns "Preparing Search..."
When performing a search using the search field, passing special characters, such as (~, +, -, :, ^) as search criteria returns a stuck screen displaying Preparing Search with no results.
image

Ideally, the search should return "Your search did not match any documents. Please make sure that all words are spelled correctly." as it occurs with other symbols such as !, @, #, etc. when no relevant match is found.
image

# QA Validation Criteria

In a generated docs preview:
- Performing docs searches that contain _only_ 1 or more special characters (and no text-based criteria) returns a standard **Search Results** page message: "Your search did not match any documents. Please make sure that all words are spelled correctly."

### PR DESCRIPTION
**Pull request by TomerPacific**
#### Summary
This pull request includes an update to the `SearchClass` in `source/_static/js/mattermost-search.js` to improve error handling during the search process.

 Wrapped the `lunr` search call in a `try-catch` block to handle potential errors, log an error message, set the post-search status to 0, and return early if an error occurs.

I have tested this fix with the following special characters in the search field: `~, +, -, :, ^`

#### Ticket Link
Resolves #7053

### CODE REVIEW

**Comment by cwarnermm** [comment]
Thanks, @TomerPacific!! When I search on other special characters, such as ``(, ), <, >``, etc., I noticed that both a title **Search Results** and text is returned.

But when I search for the targeted special characters including: ``~, +, -, :, ^``, the **Search Results** title is omitted. Can you please add the title to these specific searched characters, please, for consistency?

**Comment by TomerPacific** [comment]
@cwarnermm - Consider it done.

**Review by cwarnermm — APPROVED** [review]
Thank you so much for your help with this, @TomerPacific!!

**Comment by Rutam21** [comment]
@lindy65 Please assign this to me for QA Testing. Thanks.

**Comment by Rutam21** [comment]
### The changes in this PR have been tested in the preview environment and work as expected.

Here is a summary of the observed outcomes in the preview environment for this PR.

- Only Special Character search in the Docs site returns a Title `Search Results` and the preferred message mentioned in the ticket.
- Searching with a single special character returns the expected result.
- Searching with multiple special characters also returns the expected result.
- A single special character search for all the special characters available on a keyboard has been done and tested.

I've attached a video as a confirmation below.

https://github.com/user-attachments/assets/71409074-0d99-4959-b05c-feb99a2cbb89

cc: @lindy65

**Comment by lindy65** [comment]
Thank you for testing @Rutam21 - counted towards Hacktoberfest!

cc @cwarnermm

**Pull request merged**
