### PR TITLE
WIP: Move help wanted ticket page to new handbook

### PR DESCRIPTION
**Pull request by jasonblais**
Before merging, need
1. https://github.com/mattermost/mattermost-handbook/pull/214 merged
2. update various references to this page -- including https://developers.mattermost.com/contribute/getting-started/

### CODE REVIEW

**Comment by justinegeffen** [comment]
Confirming that https://github.com/mattermost/mattermost-handbook/pull/214 has been merged (just for reference).

**Comment by jasonblais** [comment]
Outstanding docs/pages that need to be fixed:

1. Support resources in Zendesk
2. Job postings referencing help wanted issue process (at least engineering postings)
3. docs.gitlab.com/omnibus/gitlab-mattermost/
4. AmyB and others who use the [standard response for feature requests](https://docs.mattermost.com/process/community-guidelines.html#feature-requests) and which references the old help wanted issue page

**Comment by justinegeffen** [comment]
Two outstanding issues:
1. No references to this content were found on docs.gitlab.com/omnibus/gitlab-mattermost/
2. No references to this page were found on https://developers.mattermost.com/contribute/getting-started/

This PR includes a note pointing at the new URL, so I think it's good to go, @jasonblais?

**Comment by jasonblais** [comment]
@justinegeffen Looks like this is then good to go. I checked and job postings no longer reference the help wanted issue page.

**Pull request merged**
