### PR TITLE
Rename Architect to Principal SDE.

### PR DESCRIPTION
**Pull request by grundleborg**

### CODE REVIEW

**Comment by coreyhulen** [comment]
Hmm, I thought we decided Architect/Principal SDE?

**Comment by grundleborg** [comment]
Ah OK, I can change it.

**Comment by grundleborg** [comment]
@coreyhulen fixed

**Comment by coreyhulen** [comment]
Looks like you might need to re-submit to get past he build errors.

**Comment by coreyhulen** [comment]
otherwise looks good

**Comment by hanzei** [comment]
@coreyhulen Feel free to merge

**Pull request merged**
