### PR TITLE
Update ESR info in version-archive.rst

### PR DESCRIPTION
**Pull request by torgeirl**
marked 5.9 as ESR as explained in #2665; added abbreviation

### CODE REVIEW

**Comment by amyblais** [comment]
@torgeirl,

Thank you, maybe add an "upcoming" for this too? Also, the Team Edition section should be updated.

**Comment by torgeirl** [comment]
> Also, the Team Edition section should be updated.
I left it out since only the Enterprise edition currently is marked as ESR. Looks like both gets extended support, but I assumed the Team Edition wasn't marked as ESR for a reason.

**Comment by torgeirl** [comment]
> Also, the Team Edition section should be updated.

@amyblais: I left it out since only the Enterprise edition currently is marked as ESR. Looks like both gets extended support, but I assumed the Team Edition wasn't marked as ESR for a reason.

**Comment by amyblais** [comment]
@torgeirl, no worries, they both get extended support so you can update the TE section as well.

**Comment by torgeirl** [comment]
@amyblais: made the same changes to 4.10 and 5.9 Team Edition now.

**Comment by amyblais** [comment]
Thank you!

**Pull request merged**
