### PR TITLE
Update mmctl-command-line-tool.rst

### PR DESCRIPTION
**Pull request by nadeem-hassan**
#### Summary
This pull request adds documentation for **--since** flag for **mmctl** post list command added. The PR for code update is [here](https://github.com/mattermost/mmctl/pull/521)

#### Ticket Link
https://github.com/mattermost/mattermost-server/issues/20216

### CODE REVIEW

**Comment by isacikgoz** [comment]
@cwarnermm Yes after the mmctl gets updated/released we can merge this one.

**Review by mgdelacroix — APPROVED** [review]
LGTM! :+1: Thanks @nadeem-hassan!

**Review by cwarnermm — APPROVED** [review]
Thanks, @nadeem-hassan!

**Comment by justinegeffen** [comment]
@isacikgoz, are we good to merge this?

**Comment by isacikgoz** [comment]
@justinegeffen good to merge after https://github.com/mattermost/mmctl/pull/521 👍

**Pull request merged**
