### PR TITLE
Reduce redundant config in config-proxy-nginx.rst

### PR DESCRIPTION
**Pull request by J0WI**
I also removed the empty `Connection` header completely.

### CODE REVIEW

**Comment by J0WI** [comment]
Not sure why the diff has be messed up. Didn't you specify an eol style?

**Comment by J0WI** [comment]
I provide this patch under the public domain license, but I refuse to sign your contribution license agreement.
There is no need to ask for
- Name
- Email
- Phone number or Skype ID
- Mailing Address

and I have privacy doubts to provide this data to you and the third party service Wufoo/SurveyMonkey.

**Comment by lindy65** [comment]
Hi @J0WI,

Thank you so much for the PR :)

While we understand your reservation in giving out your personal details, the reason we ask for them is because we like to send each contributor to Mattermost a #mattermug for which we need a name, shipping address and telephone number for the courier.  The information is captured on an internal spreadsheet viewable by Mattermost staff only.

We really would appreciate your reconsidering completing the CLA so we can review your PR, which we highly appreciate, as well as send you a #mattermug :)

**Comment by J0WI** [comment]
I'm not sure how you send a mattermug through Skype or phones ;)
However, I won't sign your CLA under these circumstances. Feel free to use this patch anyway.

**Comment by lindy65** [comment]
Thanks for the feedback @J0WI,

Of course we don't send the #mattermug via Skype  :) but the telephone number is often required by the courier.

I'm not able to make decisions regarding your PR and will defer to one of our product managers.

**Comment by lindy65** [comment]
Hi @J0WI,

We appreciate your contribution very much - so thank you once again for the pull request.

As per our [Contribution Guide](https://docs.mattermost.com/developer/contribution-guide.html#preparing-a-pull-request) we are not able to accept pull requests where contributors have not signed the CLA so I'll close off this PR for now.  We'd be thrilled if you decide to sign the CLA so we can accept your PR but, should you choose not to, we totally understand.

Thank you again for your interest in improving Mattermost!

**Comment by J0WI** [comment]
This CLA is very strict for a documentation only repo.
I've created #1780. Hopefully someone else picks this up.

**Pull request closed without merging**
