### PR TITLE
Remove unneeded steps

### PR DESCRIPTION
**Pull request by cdmwebs**
#### Summary

It appears that the mmetl job now outputs the data in the correct subfolder, making this step unnecssary.

### CODE REVIEW

**Comment by cdmwebs** [comment]
FWIW I don't need credit for this, so if someone with contributor access wants to fix instead, that's fine. Just thought I'd point it out!

**Comment by cwarnermm** [comment]
@cdmwebs - Signing the CLA is a required step in our PR process. Is this something you're open to doing (despite not needing the credit)? If not, no worries. I can ensure your update is applied in a separate PR if you'd rather not.

**Comment by cdmwebs** [comment]
@cwarnermm a separate PR is perfect. Thank you!

**Comment by cwarnermm** [comment]
Looks like GitHub will allow me to bypass requirements and merge this PR, so no need for a second docs PR. Thanks again, @cdmwebs!

**Comment by cdmwebs** [comment]
Hooray! Glad to help.

**Pull request merged**
