### PR TITLE
Docs updated

### PR DESCRIPTION
**Pull request by trishitapingolia**
Commas updated according to the mattermot style format.

### CODE REVIEW

**Comment by justinegeffen** [comment]
Hi @trishitapingolia! Thank you for your PR. We do use Oxford (serial) commas in our documentation so this change would unfortunately not be applicable. Would you be open to sharing the link to the style format mentioned? I'd like to confirm that our guidelines reflect that accurately. Thank you! :)

**Comment by trishitapingolia** [comment]
@justinegeffen sure, 
https://handbook.mattermost.com/operations/operations/company-processes/publishing/publishing-guidelines/voice-tone-and-writing-style-guidelines/documentation-style-guide

**Comment by justinegeffen** [comment]
Thank you, @trishitapingolia! As per our style guide, we do use the Oxford comma in our documentation. This PR is a change that removes the Oxford commas from the content, which unfortunately does not fit our style. Although this change is not one we can accept at this time, I encourage you to take a look through our open issues for other ways to contribute. Thank you again for your contribution! :)

**Pull request closed without merging**
