### PR TITLE
Added YouTube video re: CloudNative Bootstrapper

### PR DESCRIPTION
**Pull request by cwarnermm**

### CODE REVIEW

**Comment by cwarnermm** [comment]
@nickmisasi - I added your most excellent CloudNative Bootstrapper YouTube video to the Deploy Kubernetes product documentation page. Is it positioned on the page well, or would you recommend it be available elsewhere on the page? (I'm not sure where it fits into the deploy process.) Thanks!

**Comment by nickmisasi** [comment]
@cwarnermm this looks like the right spot for now. FWIW - we're still fairly early stages with the tool - do we have a "Coming Soon" badge of some sort we could apply?

**Comment by cwarnermm** [comment]
We certainly can label it as coming soon in the product docs. If docs visitors have feedback, is there a good channel they could join to share that feedback with us? Happy to add that too.

**Comment by nickmisasi** [comment]
@cwarnermm no existing channels or anything I can share at this time. I can work on getting one requested for Community, but for now I think it's best to just mark this with coming soon, or even "Sneak peek"

**Comment by cwarnermm** [comment]
@nickmisasi - I've added the "sneak peek" label to this new docs section. This PR is ready for your approval.

**Review by nickmisasi — APPROVED** [review]
LGTM. Thanks @cwarnermm!

**Pull request merged**
