### PR TITLE
WIP Change doc for MM 6+

### PR DESCRIPTION
**Pull request by pichouk**
Mattermost Docker images will changed with Mattermost `6+` (see https://github.com/mattermost/mattermost-docker/pull/366). This PR aims to update the documentation accordingly and collect reviews.

### CODE REVIEW

**Comment by justinegeffen** [comment]
Hi @pichouk! I've taken a look through this PR and the related one and wanted to find out whether you'd like to start the review process for the doc update? Let me know if I can assist with anything. :)

**Comment by justinegeffen** [comment]
Hi @pichouk. I wanted to follow up on this again and find out if you'd like to move forward with this PR and how we can assist. :)

**Comment by pichouk** [comment]
Hi :wave: 
I think this PR is not up to date anymore, since the way to deploy Mattermost using Docker changed since I opened it. I think the best solution should be to get in touch why the current maintainer of Mattermost Docker image.
(And sorry, it seems I didn't answered the first time you ping me...)

**Comment by justinegeffen** [comment]
Thanks for confirming, @pichouk! I'll sync up with the Docker maintainer/s. :)

**Pull request closed without merging**
