### PR TITLE
New Slash Commands table.

### PR DESCRIPTION
**Pull request by yangchen1**
Updated to include new slash commands.

### CODE REVIEW

**Comment by esethna** [comment]
Thanks Yang, can you please combine the commits to delete the table and add the new one into one pull request? ie make the changes on the same branch?

**Comment by jasonblais** [comment]
Actually, I think it'll override the image, so https://github.com/mattermost/docs/pull/433/ is not needed.

I'm not sure where/how the image is generated, but it would be nice if the shortcuts were in alphabetical order. 

Also, `/shortcuts` is missing from the list.

**Comment by lfbrock** [comment]
Sorry @jason I don't think alphabetical order makes sense, because it would make sense to group some like online/offline/away together, and collapse/expand

**Comment by esethna** [comment]
@yangchen1 @jasonblais, looks like this PR is not replacing the table but adding a new one since the extension is not capitalized. @yangchen1 can you please tweak this branch to delete the old table and add the new one with corrected capitalization.

image

**Comment by esethna** [comment]
+1

**Comment by lfbrock** [comment]
+1

**Pull request merged**
