### PR TITLE
Update notices.rst

### PR DESCRIPTION
**Pull request by justinegeffen**
Changed "notifications" to "notices" to match existing content. Minor rewording of AA content for ease of reading.

### CODE REVIEW

**Review by amyblais — APPROVED** [review]

**Comment by esethna** [comment]
@justinegeffen @cwarnermm I didn't realize we added the admin advisor docs into this page as well (that was originally written for in-product notices). If we are consolidating the in-product notices docs and the admin advisor docs here, then we really need to include screenshots and improve the hierarchy of this page. For example:

1. Without the tribal knowledge of what in-product notices are and what admin advisor is, this page is very hard to understand now. Images may help
2. The FAQs I wrote were for in-product notices (not admin advisor), but now they are at the same hierarchy as the rest of the headings 

_________

Resources that may help in resolving this: 

End user in-product notice image example:
image

Admin in-product notice example:
image

Admin Advisor example:
Please ask @jasonblais

**Comment by justinegeffen** [comment]
Thanks, @esethna. Those are very good points. I'm 4/5 for keeping this content in this page and will update this PR with the provided images tomorrow, thanks. :)

**Comment by jasonblais** [comment]
@justinegeffen [you can get a screenshot of the admin advisors here](https://www.figma.com/proto/wSbd7TWq5A05Zq5GOnmrbI/Admin-Advisory?node-id=58%3A1021&viewport=-1559%2C72%2C0.5&scaling=min-zoom).

**Comment by justinegeffen** [comment]
Apologies for the delay on this. I'll be addressing it today.

**Comment by esethna** [comment]
Thanks @justinegeffen, see (2) and (3) from my comment above, I think we need more updates to hierarchy in this doc

**Comment by justinegeffen** [comment]
Ah, thanks @esethna, totally skipped those. I'll sort that out.

**Comment by justinegeffen** [comment]
@esethna, I've rearranged the content as suggested. I moved the FAQ to a point between the in-product notices and admin advisor notices sections as the FAQs related only to the in-product notices. If we do add admin advisor FAQs I'll fold those into that section and then move it to the bottom of the page.

**Review by esethna — APPROVED** [review]

**Pull request merged**
