### PR TITLE
Fix mentions of `mmctl config reload`

### PR DESCRIPTION
**Pull request by elyscape**
#### Summary
The release and upgrade notes for 5.38.0 mention that the config watcher has been removed, and that in its place a command has to be run to notify the server that the configuration has changed. This change includes the actual command that has to be run.

#### Ticket Link
N/A

### CODE REVIEW

**Comment by amyblais** [comment]
@elyscape Would you be open to updating the same text at https://docs.mattermost.com/upgrade/important-upgrade-notes.html? I can also push the update if it's easier!

**Comment by elyscape** [comment]
Sure. I'll make it happen shortly.

**Comment by elyscape** [comment]
Updated!

**Review by amyblais — APPROVED** [review]
Thank you!

**Pull request merged**
