### PR TITLE
DOC-7536: Browse channels page needs animated GIFs for mobile app workflows

### LINKED ISSUE #7536: Browse channels page needs animated GIFs for mobile app workflows
## Context

To help visual learners learn how to perform tasks using the Mattermost mobile app, add visuals and short animated GIFs on the [Browse channels](https://docs.mattermost.com/collaborate/browse-channels.html) page.

## Docs Request

- Add appropriate visuals/GIFs for all the steps in the `Browse Channels` section under the mobile app tab.

## Additional Notes

- Use the latest Mattermost mobile app and the standard Mattermost Denim theme to capture all workflows.
- Avoid drawing lines, arrows, boxes, or callouts on images.
- Don't forget to include ALT Text descriptions for all new image assets.
- Use existing docs pages with images as a starting point for code guidance. The Docs team can help provide RST syntax support for publication.
- Save static image files in PNG format within the docs repository's `/images` directory.

# QA Validation Criteria

In a generated docs preview:
- Visiting the docs page results in appropriate new mobile-specific screenshots in each subsection from the **Mobile** tab.

### PR DESCRIPTION
**Pull request by Rutam21**
### Summary

This PR adds visual workflows for the Mattermost mobile app tab on the [Browse channels](https://docs.mattermost.com/collaborate/browse-channels.html) page.

### Ticket Link

Fixes #7536 

- [x] This PR follows Mattermost Contributing Guidelines.
- [x] The changes are tested in a local docs build.

### CODE REVIEW

**Comment by Rutam21** [comment]
@cwarnermm Please review and suggest changes, if any. Thanks.

@lindy65 Please add this to my queue for QA Testing once the reviews are complete. Thank you.

**Comment by lindy65** [comment]
Assigned to you for testing @Rutam21 :)

**Comment by Rutam21** [comment]
## The changes are tested in the preview environment and reflect properly.

- The `Browse channels` page now has respective workflow images under the mobile tab for visual learners.

Please refer to the screenshots below as a confirmation.

## Current Docs Page [[Browse channels](https://docs.mattermost.com/collaborate/browse-channels.html)]

Screenshot 2024-11-04 155711

## Preview Environment Page Video

https://github.com/user-attachments/assets/397a5e97-2071-4e3a-8940-a3fbb9100148


**[ Awaiting final review from @cwarnermm ]**

cc: @lindy65

**Comment by lindy65** [comment]
Thanks so much for testing @Rutam21 :)

**Review by cwarnermm — APPROVED** [review]
Thanks, @Rutam21!

**Pull request merged**
