### PR TITLE
Add Migrating Mattermost server from MySQL to PostgreSQL

### PR DESCRIPTION
**Pull request by biva**
Add a section to help people migrate from MariaDB to PostgreSQL, following https://github.com/mattermost/mattermost-server/issues/18351

### CODE REVIEW

**Comment by biva** [comment]
Hello, I'm still working on the file, I'll keep you updated when I'll be ready. Sorry if it's not the right process, I thought doing a draft pull request would leave me time to work on it without bothering you :/

**Comment by biva** [comment]
There are a lot of stuff that I'm not sure of, but notably: 
1. Formatting: I might have not respected all conventions, I'm not sure
2. Step 3: Migrate to the latest version: I understood that servers with MariaDB might have issues with the latest versions of Mattermost (for example version 7). Is it a risk? Should we keep this step?

**Comment by biva** [comment]
Hello @cwarnermm , thanks for your message. I understand that it's not possible for Mattermost to include MariaDB in the documentation because it was never officially supported. That definitely makes sense. I renamed it "Migration from MySQL to PostrgreSQL" and replaced MariaDB by MySQL everywhere: I think that like this, it helps people in real situations which are officially supported by Mattermost (not only the ones moving from MariaDB, but also the ones wanting to migrate from MySQL).

In addition, I think it would correspond to the message from @agnivade in https://github.com/mattermost/mattermost-server/issues/18351#issuecomment-1153228930:

> We can definitely look into providing clear guidelines for how to migrate from MySQL to Postgres.

Would that make sense for you?

**Comment by cwarnermm** [comment]
Thank you, @biva, for your understanding and flexibility! (And thank you @elyscape for the idea to shift the focus from MariaDB to MySQL!)

As @agnivade [noted](https://github.com/mattermost/mattermost-server/issues/18351#issuecomment-1157916493), once these steps are tested and confirmed working, this is good content to add to the product documentation that will benefit others.

@biva - Don't worry too much about the formatting or RST syntax required. That's something I can help with as we finalize your PR.

**Comment by biva** [comment]
Thanks, would somebody of your team be able to review the process first, before we test it?

**Comment by agnivade** [comment]
@biva - You are most welcome to test out the steps in a dummy environment. There's no need to test out in an actual production environment.

**Comment by agnivade** [comment]
Understood. Unfortunately, it's not on our priority list as of the moment. But I'd appreciate the community's help on this. I will create an open GitHub issue regarding this.

**Comment by agnivade** [comment]
Oh my bad, I was thinking about another issue. I didn't realize that we already had https://github.com/mattermost/mattermost-server/issues/18351 created.

**Comment by cwarnermm** [comment]
@agnivade - Do we want to keep this docs PR open? I'm not sure if this PR continues to offer value if published.

**Comment by agnivade** [comment]
We can close this if we are unable to test the steps.

**Pull request closed without merging**
