### PR TITLE
Fix incorrect type of `notify_on_cancel`

### PR DESCRIPTION
**Pull request by kaakaa**
#### Summary
* Fix incorrect type of `notify_on_cancel`
* Fix indentation

#### Ticket Link
N/A

### CODE REVIEW

**Review by justinegeffen — APPROVED** [review]

**Comment by jfrerich** [comment]
Thanks @kaakaa! @hanzei, ping for review.  Hope everyone had a great break!

**Review by hanzei — APPROVED** [review]
Thanks for the fixes :+1:

**Comment by hanzei** [comment]
Don't know why CI is failing. Merging anyway.

**Pull request merged**
