### PR TITLE
Fix navigation not closing on large screens

### PR DESCRIPTION
**Pull request by minkyngkm**
#### Summary
I found and fixed an issue with the navigation menu. When opened on small screens (less than 992px), the navigation did not automatically close when the screen was resized to a larger. After the fix, it now closes automatically on larger screens.

#### Ticket Link
Fixes https://github.com/mattermost/docs/issues/7590

(before)
before

(after)
after

### CODE REVIEW

**Comment by cwarnermm** [comment]
@hanzei - Added you as a reviewer via @core-reviewers. Please reassign as needed.

**Review by hanzei — APPROVED** [review]
LGTM :+1:

**Review by cwarnermm — APPROVED** [review]
Thanks, @minkyngkm!

**Pull request merged**
