### PR TITLE
Update python to use 3.7

### PR DESCRIPTION
**Pull request by cpanato**
#### Summary
- Update python to 3.7
- update circleci aws s3 orb to the latest release available 

#### Ticket Link
Jira: https://mattermost.atlassian.net/browse/DOPS-557

### CODE REVIEW

**Comment by justinegeffen** [comment]
Thanks Carlos! This specific change requires us to use python 3.7 - is it possible to use that version? Thank you! :)

**Comment by cpanato** [comment]
@justinegeffen sure, updated to 3.8 because i saw the preview env was using that

but will move everything to 3.7

**Comment by justinegeffen** [comment]
Yeah, this is a new change related to how our conf.py file is structured and how it uses resources to build. We do currently use a different version of python (3.8 I think) but both the preview and build servers will need to be on 3.7 going forward to support the new conf.py settings. From what I understand, 3.7 is the only version that supports multi-threaded build processes (which is what we're implementing).

**Comment by cpanato** [comment]
@justinegeffen PTAL
move to python 3.7

**Review by cwarnermm — APPROVED** [review]
Thank you for this incredibly fast turnaround, @cpanato!

**Review by justinegeffen — APPROVED** [review]
Thank you!

**Pull request merged**
