### PR TITLE
Update the MySQL to Postgres migration guide with the recent feedback

### PR DESCRIPTION
**Pull request by isacikgoz**
#### Summary
I am happy that (also sad about the ambiguities it caused) the guide pick up some attention recently! There are many many feedbacks submitted among the community channels and I would like to address as much as possible.

cc @jprusch

### CODE REVIEW

**Review by nab-77 — COMMENTED** [review]
@isacikgoz fantastic update. Thank you.

@cwarnermm can you cast your eye over the table (76-99). Each row has a consequence and I would like to review.

**Review by jlandells — APPROVED** [review]
I like these changes.  It makes the whole doc feel more approachable.

**Review by agnivade — APPROVED** [review]
Getting better every day!

**Comment by jprusch** [comment]
Does it make sense to publish this version right now? I still can't get the pgloader to work with a fresh setup of a Postgres 15 server on Debian. There are some issues with the public scheme, which apparently has not been created, when creating the mattermost database. mattermost scheme exists & is populated with the schema tables. mmuser has permission to use / create in public & mattermost scheme.

Current state of migration on my side:

https://community.mattermost.com/core/pl/95nam57s1pb5mgdmaytaxatzeh

**Comment by isacikgoz** [comment]
Thanks for the feedback @jprusch I'll try to go over the migration steps with postgres 15 and try to identify issues you have. So far we tested with the minimum supported version but the `public` schema issue needs to be addressed within the docs.

**Comment by cwarnermm** [comment]
@nab-77 - I've split the table (76-99) as discussed into 2 sections: actions that can be performed without consequences, and actions that may incur consequences. Please review.

@isacikgoz - Please review to ensure I've categorized correctly.

**Comment by isacikgoz** [comment]
@cwarnermm looks good to me!

**Comment by nab-77** [comment]
@cwarnermm and @isacikgoz nice update (and see we managed to incorporate more feedback).

@jlandells your feedback most welcome here.

**Comment by jprusch** [comment]
Not sure, if the following text contains typos:

`On [newer versions](https://www.postgresql.org/docs/release/15.0/) of PostgreSQL, newly created users do not have access to public schema. The access should be explicitly granted by running GRANT ALL ON SCHEMA public to mmuser'.`
Check the last ' after mmuser

`SELECT * FROM Configurations WHERE Active = 't';`

Is it t or 1?

**Comment by isacikgoz** [comment]
Thanks @jprusch, that was a typo indeed for the `'` character. The other query for configuration table is correct, that's for postgres.

**Pull request merged**
