### PR TITLE
Update telemetry.rst

### PR DESCRIPTION
**Pull request by wiersgallak**
Docs for https://github.com/mattermost/mattermost-server/pull/14405

### CODE REVIEW

**Comment by amyblais** [comment]
Will it also be added here https://docs.mattermost.com/administration/config-settings.html?

**Comment by wiersgallak** [comment]
> Will it also be added here https://docs.mattermost.com/administration/config-settings.html?

@amyblais We do not currently list segment or rudder here and do link to the Telemetry docs, so I think it is unnecessary to add this one as well.

**Comment by amyblais** [comment]
@wiersgallak I just noticed that this was submitted to the ``v5.26-documentation`` branch so it didn't get merged into master. (The branch had already been merged to master before this PR was submitted). Maybe you can help re-submit this?

**Comment by amyblais** [comment]
Opened a PR https://github.com/mattermost/docs/pull/3921.

**Pull request merged**
