### PR TITLE
Split changelog from latest ESR

### PR DESCRIPTION
**Pull request by cwarnermm**
The Self-Hosted Changelog has become too large to manage in GitHub web tools. Split up the file based on the most recent ESR to reduce the size of the primary source file for future updates.

Notes:
- the link to the latest changelog in progress in GitHub needs to be revisited (may not be directing user to the correct view).
- the term "legacy" may not be the best term to use for recent releases prior to v5.37. Will engage the PM team for input.

### CODE REVIEW

**Comment by cwarnermm** [comment]
@wiersgallak - What are your thoughts on using the term "legacy" for the self-hosted changelog page that contains release details prior to v5.37?

@amyblais - Can you review the "changelog in progress" link, please? I'm not sure it's taking users to the right location.

**Comment by cwarnermm** [comment]
Also, @amyblais - Can you please confirm that you're able to open and modify both self-hosted changelog source files using GitHub web tools within the branch specified via this PR? Thanks!

**Comment by wiersgallak** [comment]
@cwarnermm I think the term legacy works well, especially since these versions are out of support.

**Review by amyblais — APPROVED** [review]

**Review by amyblais — APPROVED** [review]
🎉 🎉 🎉 Thank you!

 - I believe latest changelog link is correct - the query currently doesn't show a changelog PR for self-managed release as we haven't submitted a PR for the next release yet.
 - I'm able to edit both files!

**Review by justinegeffen — APPROVED** [review]

**Pull request merged**
