### PR TITLE
Update install-rhel-71-mattermost.rst

### PR DESCRIPTION
**Pull request by bkmgit**
Added information similar to that in step 9 at https://docs.mattermost.com/install/install-ubuntu-1604.html#installing-mattermost-server

### CODE REVIEW

**Comment by bkmgit** [comment]
Seems to be problematic to sign contributor agreement at https://spinpunch.wufoo.com/

**Comment by bkmgit** [comment]
Agreement signed. May need to check can view it in all browsers.

**Comment by bkmgit** [comment]
Fixed typos

**Comment by JeffSchering** [comment]
Thanks for updating @bkmgit. My mistake... I made a list of things to change, but it seems to have been lost... there's a couple tiny changes that I hope you don't mind if I just go ahead and do them now myself. One is to change mysql to MySQL (because that's the name of the product) and the other is to put a period at the end of the sentence.

**Comment by bkmgit** [comment]
Thanks.

**Pull request merged**
