### PR TITLE
Fix gencert.sh and update related files

### PR DESCRIPTION
**Pull request by enzowritescode**
#### Summary
- Fix `gencert.sh` so it correctly creates `.crt` and `.key` files
- Add better error messaging to `gencert.sh`
- Update related documentation
- Add crt/key to gitignore

#### Ticket Link
N/A

### CODE REVIEW

**Comment by cwarnermm** [comment]
Please delete the ``gencert.renamed`` file altogether as it's not needed.

**Review by esarafianou — APPROVED** [review]
Thanks Lorenzo!

One comment for improvement: There's currently no success message shown so after successful execution, it's unclear what has happened. One would need to check that the files were generated.

**Comment by enzowritescode** [comment]
> Thanks Lorenzo!
> 
> One comment for improvement: There's currently no success message shown so after successful execution, it's unclear what has happened. One would need to check that the files were generated.

@esarafianou nice catch. added!

**Review by iyampaul — APPROVED** [review]

**Comment by cwarnermm** [comment]
@enzowritescode - Feel free to merge this docs PR when you're ready.

**Pull request merged**
