### PR TITLE
Refactor config.json settings  tables in configuration-settings.rst files to remove horizontal bars

### PR DESCRIPTION
**Pull request by guruprasath-v**
### Summary
This PR refactors the configuration tables in various `.rst` files to align with the Mattermost documentation style guide by eliminating horizontal bars in tables.

### Changes Made
- **Reformatted Configuration Tables**: Updated all `config.json` entries to the format `"Setting" > "Subsetting"` across key `.rst` files, which prevents unwanted horizontal bars and improves readability.
- **Moved Note Content**: Extracted note content from tables and added it using `.. note::` tags to ensure clarity and consistency.

### Files Updated
- **Complete Refactoring**: 
   - `source/configure/authentication-configuration-setttings.rst`
   - `source/configure/site-configuration-settings.rst`
   - `source/configure/plugins.configuration-settings.rst`
- **Partial Update**:
   - `source/configure/environment-configuration-settings.rst`: Updated one table entry, as most of the documented tables were not present in the codebase.

### Additional Information
These changes address all configuration settings found with table format issues, while other configuration files were not modified as they did not contain tables needing refactoring.

### CODE REVIEW

**Comment by cwarnermm** [comment]
@guruprasath-v - Please resolve your merge conflicts in this PR.

**Review by guruprasath-v — COMMENTED** [review]
Conflict merged

**Review by guruprasath-v — COMMENTED** [review]
Modified Enabled or Disabled customer portal requests in source/configure/environment-configuration-settings.rst.

**Review by cwarnermm — CHANGES_REQUESTED** [review]
@guruprasath-v - This is an outstanding docs PR that was a BIG lift to complete. Well done and thank you! I've provided editorial and reviewer feedback inline.

In most cases, I've simply removed the bullet point formatting in cases where it isn't needed or preferred. 

Please perform a second review looking for any places where there's a single text line note that's currently formatted as a bullet and remove the bullet for consistency.

In a few cases, I've flagged some notes that should be converted to formatted notes/warnings.

**Comment by guruprasath-v** [comment]
Hi @cwarnermm, I've made the changes as per your feedback, but I had a couple of questions to clarify:
1. Single Bullet Point in Note:
   - In `source/configure/site-configuration-settings.rst` at approximately line 1470, under the sub-heading "*Maximum Markdown nodes*" there’s a `.. note::` with just one bullet point :
   
   ```
   .. note::
     - This limit applies to all Mattermost clients, including web, desktop app, and mobile app.
   ```
    Since it wasn’t explicitly flagged, should I remove the bullet here as well, or leave it as is?

2. Hypen Usage in Specific Comments:
   - In the same file, at line 1489 (as mentioned in the 66th comment), I see the following:
  
   ```
   .. note::
      - This key is used in client-side Javascript, and must have the YouTube Data API added as a service.
   ```

   - Similarly, in line 427 (mentioned in the 55th comment), there’s a note:
   
   ```
    .. note::
      - Changing this configuration setting changes the default client language for users who haven't set a language preference via **Settings**. Mattermost applies the user's language preference when specified.
   ```
   Both of these notes contain a single bullet point. Just confirming: should I keep these bullets as they are, or were they meant to be removed?

Thanks for clarifying!

**Comment by guruprasath-v** [comment]
Ma'am, @cwarnermm, I have made all the changes and pushed them to the previous PR. Please check and let me know if any further changes are needed.

**Review by cwarnermm — APPROVED** [review]
Thank you, @guruprasath-v!! Really appreciate your help with this docs issue.

**Comment by guruprasath-v** [comment]
Hi Ma'am @cwarnermm! Super excited to see our PR merged! Out of curiosity, would this contribution qualify for the Mattermost limited edition mug? 😊

**Comment by cwarnermm** [comment]
This is your first Mattermost contribution, isn't it, @guruprasath-v? Yes! First contributions to any Mattermost project area, including documentation, earns you a Mattermost limited edition mug. Thank you again for your hard work on this issue!

**Pull request merged**
