### PR TITLE
Update config-ssl-http2-nginx.rst

### PR DESCRIPTION
**Pull request by macevil**
fixed typo ssl_ciphers

#### Summary
The config-ssl-http2-nginx did not work because there was a typo in the ssl_ciphers line.

### CODE REVIEW

**Review by justinegeffen — APPROVED** [review]
Looks good editorially.

**Review by coltoneshaw — APPROVED** [review]
Looks good. Not sure how that made its way in there. Thanks for correcting it!

**Comment by justinegeffen** [comment]
@cpanato, just wanted to check that the Github pages failing to build is expected when a PR from a forked repo is submitted?

**Comment by justinegeffen** [comment]
Also getting this dialog which seems to work in terms of approval but then the deployment fails. 

Screen Shot 2021-05-05 at 14 16 48

**Comment by cpanato** [comment]
yes this allow to run the workflow

**Comment by cpanato** [comment]
i will check what is going on with the workflow, just give to me some time

**Pull request merged**
