### PR TITLE
Edited NPS rating options from 4 to 3. (for docs.mattermost.com)

### PR DESCRIPTION
**Pull request by justinegeffen**
Edited rating options from four options to three. 

Updated to add GIF demonstrating NPS widget behavior to capture user feedback on the documentation site. 

NPS rating widget (1)

### CODE REVIEW

**Comment by jasonblais** [comment]
Thanks @justinegeffen! The change itself looks good (reducing to three emoji), but I assume we'll use this PR to fix the other two issues we found after pushing the [previous PR live](https://github.com/mattermost/docs/pull/3469/files)?

**Comment by justinegeffen** [comment]
> Thanks @justinegeffen! The change itself looks good (reducing to three emoji), but I assume we'll use this PR to fix the other two issues we found after pushing the [previous PR live](https://github.com/mattermost/docs/pull/3469/files)?

Yep, that's the plan. I have raised a Jira ticket for @asaadmahmood as discussed and I believe it'll be actioned in this sprint.

**Comment by justinegeffen** [comment]
Thanks so much @asaadmahmood, this is super! 

Two questions/comments: 
1. Is it possible to add the ability to close the widget without selecting a rating? 
2. Is it possible to add hover text or a tooltip to the button? If, however, we can do option 1, we likely won't need option 2 because the user won't be "stuck" in the rating window. 

Hope this makes sense and comments aside, I'm super excited about this and really appreciate all the work you've done. :)

**Comment by justinegeffen** [comment]
Some notes about the video: 
* The pop-up opens on click (not hover) but color is highlighted on hover. 
* Video is (unfortunately) low quality due to GitHub size restrictions so the response looks slow but is very smooth on the site.

**Comment by justinegeffen** [comment]
Thanks all, this is an exciting change. Looping @amyblais in for visibility. 

@asaadmahmood, how much work would be involved in addressing @jasonblais's feedback about the "x"? If not too much, I could create a Jira ticket for it? Would add less overhead to the next phase imo.

**Comment by asaadmahmood** [comment]
I'll fix the x, no problem.

**Comment by asaadmahmood** [comment]
@justinegeffen @jasonblais Fixed the x overlap, we can add the tooltip later.

**Comment by justinegeffen** [comment]
Looks awesome, thanks @asaadmahmood! 

Screen Shot 2020-04-18 at 12 37 23

Screen Shot 2020-04-18 at 12 38 38

**Comment by jasonblais** [comment]
Sweet, thanks @justinegeffen and @asaadmahmood!

**Comment by jasonblais** [comment]
@asaadmahmood @justinegeffen Wondering if we'd be good to merge and ship live?

@justinegeffen is there a place where I can check the ratings while you're out early next week?

**Comment by justinegeffen** [comment]
@jasonblais, I'm happy to ship it so we can start getting event data in. The event data should become available under Reports > Behavior > Events.

**Comment by jasonblais** [comment]
Great! Given Asaad reviewed and made changes, I'll go ahead and merge.

**Pull request merged**
