### PR TITLE
  Updated plugins-configuration-settings.rst to address issue #7423

### PR DESCRIPTION
**Pull request by 1510janu**
Added sections:

Microsoft Calendar 
Microsoft Teams Meetings

Documentation for:
- https://github.com/mattermost/docs/issues/7427
- https://github.com/mattermost/docs/issues/7423

### CODE REVIEW

**Review by cwarnermm — APPROVED** [review]
Thanks, @1510janu!

**Comment by lindy65** [comment]
Assigned to you for testing @Rutam21 :)

**Comment by Rutam21** [comment]
### This PR has been tested in the preview environment and all the required changes are available.

- The Wildcards section has been revamped and updated with the latest information as suggested in the original issue.
- Subsections for the `Microsoft Teams Meetings plugin` and `Microsoft Calender plugin` have been added to the `Plugin configuration settings` page.

#### Preview Environment

**Wildacrds Section**

Wildcards Section

**MS Teams Meetings Plugin / MS Calender Plugin**

MSTeamsMeetingsCalenderPlugin


cc: @lindy65

**Comment by lindy65** [comment]
Thanks so much for testing @Rutam21 - counted towards Hacktoberfest

cc @cwarnermm

**Pull request merged**
