### PR TITLE
Added asterisks around a word makes it italic too

### PR DESCRIPTION
**Pull request by billybrown1**
On line 22, added the following:
You can use either ``_`` or ``*`` around a word to make it italic. Use two to make it bold.

### CODE REVIEW

**Comment by billybrown1** [comment]
This change was made based on the issue I wrote up, "Italic style markdown should not be applied to text with *asterisks* before and after them" #8264

**Comment by lindy65** [comment]
Thanks for the pull request @billybrown1 :)

I was wondering whether it would make sense to update the table as well as having the explanatory comment above?

Something like this:
image

The explanatory comment could then be changed to read:
"You can use both `_` and `*` for italics and bold text.  See the table below for examples."

How does that sound?

**Comment by billybrown1** [comment]
Yes, that sounds very good.  Since the table was not merely text but an actual graphic, I was hesitant at first to edit it, re-export and include it as part of the change submission, but I would be willing to follow through and do that.

If so I can do it fast in the next little bit since I know what I’m doing here now.

Thanks.  

—
BillyB

**Comment by lindy65** [comment]
Fantastic, thanks @billybrown1 :)

Let us know if you need any help!

**Comment by billybrown1** [comment]
@lindy65 
Ok, I've now done the following:

1)  Icreated the new updated version of the table .png file, and have attached it here.

messagestable2

2)  I also updated the text examples, to reflect this same behavior and created a new pull request ( https://github.com/mattermost/docs/pull/1800 ) with those changes.

Let me know if I need to create a Pull Request for (1) above.  I tried doing it, but I didn't see how to replace/attach a new .png (attempting to editing https://docs.mattermost.com/help/getting-started/messaging-basics.html )  

Thanks,
BillyB

**Comment by lindy65** [comment]
Thanks @billybrown1,

This is great :)  I'm going to ask a colleague for help on the table and will get back to you soonest...

**Comment by amyblais** [comment]
Hi @billybrown1 

No problem, I opened a PR here to add the table: https://github.com/mattermost/docs/pull/1808
([Preview](https://github.com/mattermost/docs/blob/7fb62a3323ef2b74ac436579fec166de42dabd1f/source/help/getting-started/messaging-basics.rst))

**Comment by billybrown1** [comment]
Thanks!  Sounds good.

—
BillyB

**Comment by lindy65** [comment]
Thanks @billybrown1 @amyblais 👍 

I'll pass this PR through for review now and we can get both merged to update the Messaging Basics doc!

**Pull request merged**
