### PR TITLE
GH-7066 (code background redundancy) 

### PR DESCRIPTION
**Pull request by chessmadridista**
#### Summary

Code redundancy issues have been resolved for prepare-mattermost-database.rst. Issues for other files will be submitted in separate PRs. Once all the files have been modified, the main issue will be marked as completed and closed. 

The redundant background was removed by removing an extra indentation in the code blocks. The redundant background can be removed in other files following the same approach.

#### Ticket Link

#7066

Note: There are multiple files that need to be taken care of in this issue. Please do not mark this issue as closed.

### CODE REVIEW

**Comment by cwarnermm** [comment]
@chessmadridista - I very much appreciate your patience on a review of this PR.

"The redundant background was removed by removing an extra indentation in the code blocks. The redundant background can be removed in other files following the same approach."

The extra indentation in the code blocks is intentional and should not be modified. Adjusting indentation isn't a viable way to address the redundant background display issue.

By default, the Sphinx theme (Furo) being used adds a background colour to code blocks. Additional CSS is being applied on top resulting in the redundant background issue.

**Comment by chessmadridista** [comment]
> @chessmadridista - I very much appreciate your patience on a review of this PR.
> 
> "The redundant background was removed by removing an extra indentation in the code blocks. The redundant background can be removed in other files following the same approach."
> 
> The extra indentation in the code blocks is intentional and should not be modified. Adjusting indentation isn't a viable way to address the redundant background display issue.
> 
> By default, the Sphinx theme (Furo) being used adds a background colour to code blocks. Additional CSS is being applied on top resulting in the redundant background issue. 

@cwarnermm Thank you for the feedback! I'll look into it and make the necessary changes.

**Comment by cwarnermm** [comment]
@chessmadridista - Are you actively working on this issue?

**Comment by chessmadridista** [comment]
Not at the moment. I plan to take it up after 2-3 weeks if nobody else picks this up. Apologies for not intimating you about the same.

**Comment by cwarnermm** [comment]
@chessmadridista - Given that this issue is assigned to you, others from the community won't pick it up. Do you plan to continue working from this PR, or do you plan to create a new docs PR?

**Comment by cwarnermm** [comment]
Closing due to inactivity.

**Comment by chessmadridista** [comment]
> @chessmadridista - Given that this issue is assigned to you, others from the community won't pick it up. Do you plan to continue working from this PR, or do you plan to create a new docs PR?

Apologies for the late response! I got busy with other stuff so won't be able to work on this issue actively at the time being.

**Pull request closed without merging**
