### PR TITLE
Update training.rst

### PR DESCRIPTION
**Pull request by lindy65**
Updated R&D meeting notes (deleted Team Updates and added further inspiration for ice-breakers)

### CODE REVIEW

**Comment by justinegeffen** [comment]
Thanks, @lindy65! Is there a link we want to add to this or is it pending? Also, would you mind if I edited this doc directly? I picked up a few unrelated things I want to refine while this is being reviewed.

**Comment by lindy65** [comment]
Hi @justinegeffen - I did add the link at the ice-breaker ideas section (https://medium.com/signal-v-noise/the-25-most-popular-icebreaker-questions-based-on-four-years-of-data-893df9b27531) 

Sure, go ahead and update whatever you need to 👍

**Comment by justinegeffen** [comment]
I've reviewed this doc and it looks like it's part of a deprecated doc set that's been moved to the handbook. I'm going to merge this change and do a review of the handbook to confirm all the content has been moved.

**Comment by lindy65** [comment]
Thanks @justinegeffen!  Appreciated :)

**Pull request merged**
