### PR TITLE
Removed Mattermost Boards and Playbooks from plugins config page

### PR DESCRIPTION
**Pull request by matthew-src**
#### Summary

This PR removes the Mattermost Boards and Playbooks content from the plugins config page ahead of the monorepo release.

### CODE REVIEW

**Comment by cwarnermm** [comment]
@wuwinson @itao - Now that the Boards and Playbooks verticals are merged into the mono-repo, is it possible to run Boards or Playbooks as plugins anymore? 

Looking for confirmation that there's no longer a need to have plugin-specific configuration settings documented for either Boards or Playbooks, and that these settings can safely be removed.

**Comment by wuwinson** [comment]
> @wuwinson @itao - Now that the Boards and Playbooks verticals are merged into the mono-repo, is it possible to run Boards or Playbooks as plugins anymore?
> 
> Looking for confirmation that there's no longer a need to have plugin-specific configuration settings documented for either Boards or Playbooks, and that these settings can safely be removed.

It should not be possible to run the plugins anymore after v7.11. cc @sbishel @lieut-data just to be 100% sure.

**Comment by lieut-data** [comment]
@wuwinson, that's correct!

**Review by cwarnermm — APPROVED** [review]
Thanks, @matthew-src!

**Pull request merged**
