### PR TITLE
Add sudo restorecon -R /opt/mattermost/ command line to the documenta…

### PR DESCRIPTION
**Pull request by Francois-D**
#### Summary
Add sudo restorecon -R /opt/mattermost/ command line to the documentation.  
Restorecon command will reset the SELinux security context for files and directories to its default values. 

#### Ticket Link
Fixes https://github.com/mattermost/docs/issues/4101

### CODE REVIEW

**Review by jespino — APPROVED** [review]
Technically looks good to me. But I'm not a SELinux user, so maybe we should include somebody else here. The reasoning behind the command makes sense.

**Comment by jespino** [comment]
@DSchalla @jupenur Any of you knows better if this command is right in this context? I think it is, but I don't have the environment to test it and I'm not very familiarized with SELinux enough.

**Review by justinegeffen — APPROVED** [review]
Great contribution, thank you!

**Comment by jupenur** [comment]
> @DSchalla @jupenur Any of you knows better if this command is right in this context? I think it is, but I don't have the environment to test it and I'm not very familiarized with SELinux enough.

Sorry, I have no idea. This is a bit too far outside my area of expertise. Maybe Daniel can pitch in though.

**Review by DSchalla — COMMENTED** [review]
Generally the command makes sense in that context, the thing I am uncertain about is whether there are any other bits that may need adaption for SELinux - For example, if we add it here we may need to make a note in our upgrade guide as well to do a restorecon to fix the SELinux context. 

If we don't we would be inconsistent at least.

**Comment by Francois-D** [comment]
> Generally the command makes sense in that context, the thing I am uncertain about is whether there are any other bits that may need adaption for SELinux - For example, if we add it here we may need to make a note in our upgrade guide as well to do a restorecon to fix the SELinux context.
> 
> If we don't we would be inconsistent at least.

Running restorecon would reset the files to the default setting.  If the user had made customized changes you would overwrite these changes possibly leading to a unexpected upgrade experience.  

Perhaps recommending to  run restorecon -n option to check the current settings to ensure that the settings are what is desired.   This would be added after point 12 in the document below.

https://docs.mattermost.com/upgrade/upgrading-mattermost-server.html#id3.

**Comment by DSchalla** [comment]
Right, my proposal was to mention during the server upgrade that another `restorecon` would be necessary.

**Review by cwarnermm — APPROVED** [review]
Thank you for this docs contribution!

**Comment by Francois-D** [comment]
> Right, my proposal was to mention during the server upgrade that another `restorecon` would be necessary.

"might" be necessary or is necessary?  Sorry I just want to clear on your point.  Thank you.

**Comment by cwarnermm** [comment]
I've logged https://mattermost.atlassian.net/browse/MM-37745 to capture the follow-on work needed for the Upgrade documentation. Thanks @DSchalla and @Francois-D!

**Pull request merged**
