### PR TITLE
Update training.rst

### PR DESCRIPTION
**Pull request by lfbrock**
It was brought up that our meeting docs here are out of date, so started a PR to fix it. @lindy65 would you be able to do a review of the platform section as well, and suggest change for anything that's no longer accurate?

### CODE REVIEW

**Comment by amyblais** [comment]
I just happened to start drafting changes for the Triage Meeting part yesterday so I added them here if it's ok - I'm happy to help with updating the other meeting sections tomorrow as well, let me know Lindy if you need any help here.

**Comment by lindy65** [comment]
Thanks @lfbrock @amyblais 

I've updated the Platform meeting section,

Please take a look and after you've added any additional changes Amy, I can ask ES or JB to review.

Thanks!

**Comment by amyblais** [comment]
Not sure if it makes sense also to take a look at the "Leads meeting" and "Developer meeting" sections (I'm not in those meetings so can't review)?

**Comment by lindy65** [comment]
Thanks @amyblais, agree...

@lfbrock - please can you review the "Leads" section... and should we request dev review for the "Dev meeting" section?

**Comment by amyblais** [comment]
Maybe @jwilander can you help take a look if updates are needed for "Developer meeting" section?

**Comment by jwilander** [comment]
Yeah it's out-of-date. We use the [Developers Meeting](https://pre-release.mattermost.com/core/channels/developers-meeting) channel to queue items and post meeting links now. Might also be good to link to [how to queue an item](https://pre-release.mattermost.com/core/pl/q4wcrcnxhtf1fr9grneb6fbrxy)

**Comment by lfbrock** [comment]
Updated the leads section

**Pull request merged**
