### PR TITLE
DOC-7533: Manage channel members page needs animated GIFs for mobile app workflows

### LINKED ISSUE #7533: Manage channel members page needs animated GIFs for mobile app workflows
## Context

To help visual learners learn how to perform tasks using the Mattermost mobile app, add visuals and short animated GIFs on the [Manage channel members](https://docs.mattermost.com/collaborate/manage-channel-members.html) page.

## Docs Request

- Add appropriate visuals/GIFs for all the steps in the `Add members to a channel` section under the mobile app tab.
- Add appropriate visuals/GIFs for all the steps in the `Add users from their profile` section under the mobile app tab.
- Add appropriate visuals/GIFs for all the steps in the `Leave a channel` section under the mobile app tab.
- Add appropriate visuals/GIFs for all the steps in the `Remove other members from a channel` section under the mobile app tab.

## Additional Notes

- Use the latest Mattermost mobile app and the standard Mattermost Denim theme to capture all workflows.
- Avoid drawing lines, arrows, boxes, or callouts on images.
- Don't forget to include ALT Text descriptions for all new image assets.
- Use existing docs pages with images as a starting point for code guidance. The Docs team can help provide RST syntax support for publication.
- Save static image files in PNG format within the docs repository's `/images` directory.

# QA Validation Criteria

In a generated docs preview:
- Visiting the respective docs page results in new, appropriate mobile-specific screenshots in each subsection from the **Mobile** tab.

### PR DESCRIPTION
**Pull request by Rutam21**
### Summary

This PR adds visual workflows for the Mattermost mobile app tab on the [Manage channel members](https://docs.mattermost.com/collaborate/manage-channel-members.html) page.

### Ticket Link

Fixes #7533 

- [x] This PR follows Mattermost Contributing Guidelines.
- [x] The changes are tested in a local docs build.

### CODE REVIEW

**Comment by Rutam21** [comment]
@cwarnermm Please review and suggest changes, if any. Thanks.

@lindy65 Please add this to my queue for QA Testing once the reviews are complete. Thank you.

**Comment by lindy65** [comment]
Assigned to you for testing @Rutam21 👍

**Comment by Rutam21** [comment]
## The changes are tested in the preview environment and reflect properly.

- The `Manage channel members` page now has respective workflow images under the mobile tab for visual learners.

Please refer to the screenshots below as a confirmation.

## Current Docs Page [[Manage channel members](https://docs.mattermost.com/collaborate/manage-channel-members.html)]

Screenshot 2024-11-04 160159

## Preview Environment Page Video

https://github.com/user-attachments/assets/c6d39fac-2a30-482c-91af-8fc80c778f7a


**[ Awaiting final review from @cwarnermm ]**

cc: @lindy65

**Comment by lindy65** [comment]
Thanks for testing @Rutam21 :)

**Review by cwarnermm — APPROVED** [review]
Thanks, @Rutam21!

**Pull request merged**
