### PR TITLE
Update plugins-configuration-settings.rst

### PR DESCRIPTION
**Pull request by coltoneshaw**
#### Summary
When setting `defaultenabled` to false it sets `Test Mode` to `true` in the UI.
Screenshot 2024-06-07 at 3 03 10 PM

### CODE REVIEW

**Comment by cwarnermm** [comment]
@streamer45 - Is this intentional product functionality?

**Comment by streamer45** [comment]
@cwarnermm Yes, `defaultenabled` was effectively relabeled as "test mode" but it's the same setting underneath as we didn't want to cause a breaking change.

**Review by cwarnermm — APPROVED** [review]
Thanks, @coltoneshaw!

**Review by streamer45 — COMMENTED** [review]
@coltoneshaw I don't think these changes are needed. The semantic is inverted due to the labeling, but the behavior is as documented. Test mode enabled (on) translates into a false value of defaultenabled.

**Comment by streamer45** [comment]
> @streamer45 - as it stands now the docs are incorrect in guidance for setting this. Setting to true does not mean only sys admins can start calls like the docs say.

Okay, that makes sense, but the setting is called "Test Mode" here, which clearly refers to the admin UI so it's confusing. I wish we deprecated it more formally now. I am okay with merging the changes here but maybe we should change the name back to what it really is and add a note instead.

**Comment by coltoneshaw** [comment]
@streamer45 i'd second more docs clarification. It took a few looks to make sure I submitted this right 😂 on being false tripped me along with naming.

**Pull request merged**
