### PR TITLE
Update config-settings.rst

### PR DESCRIPTION
**Pull request by justinegeffen**
Added value of 1500 to AD/LDAP Maximum Page Size config setting.

### CODE REVIEW

**Comment by justinegeffen** [comment]
@jasonblais raised a good point about this in that the default in config.json is 0 but we recommend 1500. Will there be a code change to support that value?

**Comment by mkraft** [comment]
> @jasonblais raised a good point about this in that the default in config.json is 0 but we recommend 1500. Will there be a code change to support that value?

Good call-out. I have created a story for it https://mattermost.atlassian.net/browse/MM-21765

**Comment by justinegeffen** [comment]
> > @jasonblais raised a good point about this in that the default in config.json is 0 but we recommend 1500. Will there be a code change to support that value?
> 
> Good call-out. I have created a story for it https://mattermost.atlassian.net/browse/MM-21765

Should we mark this as WIP for now?

**Comment by mkraft** [comment]
> > > @jasonblais raised a good point about this in that the default in config.json is 0 but we recommend 1500. Will there be a code change to support that value?
> > 
> > 
> > Good call-out. I have created a story for it https://mattermost.atlassian.net/browse/MM-21765
> 
> Should we mark this as WIP for now?

The way I read what you have written in this PR there's no mention of the default so MM-21765 wouldn't affect this text.

**Comment by justinegeffen** [comment]
The documentation mentions this:
"----------------------------------------------------+
| This feature's ``config.json`` setting is ``"MaxPageSize": 0`` with numerical input.                                                                                 |
"
so I was wondering whether that would be problematic?

**Comment by mkraft** [comment]
> The documentation mentions this:
> "----------------------------------------------------+
> | This feature's `config.json` setting is `"MaxPageSize": 0` with numerical input. |
> "
> so I was wondering whether that would be problematic?

That will need to be updated with MM-21765.

**Comment by justinegeffen** [comment]
> > The documentation mentions this:
> > "----------------------------------------------------+
> > | This feature's `config.json` setting is `"MaxPageSize": 0` with numerical input. |
> > "
> > so I was wondering whether that would be problematic?
> 
> That will need to be updated with MM-21765.

So can we leave it in there for now, or should we hold off on pushing this change until MM-21765 is done, and then update the content to say "1500" instead?

**Comment by mkraft** [comment]
> > > The documentation mentions this:
> > > "----------------------------------------------------+
> > > | This feature's `config.json` setting is `"MaxPageSize": 0` with numerical input. |
> > > "
> > > so I was wondering whether that would be problematic?
> > 
> > 
> > That will need to be updated with MM-21765.
> 
> So can we leave it in there for now, or should we hold off on pushing this change until MM-21765 is done, and then update the content to say "1500" instead?

We could push these changes now and do a separate documentation change once the default value is changed in code.

**Comment by justinegeffen** [comment]
That works for me, thanks. I've started watching the Jira ticket and added a Documentation label so it's on my radar. Thanks for all the help. :)

**Pull request merged**
