### PR TITLE
Update collaborate-within-connected-microsoft-teams.rst

### PR DESCRIPTION
**Pull request by johndavidlugtu**
Correct mention of "embedded" experience in the "connected experience" page

### CODE REVIEW

**Review by cwarnermm — APPROVED** [review]
Thanks, @johndavidlugtu!

**Comment by cwarnermm** [comment]
@johndavidlugtu - There are numerous instances of "embedded" across the docs content for this functionality. Would you like additional references of "embedded" updated as well?

**Comment by johndavidlugtu** [comment]
@cwarnermm are you open to providing examples?

There are places where "embedded" makes sense when describing the embedded experience

**Comment by cwarnermm** [comment]
@johndavidlugtu - the bulk of the references are on the [Collaborate within embedded Microsoft Teams](https://docs.mattermost.com/collaborate/collaborate-within-embedded-microsoft-teams.html) docs page, where I believe they make sense.

**Pull request merged**
