### PR TITLE
Update elasticsearch.rst

### PR DESCRIPTION
**Pull request by justinegeffen**
https://github.com/mattermost/docs/issues/3111

### CODE REVIEW

**Comment by hanzei** [comment]
@justinegeffen Is this ready for review?

**Comment by justinegeffen** [comment]
I commented on the original issue but am reposting here. I've added three of the four questions to the ES content.

For question four, I'd like to clarify whether the customer is asking for a search string to account for that or whether they're confirming that it's possible to access logs that indicate the number of queries per user per day.

I'd like to include use cases and/or examples if they'll benefit customers and decrease the need to reach out to us. It's just a case of what would be most useful to a larger audience.

**Comment by justinegeffen** [comment]
Thanks, @wiersgallak! Before this is merged, I wanted to follow up on my question around point 4 and confirm whether the issue is limited to the customer in question or it's a general question. I can add the content either way, but if there's more context around it (and examples if required) that'd be very helpful. :)

**Comment by wiersgallak** [comment]
@justinegeffen I'd be very generic about the answer, but think its worth including - maybe we can adjust the question a bit: 

**How much data is sent to ElasticSearch?**

Every time a message is published, a channel is created or a user changes, either because their properties change (e.g.: change of the first name) or because they join/leave a channel, that post/channel/user is sent to ES.

As for queries, if the search feature through ES is enabled, every search will generate a query, and if the autocompletion feature is enabled, every user or channel autocompletion when writing a message or user search will generate a query.

**Comment by justinegeffen** [comment]
Thanks, @wiersgallak. I've updated the doc with the new entry.

**Pull request merged**
