### PR TITLE
Create an admin guide for Atlassian integrations

### PR DESCRIPTION
**Pull request by jasonblais**
cc: @lfbrock as FYI

### CODE REVIEW

**Comment by wiersgallak** [comment]
Information looks good to me.  Wondering if this should live under the [Integrations Guide](https://docs.mattermost.com/guides/integration.html) instead or https://docs.mattermost.com/guides/administrator.html#mattermost-integrations (we should consider combining these two as well in the future).  Deployment already has so much in it and this one does not seem to fall into that category as easily as integrations.

**Comment by jasonblais** [comment]
@wiersgallak I envision this section be a generic overview of how to integrate with Mattermost, and the Integration Guide being more specific features/functionality supported by Mattermost.

image

Long-term (in a couple of months) I'd envision having

```
Admin > Mattermost Integrations
   Atlassian Tools
   CI/CD Tools
   Incident Response & Monitoring
   Audio, Video & Screenshare
   Bots
   Productivity Tools
```

and

```
Integrations Guide
   API
   Incoming Webhooks
   Outgoing Webhooks
   Slash Commands
   Plugins (Beta)
   Developer Toolkit
   etc...
```

Let me know what you think, though.

**Comment by amyblais** [comment]
Should this be in a table of contents?

**Comment by jasonblais** [comment]
@amyblais Good catch, should be, PR here https://github.com/mattermost/docs/pull/2746

**Pull request merged**
