### PR TITLE
Japanese trans integration guide

### PR DESCRIPTION
**Pull request by aiot-ogino**
#### Summary

Add Japanese translation for "Integration Guide" part

### CODE REVIEW

**Comment by jasonblais** [comment]
Thank you!

cc @justinegeffen (our technical writer for docs) and @sandrospadaro who has helped with Italian translations at #3457

I'll see what we can do to move both of these PRs along and get the first versions merged. Exciting, thank you to both of you @aiot-ogino and @sandrospadaro!

**Comment by jasonblais** [comment]
cc @wget from our localization community, and @kaakaa from our Japanese contributor community, FYI

**Comment by jasonblais** [comment]
@aiot-ogino Thanks again for the contribution, this is great! We have some on-going conversations about the Italian translations at https://github.com/mattermost/docs/pull/3457.

I'm adding some of those questions here too, if you have already thought about them.

1. Do you have an active test instance running with the integrations guide translated to Japanese?
2. Do you know if there are other options for choosing different languages? While I do like the idea of using the readthedocs lower left menu, I wonder how easy it is to find it. Another option is to do a custom solution where the user can choose the language via the page header or footer. What do you think? We would likely have resources to help add this.
3. What are your thoughts on screenshots - should we keep the original English versions of the screenshots, or consider translated versions of them too?

Things to test or complete before merging:

4. Have at least one member of UX team and one member of Apps PM team review the user experience in choosing different languages
5. If we use readthedocs lower left menu, sign up to become a "Gold Member" for $50/month to remove ads (https://readthedocs.org/sustainability/)
6. To maintain high standards for translated documentation, set up a process to notify translators when something is changed in the English-version of the docs, and expectation on correcting translations for new releases
7. Decide if we want to indicate translations level - e.g. “Alpha” or “Beta” for translations that are in progress
8. Test you can successfully rate a translated docs page with the new ratings system
image

**Comment by justinegeffen** [comment]
This is really awesome! Happy to help with whatever is needed. :)

**Comment by aiot-ogino** [comment]
A1. Sorry, we only have a local instance which is not accessible from Internet.
A2. Your idea which uses the option of readthedocs is good. But I'm not familiar with that theme.
A3. The snapshot is made by Fri Dec 20 2019 d5db3359c25c0c7962f9884ae09cd1fa0b3d8e8a. I'm not sure how to specify the exact tag. When I forked from GitHub UI, then it was made automatically.

**Comment by justinegeffen** [comment]
Hi, @aiot-ogino! I've taken a look at your PR using our preview client (you can take a look [here](https://docs-git-fork-aiot-ogino-japanese-trans-integration-guide.mattermost.vercel.app/guides/integration.html). Would you be open to providing the steps to access the translated content as I'm not able to find the translations. Once we have the translated content available in a preview, we can address @jasonblais's other questions, decide on options around language selection, screenshots and so on. :)

**Comment by aiot-ogino** [comment]
Hi, @justinegeffen. You should make  with a language option like `make -e SPHINXOPTS="-D language='ja'" html`. Then it generates html files under the build folder. So I think it needs another language set for each translated docs.  How about adding a Japanese docs link in the header.

japanese-docs

**Comment by justinegeffen** [comment]
Thanks, @aiot-ogino, that is really helpful. I'll look into that today and will revert with feedback ASAP. :)

**Comment by jasonblais** [comment]
@justinegeffen any updates for this PR? Thanks! :)

**Comment by justinegeffen** [comment]
Thanks for the reminder, @jasonblais. I need to look into the build again as I wasn't able to get it working, and revert on this.

**Comment by justinegeffen** [comment]
Closed and reopened to kick off new preview build.

**Comment by lindy65** [comment]
Hi @justinegeffen - I'm helping review stale PRs and wondered what the status is on this one?  

//cc @aiot-ogino @jasonblais

**Pull request closed without merging**
