### PR TITLE
Update the how to enable slash commands

### PR DESCRIPTION
**Pull request by axilleas**
Use new option names in Custom Integrations

### CODE REVIEW

**Comment by axilleas** [comment]
I'm writing the GitLab slash commands docs and I used the `mattermost-preview` Docker image to test things. When I went to https://docs.mattermost.com/developer/slash-commands.html#enabling-custom-commands, the names were not the same.

**Comment by esethna** [comment]
Thanks for the update!

**Comment by axilleas** [comment]
@esethna Am I the only one that sees an XML file in https://docs.mattermost.com/developer/slash-commands.html? Did I break anything? :/

**Comment by jasonblais** [comment]
Seems to work now, can you try again @axilleas? Might have accessed the page in the middle of an update

**Comment by axilleas** [comment]
@esethna oh yeah! Works now, thanks again!

**Pull request merged**
