### PR TITLE
DOC-7528: Convert public channels to private channels page needs animated GIFs for mobile app workflows

### LINKED ISSUE #7528: Convert public channels to private channels page needs animated GIFs for mobile app workflows
## Context

To help visual learners learn how to perform tasks using the Mattermost mobile app, add visuals and short animated GIFs on the [Convert public channels to private channels](https://docs.mattermost.com/collaborate/convert-public-channels.html) page.

## Docs Request

- Add appropriate visuals/GIFs for all the steps in the `Convert public channels to private channels` section under the mobile app tab.

## Additional Notes

- Use the latest Mattermost mobile app and the standard Mattermost Denim theme to capture all workflows.
- Avoid drawing lines, arrows, boxes, or callouts on images.
- Don't forget to include ALT Text descriptions for all new image assets.
- Use existing docs pages with images as a starting point for code guidance. The Docs team can help provide RST syntax support for publication.
- Save static image files in PNG format within the docs repository's `/images` directory.

# QA Validation Criteria

In a generated docs preview:
- Visiting the docs page results in appropriate new mobile-specific screenshots in each subsection from the **Mobile** tab.

### PR DESCRIPTION
**Pull request by Rutam21**
### Summary

This PR adds visual workflows for the Mattermost mobile app tab on the [Convert public channels to private channels](https://docs.mattermost.com/collaborate/convert-public-channels.html) page

### Ticket Link

Fixes #7528 

- [x] This PR follows Mattermost Contributing Guidelines.

### CODE REVIEW

**Comment by Rutam21** [comment]
@cwarnermm Please review and suggest changes, if any. Thanks.

@lindy65 Please add this to my queue for QA Testing once the reviews are complete. Thank you.

**Comment by lindy65** [comment]
Assigned to you for testing @Rutam21 - will still count towards Hacktoberfest as it was done before end of day 31 October

**Comment by Rutam21** [comment]
## The changes are tested in the preview environment and they reflect properly.

- The `Convert public channels to private channels` page has now 5 workflow images for visual learners under the mobile section tab.

Please refer to the screenshots below as a confirmation.

### Current Docs Page [[Convert public channels to private channels](https://docs.mattermost.com/collaborate/convert-public-channels.html)]

Screenshot 2024-11-01 143035

### Preview Environment Page

**Step 1**

Screenshot 2024-11-01 143247

**Step 2**

Screenshot 2024-11-01 143308

**Step 3**

Screenshot 2024-11-01 143340

**Step 4**

Screenshot 2024-11-01 143402

**Step 5**

Screenshot 2024-11-01 143415

**[ Awaiting final review from @cwarnermm ]**

cc: @lindy65

**Comment by lindy65** [comment]
Thanks for testing @Rutam21 - counted towards Hacktoberfest

**Pull request merged**
