### PR TITLE
[Prototype] i18n support for docs with "sphinx-intl"

### PR DESCRIPTION
**Pull request by terukizm**
ref: http://www.sphinx-doc.org/en/stable/intl.html

Please give me some advice.
I will "git squash", if you wish.

# Tested environment:

Python 2.7.11

```
recommonmark==0.4.0
sphinx-autobuild==0.6.0
sphinx-rtd-theme==0.1.9
```

# Make HTML:

in Japanese: _(sorry, my translation sample is only "index.html")_

```
$ make -e SPHINXOPTS="-D language='ja'" html
```

output is:

in English, same as it was. no change.

```
$ make html
```

# Translation in other language:

e.g. Korean(ko)

```
$ pip install sphinx-intl
$ make gettext

$ sphinx-intl update -p build/locale -l ko
$ vi source/locale/ko/LC_MESSAGES/*.po
(translation working)

$ make -e SPHINXOPTS="-D language='ko'" html
$ open build/index.html
```

# If based-document is updated:

```
$ make gettext
$ sphinx-intl update -p build/locale
```

----

# Known issues:

## Don't support *.md files.

*.md files does not support, only *.rst. (e.g. `source/install/prod-rhel-6.md`)

If you need, use [pandoc](http://pandoc.org/), be able to convert *.md to *.rst.

---

# Feature Ideas:

## Use submodules

Move locale-files to new repository (e.g. "mattermost/docs-ja"), and use git-submodules.

```
$ mv source/locale/ja/ {docs-ja}

$ git submodule add https://git@github.com:mattermost/docs-ja.git source/locale/ja
```

## Change hosting style

Maybe, need some modification in your deploy process, and `DocuementRoot` settings.

e.g.

```
http://docs.mattermost.com/ja/
http://docs-ja.mattermost.com/
```
---

Thank you for your consideration.

### CODE REVIEW

**Comment by it33** [comment]
Hi @terukizm, 

This is a wonderful beginning. 

There are a number of countries where English is less commonly used. Localized documentation would be a significant benefit. 

There are a few things that need to happen for this to work:     
1. We need to convert .md files to .rst 
2. We need a process to review translations before they are committed
3. We need a process to update translations after the English version changes. 

Very open to thoughts from the community on how we can make these changes? 

Here is a [feature idea](https://mattermost.uservoice.com/forums/306457-general/suggestions/13194339-mattermost-doc-i18n-support-with-sphinx-intl) on this change as well.

**Comment by terukizm** [comment]
Hi, @it33.

Thank you for your response!

I know those problems, and I think so too.
This idea is low priority on the Mattermost's loadmaps, and
2. and 3. are very difficult problem, and so much hassle.

In spite of  I know, I suggested this approach.
My reason is very very simple.
"I will forget this approach" !

I found so grate project "[Mattermost Translation Server](http://186.202.167.109/)",
and localization-contributers are in so active.
(Mattermost is a superb product, it was really less surprising!!)

I think It will be necessary in the near future, 
I hope if this approach could be of any help.

When the time comes, I would be happy if you remember this PR.
Could I close this PR?

P.S.
Mattermost is so grate product, I know it.
But I never think Mattermost made me study English!  :laughing: 

Thank you for putting up with my poor English.
 I will try my best to contribute to Mattermost!

**Comment by it33** [comment]
Hi @terukizm, 

Thank you for your kind support. 

We are very impressed with your work on [Mattermost on Qiita.com](http://qiita.com/tags/Mattermost).

Would you be interested in [helping us add more guidance for Japanese speakers to Mattermost documentation](https://github.com/mattermost/docs/issues/83)? 

image

I think it is fine to leave this pull request open for now. It is a reminder that after we change from .md to .rst we can work together to add this.

**Comment by terukizm** [comment]
Dear @it33.

Thank you too. I have a great weekend!

> Would you be interested in helping us add more guidance for Japanese speakers to Mattermost documentation?

Of course! 

But I would love to try other approach on  [this issue](http://docs.mattermost.com/install/requirements.html#database-software).
That is a using fulltext-search software (like "Elasticsearch").

This approach has some strengths:

- Be able to use other language, not only CJK.
  - I'm looking forward to It can be easily support multi-language with search-message feature. 
    - ref: https://www.elastic.co/guide/en/elasticsearch/reference/2.3/analysis-lang-analyzer.html
    - e.g. "umlaut" support in German ( I dont know German more than English, it is maybe wrong...)
- Easy to FULLTEXT INDEX can cause peformance problems.
  - I'm worried about that if `Polls` talbes have many records.
- Be able to fuzzy-search (?)
  - ref: https://www.elastic.co/blog/found-fuzzy-search
    - Sorry, I know fuzzy-search only Japanese.... 

And some weakness:

- System structure more and more complicated. 
- Need indexing time.
  - https://www.elastic.co/guide/en/elasticsearch/guide/current/indexing-performance.html
  - https://www.elastic.co/blog/performance-considerations-elasticsearch-indexing
- Become unusable RDBMS-audit-support in search-feature.

I would to contribute to by programmer, but I strongly sensed the necessity of study English. :disappointed: 
Should I [help to transfer project](https://github.com/mattermost/platform/issues/2444) in Japanese first? 
I would appreciate it if I could get your advice.

> I think it is fine to leave this pull request open for now. It is a reminder that after we change from .md to .rst we can work together to add this.

Very thanks!
Thank you for your kind response.

**Comment by it33** [comment]
Thanks @terukizm, 

Highly appreciate the suggestion on Elastic Search. I plan to discuss it Monday with the team to hear their thoughts. I will reply back when I have their opinions. 

I think translating Mattermost to Japanese as a first step would be highly valuable. 

Thank you for your help!

**Comment by terukizm** [comment]
@it33 
Thanks a lot!

In my opinion, using-problems are only 2 points in Japanese.

1.  No localized documentation
  - Japanese people are able to probably use English UI/UX. (e.g. Slack is not localized in Japanese.)
    - My English is very poor, but I feel that Mattermost's messages are not difficult. 
  - But I am troubled reading document... 
    - I made this PR, that is why.
2. No support message-history-search in Japanese
  - "history-search" is one of the most important and high demand.  

Maybe, I think other languages are same.
I feel Mattermost has no weakpoint if these problems are solved.
And I would be happy if I could be of even a little help. 

Thank you for your advice, and have a good weekend!

**Comment by it33** [comment]
Hi @terukizm, 

Thank you for your feedback. 

1. Would you help us correct and expand our Japanese documentation? 

   We have started some here: https://github.com/mattermost/docs/blob/master/source/install/i18n.rst

2. Elastic search seems very complicated

    We are concerned about the complexity of adding Elastic Search right now because of the complexity and testing needed. There is more guidance on Postgres search with Japanese: https://github.com/mattermost/platform/issues/2159#issuecomment-206444074

    What do you think of this approach?

**Comment by terukizm** [comment]
Hi @it33,
Thank you for your kind response.

> 1.Would you help us correct and expand our Japanese documentation?

"Sure thing!"  :wink: 

Many Japanese people are interested Mattermost.
I would appreciate if you could make Japanese-discussion-forum(e.g. github-issue/forum-thread/Mattermost-channel), if it is possible and so easy. 

> 2.Elastic search seems very complicated

I agree.
I have trying to use elasticsearch, basic search is mostly done.

But  considering "teamId" search is not yet. It will take more time.
I'll suggest you again, if existing all testcase will have passed. ( I'd like to provide compatible with RDBMS fulltext-search) 

Thank you very much for your discussion.

I hope I could contribute to Mattermost as a Japanese, and as a programmer.
I would be happy if I could be of even a little help.

**Comment by it33** [comment]
Thanks @terukizm, 

> I would appreciate if you could make Japanese-discussion-forum(e.g. github-issue/forum-thread/Mattermost-channel), if it is possible and so easy.

I would be happy to host a location for the Japanese community. 

I'm not sure I understand "Japanese-discussion-forum(e.g. github-issue/forum-thread/Mattermost-channel)". 

I've created a [Japanese category at forum.mattermost.org](https://forum.mattermost.org/c/international/japanese) that you can use? 

[Here is an example of how the French community is using the forum](https://forum.mattermost.org/c/international/francais-french)

You are also welcome to join our nightly builds server and create a public channel for Japanese speakers: https://pre-release.mattermost.com/core/channels/french-localization

I've also added a channel for Japanese discussion on the nightly builds server: https://pre-release.mattermost.com/core/channels/i18n-japanese

You're welcome to use it and invite other community members? 

> I have trying to use elasticsearch, basic search is mostly done.

Thank you for developing this. I hope Elastic Search can solve your issue. 

That said, we would not be able to accept Elastic Search support in the `platform` repository as it would be too difficult for us to test and maintain. 

Right now, we need to recommend Japanese users configure MySQL and Postgres to support Japanese search.

**Comment by terukizm** [comment]
Thanks @it33,
and please forgive me my poor English...

> I'm not sure I understand "Japanese-discussion-forum(e.g. github-issue/forum-thread/Mattermost-channel)".
> I've created a Japanese category at forum.mattermost.org that you can use?

This is exactly the thing I wanted!!

> You're welcome to use it and invite other community members?

I’ll give it a try! 

> That said, we would not be able to accept Elastic Search support in the platform repository as it would be too difficult for us to test and maintain.

I'm too sorry, that was none of my business.
I respect your intention. :blush: 

> Right now, we need to recommend Japanese users configure MySQL and Postgres to support Japanese search.

OK, I'll try it.
(https://github.com/mattermost/platform/issues/2622, isnt it?)
I would like to discuss with @yukihane, and I'll "correct and expand our Japanese documentation".

**Comment by esethna** [comment]
Thanks for this contribution. Closing this for now until we figure out our internal processes and transition to rst. Feel free to contribute on the [discussion forums](https://forum.mattermost.org/c/international/japanese) until then. Thanks!

**Pull request closed without merging**
