### PR TITLE
Fix mismatched quotes in production install instructions

### PR DESCRIPTION
**Pull request by hmhealey**

### CODE REVIEW

**Comment by jasonblais** [comment]
Fixed a couple of formatting issues, otherwise looks good, thanks!

Note: Propose holding off on merge until #742 is merged, which should be soon. Otherwise it'll lead to merge conflicts.

**Comment by JeffSchering** [comment]
Note that all of these files with the exception of `prod-debian.rst` are superseded by https://github.com/mattermost/docs/pull/742

**Comment by esethna** [comment]
@JeffSchering if you don't mind helping to verify all the fixes in this PR are covered in your PR (#742), then we can close this.

**Comment by JeffSchering** [comment]
It's safe to merge these changes in. PR https://github.com/mattermost/docs/pull/742 does not make any changes to these files. It only removes them from the ToC, with the exception of `prod-debian.rst`.

My plan is that after https://github.com/mattermost/docs/pull/742 is merged, I'll replace the contents of these files with a note that they have been superseded by the new files, and have a link to the new files. This is to make sure that people who have links directly to the old instructions can get to the new install instructions.

**Comment by esethna** [comment]
Ah got it, thanks @JeffSchering!

**Pull request merged**
