### PR TITLE
Updated sso-office.md

### PR DESCRIPTION
**Pull request by Shivam7-1**
#### Summary

Updated some typos

### CODE REVIEW

**Review by justinegeffen — APPROVED** [review]

**Comment by justinegeffen** [comment]
Awesome, thanks for this PR, @Shivam7-1! :)

**Comment by Shivam7-1** [comment]
How can I get mug by mattermod where I have to fill my details

**Comment by Shivam7-1** [comment]
How can I get mug by mattermost where I have to fill my details @justinegeffen

**Comment by justinegeffen** [comment]
Hi @Shivam7-1. @hannaparks will be able to assist you with your question. :)

**Comment by hannaparks** [comment]
Hi @Shivam7-1, we use the information you submitted on the CLA form.  If you need to update the information on your CLA form, please help submit a new CLA form and I can replace it with the previous one.

**Comment by Shivam7-1** [comment]
@hannaparks what are the swags will I get from mattermost And how many days it will take to get swag shipped to my location

**Comment by Shivam7-1** [comment]
Hi @justinegeffen and @hannaparks can I get to know that I have won the mattermost mug if yes will I get to know that when it's arravied to my location

**Pull request merged**
