### PR TITLE
v5.20 Changelog

### PR DESCRIPTION
**Pull request by amyblais**

### CODE REVIEW

**Comment by amyblais** [comment]
@mkraft Please help with this information for v5.20 changelog: 

- Any new config.json settings
- Database Changes
- API Changes
- Websocket Event Changes

**Comment by mkraft** [comment]
> @mkraft Please help with this information for v5.20 changelog:
> 
> * Any new config.json settings
> * Database Changes
> * API Changes
> * Websocket Event Changes

# New config settings:
* `SamlSettings.IdpMetadataUrl`
* `SamlSettings.EnableAdminAttribute`
* `SamlSettings.AdminAttribute`
* `PluginSettings.EnableRemoteMarketplace`
* `PluginSettings.AutomaticPrepackagedPlugins`

# New DB columns:
* `Bots.LastIconUpdate`
* `GroupTeams.SchemeAdmin`
* `GroupChannels.SchemeAdmin`

# New API endpoints:
* `PUT /config/patch`
* `POST /server_busy`
* `GET /server_busy`
* `DELETE /server_busy`

# New websocket events:
* `channel_restored`

**Comment by amyblais** [comment]
@jasonblais Please see new config settings ^

**Comment by jasonblais** [comment]
Thanks @amyblais! PR submitted for diagnostics https://github.com/mattermost/mattermost-server/pull/13868

I did notice that 
 - SamlSettings.EnableAdminAttribute
 - SamlSettings.AdminAttribute

were also added to LdapSettings

**Pull request merged**
