### PR TITLE
Create deploy-turnkeylinux.rst

### PR DESCRIPTION
**Pull request by qq7**
An open-source alternative to Bitnami Mattermost stack on Debian 9

### CODE REVIEW

**Comment by jasonblais** [comment]
@qq7 Thank you, this is awesome! Just confirming that the Turnkey Linux app for Mattermost is hosted here https://github.com/turnkeylinux-apps/mattermost ?

**Comment by qq7** [comment]
@jasonblais Yes, this is the appliance build code for our [build system](https://www.turnkeylinux.org/tkldev)

**Comment by jasonblais** [comment]
@qq7 Sorry for my delayed response.

We have a directory of community-built integrations, apps and deployment solutions here: https://about.mattermost.com/community-applications/#privateApps It includes a list of deployment solutions such as Puppet, Chef Cookbook and Ansible.

image

Would you be open for us to add it on that list? That way it is grouped with other deployment solutions.

**Comment by jasonblais** [comment]
Thank you @qq7 and @JedMeister! You can share about the project here, and it'll get added to the apps directory :) 

https://www.mattermost.org/share-your-mattermost-projects/

Look forward to the addition!

**Comment by jasonblais** [comment]
I'll close this particular doc issue in favor of the app directory entry.

**Pull request closed without merging**
