### PR TITLE
Update telemetry.rst

### PR DESCRIPTION
**Pull request by justinegeffen**
Some formatting and name convention changes.

@agarciamontoro, PLMK whether the incident collaboration section is still accurate. Thanks. :)

@hanzei / @aaronrothschild: PLMK where the update for https://github.com/mattermost/mattermost-webapp/pull/6428/ should go. Thanks. :)

### CODE REVIEW

**Comment by justinegeffen** [comment]
Potential updates for: https://github.com/mattermost/mattermost-webapp/pull/6428

**Review by agarciamontoro — APPROVED** [review]
Looks good!

**Comment by aaronrothschild** [comment]
@justinegeffen I think we should add something like "Search terms used in Marketplace on cloud workspaces will be recorded" in a "Plugin Telemetry" area.

**Review by cwarnermm — APPROVED** [review]
Thanks! These are great updates!

**Pull request merged**
