### PR TITLE
Fix 404 links

### PR DESCRIPTION
**Pull request by kaakaa**
Fix links that returns 404 Not Found.

### CODE REVIEW

**Comment by kaakaa** [comment]
@jasonblais Thanks for changing the link! 
But it seems that the link you changed is incorrect...

`https://about.mattermost.com/default-plugins-uploads` ([docs](https://docs.mattermost.com/administration/config-settings.html#plugins-beta))
`https://about.mattermost.com/default-plugin-uploads` (The link you changed)

So the link in online document have returned 404 yet.

**Comment by jasonblais** [comment]
@kaakaa I didn't actually make the change, just proposed that https://about.mattermost.com/default-plugin-uploads should work.

Or do you get a 404 error if you try to access it

**Comment by kaakaa** [comment]
@jasonblais Oh..I misread it, sorry. And now I got it.
As you say, https://about.mattermost.com/default-plugin-uploads works correctly for me.

So I fix the link https://about.mattermost.com/default-plugins-uploads (returning 404) to https://about.mattermost.com/default-plugin-uploads?

**Comment by jasonblais** [comment]
@kaakaa That's correct, that should work. We use https://about.mattermost.com/default-plugin-uploads also in the System Console, so if we ever changed the location of that help doc, we only need to change where https://about.mattermost.com/default-plugin-uploads redirects to.

**Comment by jasonblais** [comment]
Thanks @kaakaa!

**Comment by kaakaa** [comment]
@jasonblais Thanks!

And since I found same link (returning 404) in mattermost-webapp, I'll fix it later.
https://github.com/mattermost/mattermost-webapp/blob/ce861eaca2ec2a070ac66dec8c6b40aab88c25b0/i18n/en.json#L735

**Pull request merged**
