### PR TITLE
Update deprecated configuration settings documentation

### PR DESCRIPTION
**Pull request by belkhoujaons**
#### Summary
Remove deprecated configuration setting from product documentation

#### Ticket Link

  Fixes https://github.com/mattermost/docs/issues/7460

### CODE REVIEW

**Comment by belkhoujaons** [comment]
> Thanks, @belkhoujaons!!
> 
> Please also remove the following text from that page:
> 
> ```
> Mattermost Boards setting
> --------------------------
> 
> *Removed in the Mattermost v8.0 release*
> ```

done !

**Comment by cwarnermm** [comment]
@belkhoujaons - Are you open to signing the Mattermost CLA? This step is required in order to merge your changes into the documentation code base.

**Review by cwarnermm — APPROVED** [review]
Thank you, @belkhoujaons!!

**Comment by belkhoujaons** [comment]
> @belkhoujaons - Are you open to signing the Mattermost CLA? This step is required in order to merge your changes into the documentation code base.

I just signed for that and it needs approval

**Comment by cwarnermm** [comment]
@belkhoujaons - Please comment in this PR with `/check-cla` and confirm that the CLA check is green. If it isn't, I'll investigate further.

**Comment by Rutam21** [comment]
@lindy65 You can assign this to me for QA Testing. Thanks.

**Comment by Rutam21** [comment]
@cwarnermm Please generate another preview environment so that it includes the latest commits in the PR. Thanks.

**Comment by lindy65** [comment]
Assigned to you @Rutam21 and kicked off a new preview environment

**Comment by Rutam21** [comment]
### The changes in this PR have been tested in the preview environment and all the required updates are available in the mentioned pages.

- The `Mattermost Board Settings` section doesn't show up on the Deprecated Configuration Settings page on the Docs Site.
- The `Mattermost Board Settings` link doesn't show up on the top of this page and is removed from the table of contents.
- Searching for the `Mattermost Board Settings` or `Enable publicly-shared boards` doesn't return a result in the Additional Information section that points to this removed section.

I've attached a video as a confirmation.

https://github.com/user-attachments/assets/dd1fd529-d802-4a87-ae15-280103544da4

cc: @lindy65

**Comment by lindy65** [comment]
Thanks for testing @Rutam21 - counted towards Hacktoberfest!

cc @cwarnermm

**Pull request merged**
