### PR TITLE
Add HAProxy Install/Configuration

### PR DESCRIPTION
**Pull request by kjkeane**
This PR adds the installation and configuration of HAProxy on 
* Ubuntu
* RHEL

I am not an expert in HAproxy and this is how I currently am running HAProxy.  So if there are any important details missing from the documentation feel free to suggest.

### CODE REVIEW

**Comment by jasonblais** [comment]
Hey @kjkeane, 

And terribly sorry for the delay in our response. We were discussing the best course of action for your wonderful contribution.

First and foremost, we highly appreciate your contribution. It is great to see members like yourself sharing knowledge that can benefit others in the community.

The hesitation we have accepting your contribution to the official Mattermost documentation is that we don't have anyone on our team who can review and test the HAProxy set up, nor maintain or support it in the future. We're also not aware of customers running Mattermost on HAProxy.

As a result, wondering if you'd be open to sharing your HAProxy install and configuration guides at our forums (https://forum.mattermost.org). Community members are actively engaged there as well.

**Comment by lindy65** [comment]
Hi @kjkeane,

Hope you're well? :)  Wondering whether you've had a chance to give some thought to sharing your HAProxy install and configuration guides at our forums (https://forum.mattermost.org)?

We have a vibrant, active forum community who I'm certain will benefit greatly from your guides.  

Thank you again for your most valued contribution, much appreciated!

**Comment by kjkeane** [comment]
Hi @lindy65, sorry for the late response.  I have been busy at work.  I have given it some thought and I will share the guide and configuration at the forums.  Again, I am sorry for not responding earlier.

**Comment by kjkeane** [comment]
Here is a link to the forum post

https://forum.mattermost.org/t/guide-using-haproxy-with-mattermost/4117?u=kjkeane

**Comment by lindy65** [comment]
Thanks so much @kjkeane :)  Fantastic!

**Pull request closed without merging**
