### PR TITLE
Proposing process to post deprecation plans

### PR DESCRIPTION
**Pull request by it33**
Proposal to prevent future "surprises" for the community over changes to features such as thumbnail controls: https://about.mattermost.com/mattermost-4-0/#comment-3436068337

### CODE REVIEW

**Comment by lfbrock** [comment]
we already have a process for this so you need to update it in both places and make sure it's consistent: https://github.com/mattermost/docs/blob/master/source/process/deprecated-features.rst

I think we should add a guideline about how often in advance we should try to announce the deprecation as well.

**Comment by hmhealey** [comment]
In cases like those image sizes, we could also include a brief point in the marketing about why the settings are being removed. I think that guy thinks we're removing the ability to post images like Slack does which wasn't how it worked in the first place.

**Comment by jasonblais** [comment]
We also had forum posts on deprecations (except the thumbnail one).

Maybe we should link to those in the release announce for community feedback whenever we mention upcoming and current deprecations.

**Comment by it33** [comment]
Closing and moving discussion to Platform Meeting

**Pull request closed without merging**
