### PR TITLE
Update index.rst

### PR DESCRIPTION
**Pull request by james-mm**
Include new file implementation_plan.md (in conjunction with pull request to add this file to General Overview page: https://github.com/mattermost/docs/pull/1783

### CODE REVIEW

**Comment by jasonblais** [comment]
@james-mm Thoughts on whether this belongs to the Admin's guide?

**Comment by james-mm** [comment]
@jasonblais Good idea, we can add it as the first section in this link (https://docs.mattermost.com/guides/administrator.html), before the "Installing Mattermost" section

**Comment by jasonblais** [comment]
@james-mm Yeah, I think that looks like a good place.

**Comment by james-mm** [comment]
This request can be closed since we will be adding this doc to the Admin guide section instead.

**Pull request closed without merging**
