### PR TITLE
Add keyboard-shortcuts.rst

### PR DESCRIPTION
**Pull request by jasonblais**
Add documentation for keyboard shorcuts

### CODE REVIEW

**Comment by jasonblais** [comment]
@esethna @lfbrock Please review when you have a chance

**Comment by esethna** [comment]
Looks good @jasonblais. @lfbrock any comments?

One note, I think the table for Browser Built-in commands might be malformated? When I preview the file I just see the heading:
image

FYI, this is a good website for verifying RST formatting: http://rst.ninjs.org/

image

**Comment by lfbrock** [comment]
Looks good, only thing would be "LHS" might not be clear to all people, might want to use left hand sidebar instead

**Comment by jasonblais** [comment]
Thanks, updated

**Pull request merged**
