### PR TITLE
DOC-7539: Manage channel bookmarks page needs animated GIFs for mobile app workflows

### LINKED ISSUE #7539: Manage channel bookmarks page needs animated GIFs for mobile app workflows
## Context

To help visual learners learn how to perform tasks using the Mattermost mobile app, add visuals and short animated GIFs on the [Manage channel bookmarks](https://docs.mattermost.com/collaborate/manage-channel-bookmarks.html) page.

## Docs Request

- Add/update appropriate visuals/GIFs for all the steps in the `Add a bookmark` section under the mobile app tab.
- Add appropriate visuals/GIFs for all the steps in the `Edit bookmarks` section under the mobile app tab.
- Add appropriate visuals/GIFs for all the steps in the `Share bookmarks` section under the mobile app tab.
- Add appropriate visuals/GIFs for all the steps in the `Copy bookmark links` section under the mobile app tab.
- Add appropriate visuals/GIFs for all the steps in the `Delete bookmarks` section under the mobile app tab.

## Additional Notes

- Use the latest Mattermost mobile app and the standard Mattermost Denim theme to capture all workflows.
- Avoid drawing lines, arrows, boxes, or callouts on images.
- Don't forget to include ALT Text descriptions for all new image assets.
- Use existing docs pages with images as a starting point for code guidance. The Docs team can help provide RST syntax support for publication.
- Save static image files in PNG format within the docs repository's `/images` directory.

# QA Validation Criteria

In a generated docs preview:
- Visiting the docs page results in appropriate new mobile-specific screenshots in each subsection from the **Mobile** tab.

### PR DESCRIPTION
**Pull request by Rutam21**
### Summary

This PR adds visual workflows for the Mattermost mobile app tab on the [Manage channel bookmarks](https://docs.mattermost.com/collaborate/manage-channel-bookmarks.html) page.

### Ticket Link

Fixes #7539 

- [x] This PR follows Mattermost Contributing Guidelines.
- [x] The changes are tested in a local docs build.

### CODE REVIEW

**Comment by Rutam21** [comment]
@cwarnermm Please review and suggest changes, if any. Thanks.

@lindy65 Please add this to my queue for QA Testing, if needed. Thank you.

**Comment by lindy65** [comment]
Assigned you for testing @Rutam21 👍

**Comment by cwarnermm** [comment]
@Rutam21 - Would you be able to crop the mobile images in step 4 where there's considerable empty whitespace? Here's an example:
Screenshot 2024-11-05 at 8 57 50 AM

Really loving the animated captures!

**Comment by Rutam21** [comment]
Sure, consider it done. I will push a new commit for that. And, thanks. I thought GIFs would serve the purpose better.

**Comment by Rutam21** [comment]
@cwarnermm I have added the cropped images.

**Review by cwarnermm — APPROVED** [review]
Thanks, @Rutam21!

**Pull request merged**
