### PR TITLE
Update compliance-export.rst

### PR DESCRIPTION
**Pull request by justinegeffen**
Updated documentation to include content about deleted messages/files as per: https://github.com/mattermost/mattermost-server/pull/12957.

### CODE REVIEW

**Comment by amyblais** [comment]
@justinegeffen You can submit any 5.18 PRs to the ``5.18 documentation`` branch.

**Comment by catalintomai** [comment]
@justinegeffen, @thefactremains - We have three compliance export methods: CSV, Actiance and GlobalRelay. FWIK, we recently added message and file deletion support to CSV and Actiance, and GlobalRelay had file deletion support. I don't see message deletion support for GlobalRelay though (I couldn't find any ticket for it and I don't see it in the code), so maybe it should be mentioned in the docs.

**Comment by thefactremains** [comment]
ok, agreed.

I confirmed with @justinegeffen that she will take a look tomorrow morning her time.

**Comment by justinegeffen** [comment]
Thanks, @catalintomai. I've edited the content to reflect that.

**Pull request merged**
