### PR TITLE
Replace some integrations content with links to new developer docs site

### PR DESCRIPTION
**Pull request by jasonblais**

### CODE REVIEW

**Comment by amyblais** [comment]
These 2 links don't work in `webhooks-incoming.rst`: [this](https://github.com/mattermost/docs/blob/745f9e4fd6cafeb520310fe3601f88f82293b7da/source/developer/about.mattermost.com/default-plugins) and [this](https://github.com/mattermost/docs/blob/e097c8758da64f24229a19733492429b8c161907/source/developer/webhooks-incoming#translate-slacks-data-format-to-mattermost)

**Comment by amyblais** [comment]
@jasonblais not sure if you or dev is best to fix these links:

These 2 links don't work in `webhooks-incoming.rst`: [this](https://github.com/mattermost/docs/blob/745f9e4fd6cafeb520310fe3601f88f82293b7da/source/developer/about.mattermost.com/default-plugins) for "plugins" and [this](https://github.com/mattermost/docs/blob/e097c8758da64f24229a19733492429b8c161907/source/developer/webhooks-incoming#translate-slacks-data-format-to-mattermost) for "automatically translates the Slack's proprietary JSON response format".

These 3 links don't work in `webhooks-outgoing.rst` and `slash-commands.rst`: "plugins", "Mattermost APIs" and "automatically translates the Slack's proprietary JSON response format".

**Comment by jasonblais** [comment]
@amyblais Should be fixed now

**Comment by jwilander** [comment]
We should also wait to merge this until https://github.com/mattermost/mattermost-developer-documentation/pull/103 goes in

**Comment by jasonblais** [comment]
Added the notes @jwilander

**Comment by jasonblais** [comment]
Updated Slack compatibility section of each doc

image

**Pull request merged**
