### PR TITLE
WIP: GH 5951 - Site Configuration Settings

### PR DESCRIPTION
**Pull request by matthew-src**
#### Summary

This PR updates the Site Configuration Settings documentation to the new table-based format, as well as some of the descriptions of the settings.

#### Ticket Link

Partially fixes https://github.com/mattermost/docs/issues/5951 (this issue anticipates multiple PRs for each page to be updated)

### CODE REVIEW

**Comment by matthew-src** [comment]
As of the current commit, only the Customization section of the Site Configuration Settings page is close to being done.

**Comment by cwarnermm** [comment]
Thanks, @matthew-src! I've added a label to this PR so that we can see how your code renders on the page. 

Feel free to click on the **preview environment** link above in this PR to access the preview environment any time. The preview is helpful for identifying small formatting issues, malformed links, and troubleshooting table formatting issues.

I'll regenerate new previews each time you commit changes.

**Comment by cwarnermm** [comment]
Hi @matthew-src! Here's some initial feedback:

- Please convert the clickable URL to a default ``code formatted text`` value
Screen Shot 2022-10-31 at 10 27 13 AM

- Please format legacy release details, like v5.17-specific details as a note in a new row. I suggest this because it breaks up the text in column and calls out the details more clearly for those who are looking for them
Screen Shot 2022-10-31 at 10 26 58 AM

- example of what a broken/malformed link looks like in preview
Screen Shot 2022-10-31 at 10 26 31 AM

- Please specify the input type next to the default and max length
Screen Shot 2022-10-31 at 10 25 51 AM

**Comment by matthew-src** [comment]
Thank you for the feedback. I think I addressed all of those issues. I started using the RST note directive for note rows below the description of the setting. What do you think of that?

**Comment by cwarnermm** [comment]
@matthew-src - Using the RST note directive in tables is a good choice with one word of caution: the note directive can override the width of the table column in cases where you may prefer the column to be narrower. That's why you'll see that I avoided doing the very same on other config setting pages; I encountered enough cases of the note controlling cell width that I reverted to plain text notes.

**Comment by cwarnermm** [comment]
@matthew-src - I've re-generated a new preview for us.

**Comment by matthew-src** [comment]
> @matthew-src - Using the RST note directive in tables is a good choice with one word of caution: the note directive can override the width of the table column in cases where you may prefer the column to be narrower.

Understood.

> @matthew-src - I've re-generated a new preview for us. You're doing a GREAT job with this PR!

Thank you!

**Comment by matthew-src** [comment]
All of the sections have been converted to the table format. I am going to proofread the whole page once more tomorrow or Monday.

**Comment by cwarnermm** [comment]
@matthew-src - I've generated a new preview for us.

**Comment by matthew-src** [comment]
Hi @cwarnermm, 

Thank you, I ended up making a number of tweaks as part of reviewing the whole page today. I will not make any more changes at this point until someone has a chance to review it. Thank you again!

**Comment by cwarnermm** [comment]
@matthew-src - This is an outstanding effort - thank you so much! Seriously well done! I'm impressed that you went above and beyond to add the plan and deployment badges too.

Next steps for this PR would include a technical review to ensure that the content in its new format is accurate and complete. Once that review is complete, we can merge this PR into production. 

Then I'd update the ticket driving this effort to note that the Site Configuration section is now complete, and contributors should choose a different section to work on.

**Comment by cwarnermm** [comment]
Thanks, @matthew-src! I've started conversations with our Engineering teams to confirm expected behaviour where contradictions were present in the documentation.

**Comment by cwarnermm** [comment]
@matthew-src - I'm ready to merge this PR into our codebase. Before I do, can you revert the ``.gitignore`` change in this PR, please? Thanks!

**Comment by matthew-src** [comment]
> @matthew-src - I'm ready to merge this PR into our codebase. Before I do, can you revert the `.gitignore` change in this PR, please? Thanks!

@cwarnermm - All set, thank you!

**Review by cwarnermm — APPROVED** [review]
You've done a fantastic job with this PR, @matthew-src! Thank you so much!

**Pull request merged**
