### PR TITLE
Upgrade Mattermost Server updates

### PR DESCRIPTION
**Pull request by cwarnermm**

### CODE REVIEW

**Comment by cwarnermm** [comment]
@coltoneshaw - This documentation update request has been submitted by a customer via our Customer Success Team. Can you please review this proposed update for technical accuracy?

**Review by coltoneshaw — APPROVED** [review]
Looks good on my end. It does appear that you're already in the `/opt` directory anyways based on how step 8 is structured.

**Comment by cpanato** [comment]
@phpfs can you please rebase your PR with the last main branch? thanks!!

**Pull request merged**
