### PR TITLE
Add sphinx-sitemap extension

### PR DESCRIPTION
**Pull request by jdillard**
This adds a sphinx extension that creates a sitemap.xml at https://docs.mattermost.com/sitemap.xml to improve SEO etc and help people find the information they need.

### CODE REVIEW

**Comment by jdillard** [comment]
oops, I'm on the list now.

**Comment by grundleborg** [comment]
@crspeller should this have PM review at all, or are you just happy to go ahead with merging it?

**Comment by jasonblais** [comment]
Thank you @jdillard for the contribution! Would you happen to have a screenshot of how this sitemap appears on docs.mattermost.com once merged?

**Comment by jdillard** [comment]
It just adds a **sitemap.xml** file to **build/html** that looks like (a longer version of):
```
<?xml version="1.0" encoding="utf-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>https://docs.mattermost.com/administration/announcement-banner.html</loc>
  </url>
  <url>
    <loc>https://docs.mattermost.com/administration/backup.html</loc>
  </url>
  <url>
    <loc>https://docs.mattermost.com/administration/branding.html</loc>
  </url>
  <url>
    <loc>https://docs.mattermost.com/administration/bulk-export.html</loc>
  </url>
</urlset>
```

It also adds a line to the output when you run `make html` that says:
```
sitemap.xml was generated for URL https://docs.mattermost.com/ in /local/path/to/docs/build/html/sitemap.xml
```
The **sitemap.xml** should get deployed with all the other files and end up at https://docs.mattermost.com/sitemap.xml. Once live, hand that link to your webmaster to put in Google's Webmaster Tools and it is basically a coupon for free Google Juice.

**Comment by jasonblais** [comment]
I also forgot to reply to

> If the webmaster is MIA (as they oft do) you can also create a **robots.txt** file that links to the sitemap: https://github.com/jdillard/sphinx-sitemap#getting-the-most-out-of-the-sitemap

> If you would like I can add that change to the PR.

I'll touch base with our marketing team first, but I'll let you know if this makes sense to add as well 👍

**Pull request merged**
