### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Sumindar**
Added for completion of sentence

### CODE REVIEW

**Comment by Sumindar** [comment]
hi can you please explain about one of the checks failing.thanks

**Review by jasonblais — APPROVED** [review]
Thanks @Sumindar! 

Don't worry about the failed check, it's related to our preview environment (cc @justinegeffen FYI)

**Comment by jasonblais** [comment]
@Sumindar Thanks for the contribution :)

**Comment by Sumindar** [comment]
@jasonblais thanks a lot

**Pull request merged**
