### PR TITLE
Gh 10800 convert bot account to user account

### PR DESCRIPTION
**Pull request by aaronrothschild**
@amyblais Is this the PR that needed to get done from https://github.com/mattermost/docs/pull/2928#issuecomment-522555155

### CODE REVIEW

**Comment by amyblais** [comment]
Yes but there's lot of extra commits in here.

**Comment by aaronrothschild** [comment]
@amyblais I'm confused, where did all these commits come from?  How do I clean this up?  Should I just remove my commits and put them into a separate PR?

**Comment by amyblais** [comment]
@aaronrothschild I don't know, I'm guessing they might have come from the changes you committed directly to the v5.14 branch last release. Those have been merged to master. Maybe you can open a new PR for https://github.com/mattermost/docs/pull/2928#issuecomment-522555155 from a different branch than ``GH-10800-convert-bot-account-to-user-account``

**Comment by aaronrothschild** [comment]
Done. Submitted a new PR for the GH Robots.  https://github.com/mattermost/docs/pull/2977 . Sorry for the confusion.

**Pull request closed without merging**
