### PR TITLE
Update sso-saml.rst

### PR DESCRIPTION
**Pull request by urvesh20**
Added miniOrange as custom IDP

### CODE REVIEW

**Review by justinegeffen — APPROVED** [review]

**Comment by justinegeffen** [comment]
Thanks, @urvesh20! We appreciate your contribution. :) When you have a moment, please sign the CLA and I can merge this PR. :)

**Comment by cwarnermm** [comment]
Gentle reminder on this, @urvesh20. We can merge your PR once you've signed the CLA.

**Comment by justinegeffen** [comment]
Hi @urvesh20! If you have a moment to sign the CLA we can go ahead and merge this PR. :)

**Comment by urvesh20** [comment]
@justinegeffen Hi, I have signed the Mattermost CLA. Please merge the PR. Thanks, Urvesh

**Pull request merged**
