### PR TITLE
Update cloud-billing.rst

### PR DESCRIPTION
**Pull request by wiersgallak**
Updated for deletion process of workspace after in arrears for 90  days.

### CODE REVIEW

**Review by cwarnermm — APPROVED** [review]
Looks great! Thanks!

**Review by coltoneshaw — COMMENTED** [review]
Looks good! Should we add that the admin gets an email on the 90th day? Additionally, what next steps should someone who has had their workspace terminated take if they want another workspace? I foresee this being a question.

Thanks!

**Comment by wiersgallak** [comment]
@coltoneshaw updated with your suggestions.  Thanks!!

**Comment by coltoneshaw** [comment]
@wiersgallak - Thanks, that'll make the process a lot easier!

**Review by coltoneshaw — APPROVED** [review]

**Pull request merged**
