### PR TITLE
webhook.rst

### PR DESCRIPTION
**Pull request by icelander**
I implemented webhook with Mattermost and thought having some tips would be useful

### CODE REVIEW

**Comment by lindy65** [comment]
Thanks for the PR @icelander!

We'll get it through the review process soonest...

**Comment by jasonblais** [comment]
@icelander This is great. 

We currently have an [integration's guide here](https://docs.mattermost.com/guides/integration.html), and wondering if this would be like an overview/intro doc, or if it would be integrated within the webhook documentation.

On the side, we're also working on a developers.mattermost.com documentation site for server contributions, integrations and plugins. Your doc might be a good start as a "Getting Started" doc for integrations ([proposed site map for integrations is here](https://github.com/mattermost/mattermost-developer-documentation/issues/15)).

Wondering your thoughts, as an integrations developer?

**Comment by icelander** [comment]
@jasonblais Webhooks is a third-party application so I think putting it in the integrations guide as an overview/intro on how to integrate with it would be the best spot. I agree that it would be a great doc for Getting Started because Webhooks is easy to set up and can hook into existing scripts easily.

**Comment by jasonblais** [comment]
Great, that makes sense @icelander. 

@jwilander Maybe you can help with dev review and share thoughts, if any?

PS: Made some very minor formatting tweaks https://github.com/mattermost/docs/pull/1785/commits/3d7e3fe563aeb4614ab3e6fdc8e8d7efa066fb59

**Comment by jasonblais** [comment]
Thanks all! I've included in the integrations guide https://github.com/mattermost/docs/blob/master/source/guides/integration.rst

**Pull request merged**
