### PR TITLE
Increase minimum go version in Ubuntu instructions

### PR DESCRIPTION
**Pull request by grundleborg**
Increase from 1.5.1 to 1.6 to be consistent with MacOS instructions, as
platform no longer works with go 1.5.

Now I've done this, I'm wondering if it would be even better just to say the "latest" version, or to declare the versions needed at the top of the document before the platform/distro specific instructions begin?

### CODE REVIEW

**Comment by esethna** [comment]
@grundleborg would we be okay to say the following?

```
4. Download the lastest version of Go from http://golang.org/dl/
  - Go 1.5 and earlier is not supported.
```

**Comment by grundleborg** [comment]
That would probably be the ideal thing to do, yes. But I can't say for sure whether there is a reason that elsewhere in the docs 1.6 is recommended (see the macOS section on that page), or whether that was just the latest at the time. You'd probably need to check with someone who knows the project better than me to be sure :)

**Comment by esethna** [comment]
It's likely that the doc was just not updated. Adding @jwilander to confirm:

1. Can we just say "latest version" throughout the doc?
2. Is Go 1.5 and earlier no longer supported throughout the doc?

**Comment by jwilander** [comment]
1. Let's be specific with a version because we usually like to be a major version behind and that also lets us test the newer Go versions before switching to them.
2. I believe vendoring was introduced in 1.6, so yes we would no longer support 1.5

**Comment by jwilander** [comment]
Throwing it to PM review so @esethna can ask for changes if needed

**Comment by esethna** [comment]
Thanks JW. I've added a note on not supporting Go 1.5.

**Pull request merged**
