### PR TITLE
Updating Zoom setup instructions

### PR DESCRIPTION
**Pull request by it33**
Zoom has private cloud deployment options, not only "on-prem", adjusting help text for this. 

Also, propose opening a ticket to update the help text for Zoom API URL to `If you're using a self-hosted private cloud or on-premise Zoom server, enter the Zoom API URL for the Zoom server, for example https://api.yourzoom.com/v2. Leave blank if you're using Zoom's vendor-hosted SaaS service.`

Similarly for Zoom URL. 

Also, it looks like in Mattermost 5.0 the System Console no longer shows Beta tag for this plugin, so propose removing Beta from docs. 

Also, adding upgraded screenshot of integration: 

image

### CODE REVIEW

**Comment by it33** [comment]
@jasonblais I merged this PR as I want to talk to someone about integrating their voice/video/screenshare solution with ours and I needed a reference, can you figure out how to review this PR to approve it retroactively, or make changes?

**Comment by jasonblais** [comment]
I'll talk to @amyblais about reviewing the PR. This is a pretty old PR from last year so the formatting might have been missed then..thanks for fixing those as well.

All plugins are still Beta as noted by the section heading (see attached below). Let me know if this is not obvious to you and we can look at making this more obvious
image

**Comment by jasonblais** [comment]
@it33 I'll talk to @amyblais about reviewing the PR. Looks like this is a doc from last year so I probably missed the formatting..thanks for fixing those.

All plugins are still Beta as noted by the section heading (see attached below). Let me know if this is not obvious to you and we can look at making this more obvious
image

**Comment by amyblais** [comment]
@it33 Thank you for helping with editing this doc, I agree with the changes. I reviewed this PR and it looks good. 

I have opened a Jira ticket to adjust the help text in System Console based on your proposal: [MM-11135](https://mattermost.atlassian.net/browse/MM-11135).

After that ticket is completed, I'll open a PR to add [a new screenshot](https://github.com/mattermost/docs/issues/2129) based on your proposal. I'll add to that same PR the text formatting tweaks that you proposed in [this Issue](https://github.com/mattermost/docs/issues/2130).

I have a step in my doc review checklist to go through text formatting guidelines for all doc PRs.

**Pull request merged**
