### PR TITLE
GH-5915 (Open external links in new tab)

### LINKED ISSUE #5915: Help Wanted: Open all external links in a new browser tab
**Problem space**
Currently, links to external sites from the Mattermost product documentation take the visitor away from [docs.mattermost.com](http://docs.mattermost.com/).

**Target audience**
All users

**Goal**
All external links across the product documentation site open in a new browser tab, rather than the current tab.

**Delivery expectations**
- 1 PR with all proposed changes
- Leave all links to other pages of the product documentation site as-is.
- Links to the Mattermost Developer or API documentation sites count as an external site link and should be updated.
- Comment in the PR to request a generated preview of your work. The Docs team will add the appropriate labels to your PR.

**Tech needed**
- HTML, 
- RST, MD formats
- Sphinx

**Affected repository**
mattermost/docs

**Where to get help**
Join the Mattermost Docs team on the Mattermost Community Server in the [~Documentation Working Group channel](https://community.mattermost.com/core/channels/dwg-documentation-working-group) to discuss this ticket, or feel free to comment in this docs ticket.

### PR DESCRIPTION
**Pull request by chessmadridista**
#### Summary

This pull request helps the user open all internal links in the same tab and all the external links in a new tab.

A new `open-external-links-in-new-tab.js` file has been created. When the dom gets loaded, the target=_blank attribute is applied to all the external links. The JS file has been added to `conf.py` as well so that the application is aware of that script.

A generated preview of my work is requested (this step is mentioned in the [issue](https://github.com/mattermost/docs/issues/5915#:~:text=Comment%20in%20the%20PR%20to%20request%20a%20generated%20preview%20of%20your%20work.%20The%20Docs%20team%20will%20add%20the%20appropriate%20labels%20to%20your%20PR.)).

#### Ticket Link

Fixes #5915.

### CODE REVIEW

**Comment by fmartingr** [comment]
Hey @chessmadridista, thank you for your contribution! 

I'm wondering why did you choose to use javascript for this. Is this not doable using a Sphinx extension? I'd rather have the HTML generated with this than adding javascript modifications if possible.

**Comment by cwarnermm** [comment]
@chessmadridista - I agree with @fmartingr that it's worth exploring whether our HTML generator, Sphinx, can do this for us, rather than modifying the DOM via scripting. Would you be open to looking into Sphinx capabilities in this area? We're currently using Sphinx 7.2.6.

**Comment by chessmadridista** [comment]
Hi @fmartingr and @cwarnermm, thank you for the feedback! 

I was not aware of that solution and the first solution that came to my mind was to manipulate the DOM via JavaScript. 

I'll look in the documentation of Sphinx and will make the necessary modifications.

**Comment by chessmadridista** [comment]
@fmartingr and @cwarnermm

Also, I am contributing to open source for the first time so I am not sure about the process after review. 

Should I delete the branch and start afresh with a new branch or should I commit the removal of these JavaScript code snippets and then commit the Sphinx method in this branch or should I do something else? What's the best practice?

**Comment by fmartingr** [comment]
> @fmartingr and @cwarnermm
> 
> Also, I am contributing to open source for the first time so I am not sure about the process after review.
> 
> Should I delete the branch and start afresh with a new branch or should I commit the removal of these JavaScript code snippets and then commit the Sphinx method in this branch or should I do something else? What's the best practice?

For me it's fine for you to continue here if needed so we can keep the conversation in one place; commits can be squashed later on merge :)

**Comment by cwarnermm** [comment]
Closing due to inactivity.

**Comment by chessmadridista** [comment]
Hi @fmartingr, @cwarnermm and @amyblais, [there is an issue in the Sphinx repo](https://github.com/sphinx-doc/sphinx/issues/1634) regarding this functionality. It seems that the only way to open external links is to use some form of JS.

Additionally, please take a look at this answer on StackOverflow. They are also saying that there is no inbuilt feature in Sphinx to achieve what we want.

Please let me know about the next course of action.

**Pull request closed without merging**
