### PR TITLE
Update slash-commands.rst

### PR DESCRIPTION
**Pull request by Sayanta66**
Updated the links ...Similar to #4808

### CODE REVIEW

**Comment by justinegeffen** [comment]
Hi @Sayanta66 . This content has been moved to: https://developers.mattermost.com/integrate/admin-guide/admin-slash-commands/ but these changes look like they'd still be valid. Would you be open to updating the content in the new location? :)

**Comment by Sayanta66** [comment]
Anything that will properly help the doc will be fine. If possible merge this PR, then update that specific link

**Comment by justinegeffen** [comment]
Thanks, @Sayanta66! This PR won't be merged, because this content is no longer used - it's been moved to a new site and this particular page will be archived shortly. The update you've made could be applied to this content in the new place, and if you're open to updating it that would be great. :) The editing process is pretty much the same as this one - let me know if you get stuck!

**Comment by Sayanta66** [comment]
Okay, So it's in a separate repository right? @justinegeffen

**Comment by justinegeffen** [comment]
That's correct - you can edit the document by opening the link provided. Then click "Edit on GitHub" in the top-right corner. Make the changes, and follow the same process to create a PR as you did for this PR. :)

**Pull request closed without merging**
