### PR TITLE
Remove the term "mattermoster"

### PR DESCRIPTION
**Pull request by jwilander**
The term "mattermoster" seemed to get introduced here without much discussion? The only discussion I've seen about this term is that most people don't like it. I think introducing this term is a major change in company culture that a lot of people don't agree with or at least weren't consulted about.

### CODE REVIEW

**Comment by jwilander** [comment]
Thanks @enahum, removed the other usages and a distinction created between remote and non-remote employees

**Comment by it33** [comment]
>The term "mattermoster" seemed to get introduced here without much discussion? The only discussion I've seen about this term is that most people don't like it. I think introducing this term is a major change in company culture that a lot of people don't agree with or at least weren't consulted about.

The work-in-progress PR for adding "Mattermoster" was shared with the company in January. The text introducing "Mattermoster" was posted in the announcements channel, and multiple people in this discussion added a Thumbs-Up reaction.

Here's a link to the post in the announcement: https://pre-release.mattermost.com/private-core/pl/gexsidnaof8pinha3ia9whgspa

Here's a screenshot: 

image

The posting in the announcements channel was followed by a company-wide presentation and discussion by the founders to the company, after the draft PR was reviewed by all department heads, to define what it meant to belong to our culture, where we work out of our online headquarters (Mattermost server) in an open source, remote-first, communities-centered company. The talk was streamed live and also recorded live by a video crew. 

I don't remember all the Q&A from the session, I do remember Lev asking about how to think about growth opportunities and my answer was something like "growth opportunities are a multi-variate optimization, we have an equation that involves downloads, conversion rates, average revenue per user, average number of users and other factors, and doubling three to four of the variables increases our growth rate 10x" 

Hopefully that jogs some memories? 

Also, some points from the discussion that I hope people might remember now that we're talking about it: 

- We are an open source, remote-first, [communities-centered](https://docs.mattermost.com/process/community-overview.html) company
- Courtesy is the principle by which remote-first works
- Mattermost is our headquarters, and it's our home. It's on our phones and in our laptops, we are never remote from our home. We are not "Remoters" we are "Mattermosters". 

What I'll add is I think that being a Googler, a Herokai, a Treker, or a Microsoftie is to belong to something. I don't think it ever sounds right at the beginning, but what makes it work--like the ABC and XYZ team names--is that when we decide a name is going to stand for something, it does, and it endures, and it elevates. We'd miss it when it's gone. 

I can't promise you that everything at Mattermost is going to sound cool. What I can say is that I want people to be empowered to do the best work of their careers. I want people to look back and their time here, and be proud of what they built.

**Comment by jwilander** [comment]
It seems I was mistaken and that the term wasn't added without consultation. In that original pull request I seemed to have missed the term "Mattermoster" being introduced, among all the other changes. I take total responsibility for that and admit I could have approached starting this discussion in a better manner.

The specific concern here is that choosing the word of how we identify ourselves seems very important. Working at Mattermost and being a part of our communities (all of them) means a lot to me and to the other people that work here. When I think about how I identify with being a part of Mattermost, it's important to me that any label or term we apply to that resonates with me and the rest of the people (staff and otherwise) who make up this company and project. I don't feel that "Mattermoster" resonates with me and I think a lot of other people agree to the point that there should be some more discussion around it. I've seen other terms thrown around recently, such as "Matternaut", but I'm also entirely convinced that we need some special/cutsey term to describe ourselves. I very much identify with being someone who works at Mattermost, and "Mattermost staff" means more than just a contractual obligation to me. It means I'm someone who upholds and believes in our core values.

The main concern that dovetails out of all this is that I feel, despite the company announcement in DR and the earlier pull request, like we didn't actually discuss this change a significant amount before it was actually merged. Maybe I'm wrong, and there was enough, but the fact that many people don't remember it going in seems to back up the idea that it wasn't talked about enough. What I would really like is for us to come up with a process around these changes that affect culture that better informs and gathers feedback so we can make better decisions that will help us prosper and continue the growth of are awesome communities and company.

**Comment by hanzei** [comment]
One point as a community member that I want to add is that "Mattermoster" as a term for staff members adds a barrier between community members and staff members. Why shouldn't community members see themself as "Mattermoster"?

**Comment by hanzei** [comment]
Moved the discussion over to https://gitlab.com/mattermost/proposals/issues/28

**Comment by amyblais** [comment]
Closing for now and this can be re-opened once the discussion is complete.

**Comment by jwilander** [comment]
Closing as this discussion is stale

**Pull request closed without merging**
