### PR TITLE
Note that themes per team is for v3.3

### PR DESCRIPTION
**Pull request by lfbrock**

### CODE REVIEW

**Comment by jasonblais** [comment]
+1

**Comment by esethna** [comment]
Do we want to open a new branch for 3.3 instead of having this in master?

**Comment by lfbrock** [comment]
I think it's easier to just put the note in master (since themes is already incorrectly there), and then we can remove the available in v3.3 part in the v3.3 branch

**Comment by esethna** [comment]
Okay, that's fine with me. +1

**Pull request merged**
