### PR TITLE
Fix Calls FAQ section

### PR DESCRIPTION
**Pull request by streamer45**
#### Summary

Somehow the use of sub-subsections (`^^^^^^`) prevented the questions from getting displayed. 

#### Screenshots

image

image

### CODE REVIEW

**Comment by cwarnermm** [comment]
@streamer45 - Isn't RST format FUN!?!? :) When formatting headings, all headings need to follow the same approach across the doc set, otherwise, headings disappear. 

Titles are denoted with ``====``
h1's are denoted with ``----``
h2's are denoted with ``~~~~``
h3's are denoted with ``^^^^``

If levels are skipped, the docs aren't parsed as intended.

**Comment by streamer45** [comment]
Oh wow, thanks @cwarnermm :raised_hands: I definitely experienced that first hand :D

**Comment by justinegeffen** [comment]
Argh! Sorry all, I was a bit enthusiastic and merged this. LMK if I can revise/redo anything.

**Comment by streamer45** [comment]
@justinegeffen All good, just needed an approval really :)

**Pull request merged**
