### PR TITLE
Added FAQ on encryption at rest

### PR DESCRIPTION
**Pull request by sadohert**
Incorporated content from @jasonblais https://github.com/mattermost/docs/pull/2491 and expanded.

@jasonblais, @crspeller - Please let me know what you think or if I have anything wrong.  Maybe too long?

### CODE REVIEW

**Comment by jasonblais** [comment]
Thanks @sadohert! Discussed with Chris, there are some technical updates the engineering team would like to make, so we've created a ticket for them to do so. I'll apply a WIP label for now while those updates are being made, and we can then queue for a review.

**Comment by sadohert** [comment]
@jasonblais - Do you have a sense for timing on this?  Was hoping to send to a customer as a follow-up to their E2E questions.

**Comment by jasonblais** [comment]
@sadohert It's scheduled for security team's triage on Thursday. Apart from being for a customer (which I've communicated to the team), is this time-sensitive?

**Comment by sadohert** [comment]
Yes, I've wanted to provide a comprehensive resposne to the customer for
over a month but wanted to create this artifact first (for re-usability).
If you think the reviews still need past this week I'll take a form of what
I've produced and share it now.

**Comment by jasonblais** [comment]
@sadohert was the chat with Chris helpful in terms of next steps?

**Comment by sadohert** [comment]
Hey @jasonblais  - Yes it was.  I have some notes to implement changes on my original PR and I will re-submit.  Will try to get this done before Monday.

**Comment by crspeller** [comment]
@sadohert re-open when ready.

**Pull request closed without merging**
