### PR TITLE
adds favicon.ico to root path (#6173)

### PR DESCRIPTION
**Pull request by worldworm**
#### Summary
This will add the favicon.ico to root path due to some browsers prerendering the icon before parsing the index.html and that not knowing, that it is not located in the root project path.

#### Ticket Link
Fixes https://github.com/mattermost/docs/issues/6173

### CODE REVIEW

**Comment by cwarnermm** [comment]
Thank you, @worldworm, for addressing one of our help wanted tickets! Next steps for this PR include a technical review.

**Comment by azigler** [comment]
@cwarnermm Can we create a preview for this one?

**Review by azigler — APPROVED** [review]
Looks good @worldworm! Thanks for tackling this and congratulations on crushing your first Mattermost issue+PR! 💪 We hope you stick around and continue to make helpful contributions like this one. See you around, and [don't be a stranger](https://community.mattermost.com)! 🚀 

cc @cwarnermm

**Pull request merged**
