### PR TITLE
Image name removed

### LINKED ISSUE #3205: Docs with `md` file formatting show the file name for images below or beside the image
This is an issue with any file with ``md`` file format.

Example docs with this issue:
https://docs.mattermost.com/deployment/sso-google.html
https://docs.mattermost.com/deployment/sso-office.html

Found while reviewing: https://github.com/mattermost/docs/pull/2622

file-name

### PR DESCRIPTION
**Pull request by trishitapingolia**
Image names removed
Fixed #3205

### CODE REVIEW

**Comment by justinegeffen** [comment]
Thanks, @trishitapingolia! This is a really great PR, and the doc looks much better now. :)

**Review by justinegeffen — APPROVED** [review]

**Comment by justinegeffen** [comment]
Apologies, I just saw you'd been working with @amyblais on this and I jumped in. It all looks good to me, @trishitapingolia, so if you'd like to take on the other pages that would be awesome. :)

**Comment by trishitapingolia** [comment]
@justinegeffen I have updated one more page from the docs.
can you please review it? Also let me know if there are more pages having the same issue!

**Comment by justinegeffen** [comment]
Thank you, @trishitapingolia! I have reviewed your PR - much appreciated, it's so helpful. 

I think there are some other docs with the same issue - I'll create a new issue for them and tag you in it, if you're open to that?

**Comment by trishitapingolia** [comment]
@justinegeffen yeah you can create an issue and tag me.

**Pull request merged**
