### PR TITLE
Enabling sphinx options menu

### PR DESCRIPTION
**Pull request by shieldsjared**
Added a versions.html template which renders the options flyout menu on the side navbar.  On the options flyout, included a 'Report a Problem' link and an 'Edit on GitHub' link. Also added (what I believe is) a missing border to the right of the search text input box, missing due to the fixed positioning on the box.  Updated the options reveal to be the 'Mattermost Blue' in lieu of the base themes 'black', since the black didnt jive well w/ the rest of the page. mattermost/docs#85

Would like some input on the color of the flyout... Screenshot of the flyout in action:

optionsflyout

### CODE REVIEW

**Comment by esethna** [comment]
Thanks @shieldsjared!! This is awesome, docs is miles beyond where it was before your contributions, much appreciated.

Reviewing I found one bug where the "Edit on Gitbhub" button in the options pane doesn't append the ".md" or ".rst" to the url so it results in a 404 (see screenshot). The "Edit on Github" button on the top right in the header works great.

image

Other than that we are discussing in the UX meeting tomorrow on the color of the options pane. Mattermost blue seems to stand out a lot, we might want a color that is less prominent. I will circle back shortly!

**Comment by shieldsjared** [comment]
Yikes!  I'll see if I can figure that out. Seems like Sphinx puts a lot of information into the available context but I'm still trying to figure it all out. Worst case resolution would be to _not_ show the edit link whenever all variables needed to construct the URL aren't present. I have an idea of what the issue might be though :)

**Comment by esethna** [comment]
Thanks @shieldsjared! We chatted in UX and think that maybe something between the default grey and black would be best. Can we try #333333? Open to other suggestions!

**Comment by shieldsjared** [comment]
I'll post full screenshots before committing :) I should have time between flights tomorrow.

**Comment by shieldsjared** [comment]
@esethna - I fixed the issue where the edit link _sometimes_ did not work as expected (I mirrored the error checking logic baked into the breadcrumbs template provided by the rtd theme).  Also, I updated the options theme to #333333 but then found that it was a such a close match to the body text color being used (#404040), so for consistency I made it #404040 to make it an exact match.  

optionsflyout 2

Also, I snuck in something (I can remove it if required): the border to the right of the search-box is being hidden because of the box-sizing and fixed positioning, so I added a right-border to the necessary element so that the right-border on the LH bar is consistent from top-to-bottom.

**Comment by esethna** [comment]
Much appreciated, the changes look excellent! I will pass on for dev review and then get this merged!

**Comment by enahum** [comment]
+1

**Pull request merged**
