### PR TITLE
MM-18463/MM-19503 Add update_badge notifications to push proxy metrics dashboard

### PR DESCRIPTION
**Pull request by hmhealey**
We're adding a new `update_badge` notification type as part of the Mark as Unread feature, so this is attempting to add it to the metrics.

@jasonblais I've never worked with Grafana before, so I just copied and pasted the section for `clear` notifications to make this. I assume we'd want to give it a different colour at least, so I could use some help finishing this up before it's ready for a proper review.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-18463
https://mattermost.atlassian.net/browse/MM-19503

### CODE REVIEW

**Comment by jasonblais** [comment]
^I meant to add a 'comment', not 'approve',

**Comment by hmhealey** [comment]
Thanks for the feedback, Jason. I've created a separate ticket to track this and make sure it's done correctly since there's more work to be done here than expected. I'll let you know if I need any further help, but I'm likely not going to get to this this week.

**Comment by hmhealey** [comment]
@jasonblais I've updated the dashboard to actually fit in the screen correctly, and I actually tested it this time to ensure it still looks. How is this?
Screen Shot 2019-12-02 at 5 13 34 PM

**Comment by jasonblais** [comment]
@hmhealey Let me know if you have any thoughts on the question above?

**Comment by hmhealey** [comment]
I've updated the titles and description for those 4 metrics to:
- Total Notifications: The number of push notifications sent through the proxy
- Message Notifications: The percentage of push notifications sent that contained new messages
- Clear Notifications: The percentage of push notifications sent to clear a previous notification
- Update Badge Notifications: The percentage of push notifications sent to update the notification count on the app icon

**Pull request merged**
