### PR TITLE
Fix GitLab documentation link

### PR DESCRIPTION
**Pull request by vegerot**
#### Summary

Fix the GitLab link in the documentation. It currently points to an invalid URL.  This commit points it to the correct URL

### CODE REVIEW

**Review by justinegeffen — APPROVED** [review]

**Comment by justinegeffen** [comment]
Thanks for this PR, @vegerot! Really appreciate it. Please let us know once you've signed the CLA so we can merge this. :)

**Comment by vegerot** [comment]
> Thanks for this PR, @vegerot! Really appreciate it. Please let us know once you've signed the CLA so we can merge this. :)

@justinegeffen I can't seem to get /check-cla to work

**Pull request merged**
