### PR TITLE
Sphinx upgrade to prod

### PR DESCRIPTION
**Pull request by justinegeffen**
PR for Sphinx upgrade into prod.

### CODE REVIEW

**Comment by justinegeffen** [comment]
@jasonblais, please could you approve this PR so I can merge master into it? I'll re-add you once that's done.

**Comment by justinegeffen** [comment]
Screen Shot 2021-03-23 at 08 05 27

**Comment by justinegeffen** [comment]
@lawrencejohnson, just an FYI: I am merging the update as-is. The next round of updates will be for analytics with Rudderstack followed by the SEO/metadata fields.

**Review by cwarnermm — COMMENTED** [review]
I have nothing to contribute in terms of a review, but I'm excited to see this PR go through!

**Comment by justinegeffen** [comment]
@jasonblais, @wiersgallak: Thoughts on merging this? Would be good to get it live so we can iterate on it and unblock the SEO team.

**Review by wiersgallak — APPROVED** [review]
No real input to add to the PR, but thanks for the heads up.

**Review by cwarnermm — APPROVED** [review]
Approved! Thank you!

**Comment by justinegeffen** [comment]
Screen Shot 2021-03-25 at 17 49 21

Looks like we have a permissions issue with the staging branch. @metanerd, is this something you'd be able to fix? :)

**Pull request merged**
