### PR TITLE
Update important-upgrade-notes.rst

### PR DESCRIPTION
**Pull request by amyblais**
- Based on discussion in the release channel https://community.mattermost.com/core/pl/zp9ohcfatjfo8youq8mfwba4sh
 - Send to GitLab once reviewed.

### CODE REVIEW

**Review by agnivade — APPROVED** [review]

**Review by jasonblais — COMMENTED** [review]
0/5 - if this impacts upgrading to 6.X and above, I wonder if we'd include it as an upgrade note for 6.0 specifically, and copy-pasting the text in the gist document to the upgrade notes (since it's short).

Thoughts?

EDIT: Helps the information to be in one place, and in a relevant place only impacting one-time upgrade to 6.x.

**Comment by amyblais** [comment]
@agnivade To confirm, the error/issue only affects v6.0+?

**Comment by agnivade** [comment]
Correct. As mentioned in the gist:

> While trying to upgrade to an MM version >= 6.0.x, you might encounter an error of the form:

**Review by cwarnermm — APPROVED** [review]

**Comment by amyblais** [comment]
@jasonblais Let me know if this needs to be added to GitLab docs.

**Comment by jasonblais** [comment]
@amyblais I think it's fine as the GitLab docs link to important upgrade notes https://docs.gitlab.com/ee/integration/mattermost/#upgrading-gitlab-mattermost-to-146

It would be good to respond here that the important upgrade notes have been updated to include the resolution steps mentioned at https://gitlab.com/gitlab-org/omnibus-gitlab/-/issues/6599#note_797502592

**Pull request merged**
