### PR TITLE
Update security.rst

### PR DESCRIPTION
**Pull request by justinegeffen**
Added link to security policies handbook page and minor clean-up.

@jasonblais, no content was changed in this PR hence the editorial review only, but if additional reviewers should be added please feel free to add. :)

Do not merge until https://github.com/mattermost/mattermost-handbook/pull/426 is merged.

### CODE REVIEW

**Review by jasonblais — APPROVED** [review]

**Comment by jasonblais** [comment]
Requesting @wiersgallak's review for blindspots. 

@wiersgallak in summary, we're moving the existing security policies page to our handbook, and linking to it from our Security Overview page. Reasoning is that these refer to internal policies and hence it makes more sense to have it in our handbook. Daniel + Tim is :+1:

**Review by wiersgallak — APPROVED** [review]

**Comment by amyblais** [comment]
@justinegeffen Was https://handbook.mattermost.com/operations/operations/company-policies/security-policies added to the table of contents? The link is currently broken.

**Comment by justinegeffen** [comment]
Thanks @amyblais, I dropped the ball on that. I've submitted a PR for the addition.

**Comment by justinegeffen** [comment]
Fixed.

**Pull request merged**
