### PR TITLE
Delete setup.md and add new Desktop Guides to TOC

### PR DESCRIPTION
**Pull request by jasonblais**
This information is included in https://github.com/mattermost/docs/blob/master/source/help/apps/desktop-guide.rst

and
https://github.com/mattermost/docs/blob/master/source/install/desktop.rst

### CODE REVIEW

**Comment by lfbrock** [comment]
@jasonblais - do you know if there's any links that will break deleting this file?

**Comment by lfbrock** [comment]
+1, spoke to JB and it's an old doc that hasn't been used.

**Comment by esethna** [comment]
I think the entire "Apps" section is missing from the sidebar in docs?

**Comment by jasonblais** [comment]
Is the Android one up to date?

**Comment by esethna** [comment]
Looks like it is pretty bare bones. Maybe just add the desktop docs to the sidebar in this PR?

**Comment by jasonblais** [comment]
Yeah -- I wasn't sure if it looked weird to have Apps > Desktop App as it's only section in the TOC.

I kind of feel we'd need a short section for the iOS and Android apps too to justify adding Apps as it's own TOC.

We could consider adding the Desktop User Guide under "Getting Started" as it's mostly useful when someone sets up the app for the first time.

**Comment by esethna** [comment]
@jasonblais ya I think getting started makes sense for now.

**Comment by jasonblais** [comment]
Updated title of Desktop guides to make the name consistent with other docs in "Getting Started"

[Approved by @lfbrock](https://pre-release.mattermost.com/core/pl/cefw1apj1igxfpnz6q9u7crh7o)

**Comment by esethna** [comment]
Thanks @jasonblais, FYI it's also possible to change the title in the sidebar to make it so it doesn't have to match the documents main heading. See syntax below:

image

**Pull request merged**
