### PR TITLE
Change name from MSTeams Sync > MS Teams Connector

### PR DESCRIPTION
**Pull request by cwarnermm**
Note: Repository name/path & slash commands left as-is to match current code base.

### CODE REVIEW

**Comment by cwarnermm** [comment]
@jasonblais - Would it be safe to update our docs terminology from MS Teams Sync to MS Teams Connector? We had initially held off on applying this change to avoid disrupting a customer deployment.

**Comment by jasonblais** [comment]
@cwarnermm I would confirm with John Lugtu when he's back next week, he'll have the most context

**Comment by cwarnermm** [comment]
@jasonblais - Perfect! Thanks! Once we have an all-clear to proceed with this docs PR, I'll ensure the merge conflicts are resolved. Thanks!

**Comment by cwarnermm** [comment]
Closing in favour of: https://github.com/mattermost/docs/pull/6829

**Pull request closed without merging**
