### PR TITLE
Add Twitter checklist

### PR DESCRIPTION
**Pull request by jasonblais**

### CODE REVIEW

**Comment by amyblais** [comment]
Is this WIP or done?

**Comment by jasonblais** [comment]
@amyblais I think it's good as-is and we can add to the list over time.

**Comment by amyblais** [comment]
We already have a twitter checklist so I just added step no.5: https://docs.mattermost.com/process/marketing-guidelines.html#guidelines-for-twitter-accounts

**Comment by jasonblais** [comment]
Thanks @amyblais, sounds good :+1:

**Pull request merged**
