### PR TITLE
Document how to use message attachments with posts created with API

### PR DESCRIPTION
**Pull request by jwilander**

### CODE REVIEW

**Comment by jwilander** [comment]
I'm 0/5 but I think the goal is to make it easier on the user and having it here is helpful. Feel free to make a PR to the API reference if you think it fits better there

**Comment by JeffSchering** [comment]
Closing because this is API documentation that belongs on https://api.mattermost.com

**Comment by rqc** [comment]
Hi, I don't see a cross-reference to a PR to the api reference repo. Could you provide this?

**Comment by JeffSchering** [comment]
Hi @rqc It's on my to-do list but keeps getting pushed down... would you have time to create a PR for it in the API repo?

**Pull request closed without merging**
