### PR TITLE
Update sysctl settings

### PR DESCRIPTION
**Pull request by agnivade**
#### Summary

This is the updated list of tweaks that we are using for our load test cluster. Just the 2 initial settings are not enough to handle high load.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-21660

### CODE REVIEW

**Comment by justinegeffen** [comment]
@streamer45, following up on this. :)

**Comment by streamer45** [comment]
Yes, just taking my time since I'd like some good testing to be done before we add these to the official documentation.

**Comment by justinegeffen** [comment]
> Yes, just taking my time since I'd like some good testing to be done before we add these to the official documentation.

No worries at all - totally agree. I missed this review request so wanted to follow up at the same time. :) Let me know if I can help with anything. :)

**Comment by justinegeffen** [comment]
Following up on this, @streamer45 - how's the testing going? Should we mark this as a draft in the meantime?

**Comment by justinegeffen** [comment]
That's great news! Thanks for letting me know. :)

**Pull request merged**
