### PR TITLE
Fix Acknowledgement icons in Dark Mode

### PR DESCRIPTION
**Pull request by aamfahim**
#### Summary

Removes CSS class from `|acknowledge-button|` which causes the button to appear red instead of green in dark mode.

Before:
before change

After:
after change

#### Ticket Link

Fixes https://github.com/mattermost/docs/issues/7459

### CODE REVIEW

**Review by cwarnermm — APPROVED** [review]
Thanks, @aamfahim!

**Comment by Rutam21** [comment]
@lindy65 Please assign this issue to me for QA Testing. Thanks.

**Comment by Rutam21** [comment]
### The changes through this PR have been tested in the preview environment and work as expected. 

The CSS for the `Acknowledge` icon has been fixed and is set to **Green** only, in both Light and Dark mode. I've attached a video as a confirmation.

https://github.com/user-attachments/assets/7eb0ec07-ed86-45fe-bd6e-411b0d230b50

cc: @lindy65

**Comment by lindy65** [comment]
Thanks @Rutam21 - counted towards Hacktoberfest!

cc @cwarnermm

**Pull request merged**
