### PR TITLE
Update share-files-in-messages.rst

### PR DESCRIPTION
**Pull request by ayrotideysarkar**

### CODE REVIEW

**Comment by cwarnermm** [comment]
Thank you, @ayrotideysarkar! Great job!

Please move all of the text under "Attachment limits and sizes" through to "Download files" outside of the tabbed content, so that it's visible below the tabbed information. Attachment limits, preview, share, and download applies regardless of the client being used. Only the share functionality steps change on mobile.

**Comment by ayrotideysarkar** [comment]
@cwarnermm  okay i will do it 🙂

**Comment by ayrotideysarkar** [comment]
@cwarnermm  i have made the changes ...
you can check it

**Review by cwarnermm — APPROVED** [review]
Thank you, @ayrotideysarkar! Great job!

**Pull request merged**
