### PR TITLE
DOC-7565: Reply to messages page needs animated GIFs for mobile app workflows

### LINKED ISSUE #7565: Reply to messages page needs animated GIFs for mobile app workflows
## Context

To help visual learners learn how to perform tasks using the Mattermost mobile app, add visuals and short animated GIFs on the [Reply to messages](https://docs.mattermost.com/collaborate/reply-to-messages.html) page.

## Docs Request

- Add/update appropriate visuals/GIFs for all the steps in the `Reply to messages` section under the mobile app tab.

## Additional Notes

- Use the latest Mattermost mobile app and the standard Mattermost Denim theme to capture all workflows.
- Avoid drawing lines, arrows, boxes, or callouts on images.
- Don't forget to include ALT Text descriptions for all new image assets.
- Use existing docs pages with images as a starting point for code guidance. The Docs team can help provide RST syntax support for publication.
- Save static image files in PNG format within the docs repository's `/images` directory.

# QA Validation Criteria

In a generated docs preview:
- Visiting the docs page results in appropriate new mobile-specific screenshots in each subsection from the **Mobile** tab.

### PR DESCRIPTION
**Pull request by Rutam21**
### Summary

This PR adds visual workflows for the Mattermost mobile app tab on the [Reply to messages](https://docs.mattermost.com/collaborate/reply-to-messages.html) page.

### Ticket Link

Fixes #7565 

- [x] This PR follows Mattermost Contributing Guidelines.
- [x] The changes are tested in a local docs build.

### CODE REVIEW

**Comment by Rutam21** [comment]
@cwarnermm Please review and suggest changes, if any. Thanks.

**Comment by cwarnermm** [comment]
@Rutam21 - The image quality of these mobile images is considerably lower than others you've contributed recently. Is there a way to increase the image quality to avoid the checker-pattern effect when the image is displayed via docs?

Screenshot 2024-11-07 at 12 07 36 PM

**Comment by Rutam21** [comment]
@cwarnermm I have updated the GIFs. Please check if the image quality looks okay now.

**Comment by cwarnermm** [comment]
@Rutam21 - In your latest commit, I noticed that you changed the ``:scale:`` value for the screenshots. That hasn't improved the image quality (expected). The scale attribute resizes the image, it doesn't affect image quality.

I recommend reviewing your capture tool configuration -- that's likely where the lower-res quality is coming from.

**Comment by Rutam21** [comment]
@cwarnermm I have not only changed the scale but also updated the GIFs with totally newer ones. Please find the screenshot of the updated ones below. This is visible in the preview environment. Are you still seeing them pixelated or distorted?

Screenshot 2024-11-08 233748

**Review by cwarnermm — APPROVED** [review]
Thanks, @Rutam21!

**Pull request merged**
