### PR TITLE
Sphinx Tabbed Content

### PR DESCRIPTION
**Pull request by Sayanta66**
This is an approach. Help me fix it. So that this issue can be closed

Fixes : issue #4487 

#### Ticket Link

  Fixes https://github.com/mattermost/mattermost-server/issues/4487

### CODE REVIEW

**Comment by Sayanta66** [comment]
@justinegeffen This is an approach I tried. It has errors. Help me fix it

**Comment by justinegeffen** [comment]
Thanks, @Sayanta66! Have you had a chance to build this locally and see the changes? In the file preview the formatting of the changes is displaying as plain text and I'm curious as to what it looks like on your build. If you have a screenshot, that would be great.

To view the preview in GitHub, select the three dots at the top-right corner of the file and select "View file". That'll show you the preview.

**Comment by justinegeffen** [comment]
I've just looked at the file again and it may be related to the heading having been deleted. I'd try re-adding the heading to see whether that changes anything. :)

**Comment by Sayanta66** [comment]
It has errors regarding the format I guess. The format needs to be fixed.

**Comment by justinegeffen** [comment]
You mentioned it has errors - are they build errors or errors in what it looks like?

It is definitely related to formatting - possibly the header, or possibly related to indentation.

**Comment by Sayanta66** [comment]
indentation problems because the tab came in my build but the other things are not previewing. So probably problem with indentation

**Comment by justinegeffen** [comment]
If you can see the tabs in your build, please take a screenshot and share it - that would be super helpful in diagnosing the issue. :) That way we can see what you're seeing.

**Comment by Sayanta66** [comment]
image

**Comment by Sayanta66** [comment]
This is how it is coming

**Comment by Sayanta66** [comment]
The images are coming when it is pushed to the extreme left

**Comment by Sayanta66** [comment]
image

**Comment by justinegeffen** [comment]
Thank you for this PR, @Sayanta66! It's a great start to this complex change. We will need some time to look into this and do some testing on our side. While I don't have an ETA on our feedback, we will provide it when we have it. :)

**Comment by Sayanta66** [comment]
Yeah no worries....I will learn from you guys with this issue.

**Comment by justinegeffen** [comment]
Thank you for this PR and the work you put into this change. We've taken a look at the PR and assessed the amount of work involved in building and validating this solution. Unfortunately at this stage we won't be able to continue work on this PR and will be closing it. We appreciate your contribution. :)

**Pull request closed without merging**
