### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by JakobMiksch**
Minor typo

### CODE REVIEW

**Review by cwarnermm — APPROVED** [review]
Thank you, @JakobMiksch! Good catch!

**Comment by cwarnermm** [comment]
@JakobMiksch - We can merge your PR into the codebase once you sign the CLA. Thanks!

**Comment by JakobMiksch** [comment]
@cwarnermm signing the CLA seems a bit too complicated for me, taking into account this is just a typo of one character. 
Hereby, I publish this contribution as public domain. Feel free to merge it in an separate PR if that is easier for you.

**Comment by cwarnermm** [comment]
Thanks, @JakobMiksch. Really appreciate your flexibility on this.

**Pull request merged**
