### PR TITLE
Help Wanted: Mattermost for Microsoft Teams documentation would benefit from updated GIFs

### LINKED ISSUE #6907: Help Wanted: Mattermost for Microsoft Teams documentation would benefit from updated GIFs
# Context

The Mattermost UX team has created animated GIFs that will be used to supplement existing product documentation.

# Docs Request 
Incorporate the following animated GIFs into the Mattermost Product Documentation:

1. [Mattermost for Microsoft Teams](https://docs.mattermost.com/about/mattermost-for-microsoft-teams.html) - position this image to follow the end of the first sentence under **Connect Mattermost with Microsoft Teams**.

MSTeamsSync-channel-sync

2. [Collaborate within Microsoft Teams](https://docs.mattermost.com/collaborate/collaborate-within-connected-microsoft-teams.html) - position this image to follow the introductory sentence on the page.

MSTeamsSync-DM-sync

# How you can help

- The [Organize conversations using Collapsed Reply Threads](https://docs.mattermost.com/collaborate/organize-conversations.html) product documentation includes an animated GIF you can use as a starting point & reference. 
- Download a copy of each animated GIF file from this docs issue.
- Create a docs PR that adds the visuals to the product documentation.
- Don't forget to include ALT Text descriptions for the new images.

### PR DESCRIPTION
**Pull request by azigler**
Fixes #6907

### CODE REVIEW

**Comment by azigler** [comment]
Easy access links for testing:

- http://mattermost-docs-preview-pulls.s3-website-us-east-1.amazonaws.com/6937/about/mattermost-for-microsoft-teams.html
- http://mattermost-docs-preview-pulls.s3-website-us-east-1.amazonaws.com/6937/collaborate/collaborate-within-connected-microsoft-teams.html

@cwarnermm @johndavidlugtu this is ready for review now!

**Comment by johndavidlugtu** [comment]
Tangential but thoughts on introducing the `Beta` label on the documentation @cwarnermm ?

**Comment by cwarnermm** [comment]
@johndavidlugtu - Agreed; the ``Beta`` label should be added to the MS Teams documentation. I'll add it in a separate PR.

**Review by cwarnermm — APPROVED** [review]
Thanks, @azigler!!

**Review by johndavidlugtu — APPROVED** [review]

**Pull request merged**
