### PR TITLE
Updates to Deployment Solution Program

### PR DESCRIPTION
**Pull request by it33**

### CODE REVIEW

**Comment by esethna** [comment]
@it33 do you want this doc hidden from the TOC for now? The folder it's currently in should only be used for index files.

I think once it's ready it should go in the [source/deployment](https://github.com/mattermost/docs/tree/master/source/deployment) folder and then it can be added to the TOC via the ["administrator's guide" index file](https://github.com/mattermost/docs/blob/master/source/guides/administrator.rst)

**Comment by it33** [comment]
Thanks @esethna, not in TOC until it's more vetted. This update was just a small fix

**Comment by it33** [comment]
Thanks @esethna, can you help update the Handbook with your recommendation so anyone adding a new page do documentation understands the guideline?

**Comment by lfbrock** [comment]
+1, not sure what's going on with doc placement. Maybe if it needs to be moved it can be done in a separate PR.

**Comment by esethna** [comment]
@JeffSchering any recommendations on where we can add a small section to the doc guidelines on the repo folder structure/where to add new files?

**Pull request merged**
