### PR TITLE
Update telemetry.rst

### PR DESCRIPTION
**Pull request by justinegeffen**
- Updated telemetry doc to link to boards and playbooks telemetry files to stay current.
- Retained some of the boards content as it wasn't covered in the telemetry file - @jespino, please confirm that the content is correct. If not, I can remove it. Also let me know if you're not the DIR for telemetry! :) 
- @lieut-data, adding you as a reviewer in lieu of @agarciamontoro.

### CODE REVIEW

**Review by lieut-data — APPROVED** [review]

**Review by stephenvanhemmen — APPROVED** [review]
This is fantastic, looking forward to using this!

**Review by cwarnermm — APPROVED** [review]
Nicely done!

**Review by wuwinson — APPROVED** [review]
LGTM!

**Review by jespino — APPROVED** [review]
LGTM

**Comment by jespino** [comment]
@justinegeffen this is already reviewed by everybody, sorry for the delay

**Pull request merged**
