### PR TITLE
Fix incorrect WebSocket configuration for Apache2

### PR DESCRIPTION
**Pull request by fksu**
The condition for the Connection header usually failed as a browser
typically sends also keep-alive value in this header, hence changed
to word matching.

Then the OR conditions can be changed to the default ANDs allowing
other services requiring WebSockets to be proxied through the same
server.

### CODE REVIEW

**Comment by justinegeffen** [comment]
Approving editorially; @svelle, please can you confirm that the content is accurate. Thank you!

**Review by justinegeffen — APPROVED** [review]

**Comment by cwarnermm** [comment]
Thank you, @fksu! Are you open to signing the Mattermost CLA as part of this contribution?

**Comment by fksu** [comment]
Already done, see above.

**Review by cwarnermm — APPROVED** [review]
Thank you for this contribution! Next steps include a technical review for accuracy.

**Comment by justinegeffen** [comment]
@agarciamontoro, I wasn't sure who to ask for a dev review so I thought if you didn't know you may be able to give me a referral. :)

**Comment by agarciamontoro** [comment]
I know nothing about this, but @mrckndt has volunteered to take a look :)

**Review by mrckndt — APPROVED** [review]
Looks good to me

**Pull request merged**
