### PR TITLE
Remove information regarding self serve, the portal, etc

### PR DESCRIPTION
**Pull request by nickmisasi**
#### Summary
Removes information regarding self serve purchases, the portal, stripe, etc.

Some of the things I searched for:
- Stripe
- Credit card
- self serve
- customers.mattermost.com
- cloud free
- free
etc

I may have missed some places but I think I've gotten most of the important ones. 

#### Ticket Link
https://mattermost.atlassian.net/browse/CLD-7547

### CODE REVIEW

**Comment by cwarnermm** [comment]
@emdecr - There's a couple of [Customer Portal](https://customers.mattermost.com) links in the web navigation via docs via ``/source/_templates/custom-nav.html`` (and potentially also in web) that are impacted by self-serve & portal deprecations.  Can you help update the docs nav as part of this PR, please?

@amyblais - the ``/deploy/legacy-self-hosted-changelog.rst`` source page contains a reference to https://customers.mattermost.com that should either be removed or rephrased/redirected since users will see an error if they try to use that link. What's your preferred way forward?

**Comment by amyblais** [comment]
> the `/deploy/legacy-self-hosted-changelog.rst` source page contains a reference to https://customers.mattermost.com that should either be removed or rephrased/redirected since users will see an error if they try to use that link. What's your preferred way forward?

@cwarnermm I couldn't find the link https://customers.mattermost.com/ on that page just now - do you have a screenshot?

**Comment by amyblais** [comment]
@cwarnermm Thank you, I think that last sentence in that paragraph can be removed since it's an old release.

**Comment by emdecr** [comment]
@cwarnermm Happy to change link! Is there a bit more context around the depreciation somewhere? We link to the customers.mm.com site in a few instances on the mm.com side as well.

**Comment by cwarnermm** [comment]
Docs note: "users will still be able to create an account or log in to an existing one. Existing users will be able to see their subscriptions/licenses/invoices as well. They just won't be able to purchase a new subscription"

**Review by cwarnermm — APPROVED** [review]
Thank you, @nickmisasi!

**Pull request merged**
