### PR TITLE
Added open-external-links.js to open external links in new tab

### PR DESCRIPTION
**Pull request by rahulmansharamani14**
#### Summary

This PR ensures that all external links in the Mattermost documentation open in a new tab or window, addressing [Issue #7048](https://github.com/mattermost/docs/issues/7048).

**Changes Made**

- **Added `open-external-links.js`:**
  - Located in the `_static/js` directory.
  - Contains JavaScript code that adds `target="_blank"` to all external links.

- **Updated `conf.py`:**
  - Added `open-external-links.js` in the html_js_files list to include this file in the build process.

**Implementation Details**

- The script selects all `<a>` elements and checks if they have the `external` class.
- External links are modified to include `target="_blank"`, opening them in a new tab/window.

**Testing**

- Built the documentation locally using `make clean build`.
- Verified that:
  - External links open in a new tab/window.
  - Internal links open in the same tab/window.
- Tested across multiple pages.

**Notes**

- This solution depends on external links being assigned the external class by Sphinx during the build process.
- No additional dependencies are introduced.
- No changes to existing content or functionality other than modifying external link behavior.

Thank you for reviewing my PR. I'm open to any feedback or suggestions.

#### Ticket Link

Fixes https://github.com/mattermost/docs/issues/7048

### CODE REVIEW

**Comment by cwarnermm** [comment]
@rahulmansharamani14 - It looks like all links are opening in new browser windows right now, rather than only external links.

**Comment by rahulmansharamani14** [comment]
Hi @cwarnermm, Thank you for reviewing my PR and for your feedback.

I wanted to clarify that, based on my testing, internal links are opening in the same tab, while external links are opening in new tabs, which is the intended behavior.

Testing Details:

- Environment: I built the documentation locally using ```make html``` and served it using a local server at http://127.0.0.1:8000/.
- Internal Links: Links that point to the local domain (e.g: http://127.0.0.1:8000/some-page) open in the same tab.
- External Links: Links that point to external domains (e.g: https://mattermost.com) and have class="external" open in a new tab/window.
Examples:

### Internal Link:

URL: http://127.0.0.1:8000/developer/contribution-guide.html
Behavior: Opens in the same tab.

Screenshot:

Screenshot 2024-11-08 at 5 30 59 AM


### External Link:

URL: https://github.com/mattermost/mattermost-server
Behavior: Opens in a new tab/window.

Screenshot:

Screenshot 2024-11-08 at 5 31 24 AM


Possible Reasons for Different Behavior:

- Server Environment: Perhaps the difference arises if the documentation is viewed in a different environment or after deployment.
- Cache or Browser Extensions: Sometimes, cached files or browser extensions can affect link behaviors.


Could you please let me know if there's a specific page or link where you're seeing all links opening in new tabs? I'd be happy to investigate further. If there's a particular environment or method you're using to build and serve the documentation, please share the details so I can replicate it.

**Comment by cwarnermm** [comment]
@rahulmansharamani14 - There's a generated preview of the product docs that uses the code in this docs PR. In that preview environment (which mirrors production), I'm continuing to see links to pages of the product docs that open in a new browser window. 

Examples include:
- http://mattermost-docs-preview-pulls.s3-website-us-east-1.amazonaws.com/7540/about/mattermost-server-releases.html#frequency --> the **unsupported Mattermost legacy releases** link
- http://mattermost-docs-preview-pulls.s3-website-us-east-1.amazonaws.com/7540/deploy/manual-postgres-migration.html --> all of the links at the top of this docs page
- http://mattermost-docs-preview-pulls.s3-website-us-east-1.amazonaws.com/7540/integrate/jira-interoperability.html#mattermost-configuration --> Under 1d, the second bullet point's link to **install this Jira integration in your Jira instance**; the **legacy webhooks** link much further down the page behaves similarly
- http://mattermost-docs-preview-pulls.s3-website-us-east-1.amazonaws.com/7540/integrate/zoom-interoperability.html#enable --> the **connect their Zoom accounts to Mattermost** link

I haven't done an exhaustive search; however, a common pattern I'm seeing here is mid-page links (that should take the user to another section of the current document) opens a new browser tab.

**Comment by cwarnermm** [comment]
@rahulmansharamani14 - Are you open to addressing the outstanding issues on this docs PR?

**Comment by cwarnermm** [comment]
Closing due to inactivity.

**Pull request closed without merging**
