### PR TITLE
DOC-6760: Add a Note for the DataSource sslmode property in the Insta…

### LINKED ISSUE #6760: Help Wanted: Cannot connect to AWS Lightsail Postgres instance with sslmode=disable
#### Summary
The `sslmode=disable` as suggested by the [instructions](https://docs.mattermost.com/install/install-ubuntu.html) don't seem to be compatible with AWS Lightsail Postgres instances.

#### Steps to reproduce
1. Create an AWS Lightsail Postgres instance
2. Follow instructions to [setup mattermost database](https://docs.mattermost.com/install/prepare-mattermost-database.html)
3. Follow instructions to update mattermost config to use database.

#### Expected behavior
It should be able to connect to the database

#### Observed behavior (that appears unintentional) 

It gives the following error:

```
Nov 03 16:20:03 ip-172-26-5-245 mattermost[6201]: {"timestamp":"2023-11-03 16:20:03.028 Z","level":"error","msg":"failed to initialize platform: cannot create store: error setting up connections: pq: no pg_hba.conf entry for host \"172.26.5.245\", user \"mmuser\", database \"mattermost\", no encryption","caller":"commands/server.go:76"}
```

Note that AWS Lightsail is a managed postgres and does not allow direct control over `pg_hba.conf`

#### Possible fixes

Workaround: Changing the config to `sslmode=require` worked for me.

Fix: Update the docs to mention that the `sslmode` setting may depend on your particular environment.

# QA Validation Criteria

In a generated docs preview:
- Visiting the docs page directly returns details in a note at the end of the Setup section on the value of the sslmode property.

### PR DESCRIPTION
**Pull request by Rutam21**
### Summary

This PR adds a note in the `Install Mattermost Server on Ubuntu` page under the `Setup` section so that the users can understand how to set the correct value of the `sslmode` property.

### Ticket Link

Fixes #6760 

- [x] This PR follows the Mattermost Contributing Guidelines.

### CODE REVIEW

**Comment by Rutam21** [comment]
@cwarnermm Please review and suggest changes, if any. Thanks.

**Review by cwarnermm — APPROVED** [review]
Thanks, @Rutam21!

**Comment by Rutam21** [comment]
@lindy65 Please assign this PR to me for QA Testing. Thanks.

**Comment by lindy65** [comment]
Assigned to you @Rutam21

**Comment by Rutam21** [comment]
### The changes in this PR have been tested in the preview environment and all the required changes are available in the mentioned pages.

- A new and properly formatted `Note` has been added under the `Setup` section on the `Install Mattermost Server on Ubuntu` page with the suggested information.

I've attached a video as a confirmation.

https://github.com/user-attachments/assets/7f8a207c-325e-46d8-a1c8-858ff8b44c11

cc: @lindy65

**Comment by lindy65** [comment]
Thanks @Rutam21 - counted towards Hacktoberfest!

cc @cwarnermm

**Pull request merged**
