### PR TITLE
Documentation for ExperimentalEnableHardenedMode

### PR DESCRIPTION
**Pull request by crspeller**
Documentation for https://github.com/mattermost/mattermost-server/pull/8881

### CODE REVIEW

**Comment by crspeller** [comment]
@jasonblais When it stops being experimental, yes.

**Comment by jasonblais** [comment]
@crspeller Makes sense - what is our plan to get it out of experimental?

**Comment by crspeller** [comment]
The idea is to try it out on pre-release to find any issues. Maybe see if there is customer interest in actually turning it on.

**Comment by crspeller** [comment]
@jasonblais Pr is merged. https://github.com/mattermost/mattermost-server/pull/8881

**Comment by jasonblais** [comment]
@crspeller thanks - can you help rebase against the `v5.0-documentation` branch and we'll merge this PR.

**Pull request merged**
