### PR TITLE
WIP : Display code copy button for all inline code formatted text #5912

### PR DESCRIPTION
**Pull request by jpphilips**
#### Summary
Enable the copy code option on all code samples across the product documentation site.

#### Ticket Link
Fixes https://github.com/mattermost/docs/issues/5912

### CODE REVIEW

**Comment by justinegeffen** [comment]
I've checked in the preview and using this page http://mattermost-docs-preview-pulls.s3-website-us-east-1.amazonaws.com/5927/install/installing-ubuntu-2004-LTS.html but it doesn't look like a change has been effected. 

cc @cwarnermm @neflyte

**Comment by jpphilips** [comment]
Alright. Thanks for the feedback. Will continue working on it. 
clicking on the link you provided will test recent changes, yes?

**Comment by jpphilips** [comment]
Looking at the link you posted, the copy button is on the inline codes but it seems to me that it's now a css issue and involves changing the position of the button.
image
I adjusted the positioning and opacity just to illustrate.

**Comment by jpphilips** [comment]
adjusting the below css properties of the buttton should give the desired result for the inline code but will move the button position for the code block as well.

positioning : relative
display : unset
margin-left : 0.4em 

-screenshot when i see the change on the server

**Comment by neflyte** [comment]
I don't see any additional page elements that have a copy button with this change.
For example, in the preview: http://mattermost-docs-preview-pulls.s3-website-us-east-1.amazonaws.com/5927/install/installing-ubuntu-1804-LTS.html

**Comment by jpphilips** [comment]
@cwarnermm @justinegeffen 
for inline code:
image

for code block:
image

changes to the copy button for the inline code currently affects the block code.

**Comment by justinegeffen** [comment]
Thanks, @jpphilips, this is looking great!!

> changes to the copy button for the inline code currently affects the block code.

Would you be able to elaborate on that?

**Comment by cwarnermm** [comment]
@neflyte - This PR introduces an inline code copy/paste option. Do you know of a way forward that would allow us to adjust the copy/paste option for code blocks separately from inline code?

**Comment by neflyte** [comment]
@cwarnermm Possibly; I'd need to see an updated preview.

**Comment by neflyte** [comment]
I'm not sure what's going on but this page (http://mattermost-docs-preview-pulls.s3-website-us-east-1.amazonaws.com/5927/onboard/shared-channels.html) has a huge "Mattermost" text behind the page content. That needs to be fixed up.

**Comment by neflyte** [comment]
@jpphilips Could you direct me to a page in the preview environment that shows the copy button for inline code? I can't seem to find one.

**Comment by jpphilips** [comment]
@neflyte sorry, it's not visible on hover but if youn place ur cusor beside the code in this page (http://mattermost-docs-preview-pulls.s3-website-us-east-1.amazonaws.com/5927/guides/deployment.html) you'll see 'copy to clipboard' and be able to copy the code.
I just updated the custom css and it should display on hover in a new preview environment but the button is in the flow of the document. Not so nice. Yet to be resolved.

**Comment by neflyte** [comment]
@jpphilips Thanks! I see the copy button now and I'll take a look to see what we can do :)

**Comment by cwarnermm** [comment]
@jpphilips - You've done some great work on this PR, and you've helped our team realize that we need to review and convert many or most of the inline code examples across the docs set to code blocks, rather than try to offer a copy/paste option for that kind of inline text.

Given that we're changing direction, we won't be moving forward with this product documentation update and I'll be closing this PR and its help wanted ticket. 

Please note that your great work on this ticket hasn't gone unnoticed, and it'll be counted as a Hacktoberfest contribution. It's because of your hard work that we took a deeper dive and identified a deeper root cause we want to address in the docs.

**Pull request closed without merging**
