### PR TITLE
Update formatting-text.rst

### PR DESCRIPTION
**Pull request by jasel-lewis**
#### Summary
Improper escaping of backticks. Documentation was displaying three backslashes instead of backticks.

### CODE REVIEW

**Review by cwarnermm — APPROVED** [review]
Thank you, @jasel-lewis, for this documentation update. We really appreciate your submission! Are you open to completing the Mattermost contribution license agreement? If so, please see the details on how to do so in this PR. Doing so means that you receive credit for contributing this update.

**Comment by jasel-lewis** [comment]
@cwarnermm CLA completed (I think... process didn't seem to really have a clear end state).

**Comment by cpanato** [comment]
looks like some issues on the GH actions side, will wait a bit

**Pull request closed without merging**
