### PR TITLE
Move security policies from legacy handbook to a subsection in Security Overview

### PR DESCRIPTION
**Pull request by jasonblais**
Intent of this PR is to move [Security Policies](https://docs.mattermost.com/process/security.html) out of the legacy handbook.

Proposal is to add it as a subsection of Security Overview section, where it is already referenced:

image

Although I have not tested locally, the approach in this PR should allow us to add the Security Policies page as a subsection -- this same approach is used for SAML 2.0 docs, where Okta, OneLogin and ADFS docs are their standalone pages but appear as subsections of the master SAML 2.0 doc:

image

### CODE REVIEW

**Comment by justinegeffen** [comment]
I did a local build for this and it looks like this page hasn't been structured correctly, as there are no subsections. You can see the difference in the screenshots below. 

@jasonblais, can I confirm that the Security page is meant to be structured in a similar way to the Architecture Overview (as an example) so the subsections appear in the LHS navigation? It also looks like the reference to "Security Policies" may be circular as the link is within its own section. 

I'm happy to do the reorganizing if this is the case. :) 
Screen Shot 2020-05-01 at 12 02 46

Screen Shot 2020-05-01 at 12 02 38

Screen Shot 2020-05-01 at 12 00 39

**Comment by jasonblais** [comment]
Thank you @justinegeffen! 

What I intent is to structure it similar to SAML 2.0 docs in the attached
image

Specifically, 
1. `Okta SAML Configuration`, `OneLogin SAML Configuration` and the two Microsoft ADFS configurations are referenced in the main `SAML Single-Sign-On (E20)` page
2. Each of these configurations are their own pages
3. Each of these configurations appear as subsections in the LHS dropdown navigation

Moreover, there may be other subsections within the LHS dropdown navigation, such as `Using SAML Attributes to Apply Roles` - but which exist within the main `SAML Single-Sign-On (E20)` page.

So, similarly, my intent is to have
1. `Security Policies` referenced in the main `Security Overview` page,
2. have it as its own page, but
3. have it appear as a subsection within the LHS nav

Let me know if I can help clarify

**Comment by justinegeffen** [comment]
Thanks, @jasonblais. I'm definitely in favor of that. I can work on the formatting - would Monday work for the update?

**Comment by jasonblais** [comment]
@justinegeffen Thank you! And next week works great, not urgent :+1:

**Comment by TQuock** [comment]
@justinegeffen - the proposal makes sense and it pushes customers/users to the correct landing page. I do think that @DSchalla, Melissa Warner, Natalie Jew, and I need to do some additional vetting on the content and what we are opining on. I honestly have not spent much time on these controls and whether these are still relevant for our environment. My initial thoughts are this is not an accurate list. For example, `Is a background screening performed prior to allowing personnel access to Scoped Systems and Data?`. The answer to that is no. We don't have HR background screening process nor have we defined what encompasses that background screening process. 

@DSchalla - whats are your thoughts?

**Comment by jasonblais** [comment]
@justinegeffen one consideration from editing perspective, is that we may want to ensure the old page (https://docs.mattermost.com/process/security.html) asks the user to go to the new URL. Similar to https://docs.mattermost.com/process/feature-release.html

**Comment by justinegeffen** [comment]
Good catch, @jasonblais, I forgot to do that. It's been updated to reflect your suggestion. :)

**Comment by justinegeffen** [comment]
@DSchalla, @TQuock, wanted to follow up on this and update the doc with your changes/feedback. :)

**Comment by jasonblais** [comment]
@justinegeffen @DSchalla Any next steps here? I'd propose vetting of content is done separately, as this PR simply moves the content to another page.

**Comment by justinegeffen** [comment]
I'm happy with the content and moving the vetting to another PR. 

If everyone is happy with that, I'll fix the conflicts and merge.

**Comment by justinegeffen** [comment]
Following up on this, @TQuock and @DSchalla. :)

**Comment by justinegeffen** [comment]
@DSchalla, @TQuock; following up on this as this PR is simply to move the content from one place to another. I'm 5/5 on vetting being required but as the content is already published, could that be done in a new PR or offline? :)

**Comment by DSchalla** [comment]
Hi @justinegeffen,

if it's primarily about migrating them away, could we move them to handbook.mattermost.com since they are not product related but rather about internal controls? My biggest concern is mixing up product and internal documentation.

**Comment by justinegeffen** [comment]
Hi @DSchalla. That is a very valid point. However, reading through this content, I am torn between the handbook and the docs. The content covers information that customers may want to know but is also relevant internally. 

I propose merging this as per this PR. But, there is a need for this content to be in the Handbook. I'd just need some time to find the right place, as it would be a good time to add the Security team's processes etc to the Handbook.

@jasonblais, what do you think? I'm 0/5 and happy to go with either merging this or closing it and opening a Handbook PR.

**Comment by jasonblais** [comment]
@justinegeffen @DSchalla I'm fine moving this to the handbook as well, and linking from our Security Overview page there. We could have it in https://handbook.mattermost.com/operations/operations/company-policies for now.

Will defer to @TQuock if the page needs to be in the 'official' docs for customer contract purposes. My guess is not, as long as the page is publicly accessible.

**Comment by justinegeffen** [comment]
That works for me, @jasonblais. I'll move it over to the handbook. :)

**Comment by TQuock** [comment]
I am in agreement that we can vet the content through a new PR. Sorry for the delay

**Review by TQuock — APPROVED** [review]
Approved to move this and to review the content in separate PR.

**Comment by justinegeffen** [comment]
Handbook PR: https://github.com/mattermost/mattermost-handbook/pull/426. Closing this PR.

**Comment by justinegeffen** [comment]
Docs PR: https://github.com/mattermost/docs/pull/3881.

**Pull request closed without merging**
