### PR TITLE
Fixed a typo in the troubleshooting section of make-calls

### PR DESCRIPTION
**Pull request by gbyx3**
Summary
Fixed a typo in the troubleshooting section of make-calls

Ticket Link
N/A

Checklist
Includes text changes, file (https://github.com/mattermost/docs/blob/master/source/channels/make-calls.rst) updates

### CODE REVIEW

**Comment by justinegeffen** [comment]
Thanks, @gbyx3! Would you be open to confirming whether the original content produced an error when used?

**Comment by gbyx3** [comment]
> Thanks, @gbyx3! Would you be open to confirming whether the original content produced an error when used?

Hi @justinegeffen no error was produces, I found it because my console filter (`rtc: client`)didn't match the expected output

**Review by justinegeffen — APPROVED** [review]

**Comment by justinegeffen** [comment]
Awesome, thank you for this PR, @gbyx3! :)

**Review by streamer45 — APPROVED** [review]
Thanks @gbyx3 :100:

**Pull request merged**
